### PR TITLE
Nightly builds fixes

### PR DESCRIPTION
**Pull request by lucbv**

### CODE REVIEW

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight to start: Total Wait = 3603
- Other jobs have been previously started - We must stop them...

**Review by ndellingwood — APPROVED** [review]
Thanks @lucbv !

**Comment by ndellingwood** [comment]
@lucbv to address the `Kokkos::pair` related build errors (cuda/11.0 nightly build), don't we need to also provide the types as template arguments, i.e.

```diff
[ndellin@kokkos-dev-2 kokkos-kernels]$ git diff
diff --git a/sparse/unit_test/Test_Sparse_spmv_bsr.hpp b/sparse/unit_test/Test_Sparse_spmv_bsr.hpp
index 3623778..2c2cbd1 100644
--- a/sparse/unit_test/Test_Sparse_spmv_bsr.hpp
+++ b/sparse/unit_test/Test_Sparse_spmv_bsr.hpp
@@ -116,9 +116,9 @@ Bsr bsr_random(const int blockSize, const int blockRows, const int blockCols) {
       rcs(blockRows, blockCols, scalar_type(0), max_a<scalar_type>());
 
   const auto colids =
-      Kokkos::subview(rcs.get_ids(), Kokkos::pair{size_t(0), rcs.get_nnz()});
+      Kokkos::subview(rcs.get_ids(), Kokkos::pair<size_t, decltype(rcs.get_nnz())>{size_t(0), rcs.get_nnz()});
   const auto vals =
-      Kokkos::subview(rcs.get_vals(), Kokkos::pair{size_t(0), rcs.get_nnz()});
+      Kokkos::subview(rcs.get_vals(), Kokkos::pair<size_t, decltype(rcs.get_nnz())>{size_t(0), rcs.get_nnz()});
   Graph graph(colids, rcs.get_map());
   Crs crs("crs", blockCols, vals, graph);
```

I tried this to resolve errors of form
```
/ascldap/users/ndellin/kokkos-kernels/sparse/unit_test/Test_Sparse_spmv_bsr.hpp:118:54: error: ‘pair’ was not declared in this scope
  118 |   const auto colids =
      |                                                      ^
/ascldap/users/ndellin/kokkos-kernels/sparse/unit_test/Test_Sparse_spmv_bsr.hpp:118:54: note: suggested alternatives:
/net/watson.sandia.gov/storage/fast/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/base/include/c++/9.2.0/bits/stl_pair.h:208:8: note:   ‘std::pair’
  208 |     struct pair
      |        ^~~~
/home/ndellin/kokkos-kernels/kokkos-install/include/Kokkos_Pair.hpp:43:8: note:   ‘Kokkos::pair’
   43 | struct pair {
      |        ^~~~
/usr/local/cuda-11.0//bin/../targets/x86_64-linux/include/thrust/pair.h:49:8: note:   ‘thrust::pair’
   49 |   struct pair
      |        ^~~~
/ascldap/users/ndellin/kokkos-kernels/sparse/unit_test/Test_Sparse_spmv_bsr.hpp:120:57: error: expected ‘)’ before ‘{’ token
  120 |   const auto vals =
```

**Comment by ndellingwood** [comment]
@lucbv I can commit the changes above (clang-formatted) to your branch if you like, let me know

**Comment by lucbv** [comment]
That's a good question, I only tried on host and I'm pretty sure that's not where the main problem happens...
If you have the fix, yes feel free to submit it, ping me if I need to invite you to my fork or something like that?

**Comment by ndellingwood** [comment]
@lucbv I pushed the update to add the missing Kokkos::pair template args d74c72bafb41b67197fd739d851ba7c8cd8bc1c1

This branch successfully compiles with the failing nightly configure. There are still warnings that need to be addressed (likely unrelated) but that can be done later

**Warnings present**
```
/ascldap/users/ndellin/kokkos-kernels/common/unit_test/Test_Common_UpperBound.hpp(190): warning: missing return statement at end of non-void function "lambda [](int)->int"
          detected during instantiation of "void test_upper_bound<T,Device>() [with T=int, Device=Kokkos::Serial]" 
(220): here

/ascldap/users/ndellin/kokkos-kernels/common/unit_test/Test_Common_UpperBound.hpp(190): warning: missing return statement at end of non-void function "lambda [](size_t)->unsigned long"
          detected during instantiation of "void test_upper_bound<T,Device>() [with T=size_t, Device=Kokkos::Serial]" 
(232): here

/ascldap/users/ndellin/kokkos-kernels/common/unit_test/Test_Common_UpperBound.hpp(190): warning: missing return statement at end of non-void function "lambda [](double)->double"
          detected during instantiation of "void test_upper_bound<T,Device>() [with T=double, Device=Kokkos::Serial]" 
(244): here

/ascldap/users/ndellin/kokkos-kernels/common/unit_test/Test_Common_UpperBound.hpp(190): warning: missing return statement at end of non-void function "lambda [](int)->int"
          detected during instantiation of "void test_upper_bound<T,Device>() [with T=int, Device=Kokkos::Cuda]" 
(220): here

/ascldap/users/ndellin/kokkos-kernels/common/unit_test/Test_Common_UpperBound.hpp(190): warning: missing return statement at end of non-void function "lambda [](size_t)->unsigned long"
          detected during instantiation of "void test_upper_bound<T,Device>() [with T=size_t, Device=Kokkos::Cuda]" 
(232): here

/ascldap/users/ndellin/kokkos-kernels/common/unit_test/Test_Common_UpperBound.hpp(190): warning: missing return statement at end of non-void function "lambda [](double)->double"
          detected during instantiation of "void test_upper_bound<T,Device>() [with T=double, Device=Kokkos::Cuda]" 
(244): here
```

**Reproducer** (kokkos-dev-2):
```
module load sems-archive-env sems-archive-cmake/3.17.1 sems-archive-gcc/9.2.0 cuda/11.0

$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Cuda,Serial --arch=Volta70 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-options=disable_deprecated_code --with-cuda-options=enable_lambda   --no-examples
```

**Comment by lucbv** [comment]
Closing in favor of PR #1826

**Pull request closed without merging**
