### PR TITLE
trsv team vector interface fix.

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
As reported in #729, I did not use team vector interface with algorithm tag. For consistency with other codes and users' testing and developement capabilities, I add algorithm tag. 

Tests screen capture will be added later.

### CODE REVIEW

**Comment by kyungjoo-kim** [comment]
@DavidPoliakoff

**Comment by kyungjoo-kim** [comment]
kokkos-dev-2
```
[kyukim @kokkos-dev-2] test-all > ../../../kyukim/scripts/cm_test_all_sandia cuda/10.1 clang/8.0 gcc/4.8.4 gcc/4.9.3 gcc/9.2.0 intel/17.0.1 intel/18.0.5 intel/19.0.5
Running on machine: kokkos-dev-2
KokkosKernels Repository Status:  eb1c0983ced6ddce3b254e2a70fb8909ef5eb9da KokkosBatched - add algorithm tag for internal interface

Kokkos Repository Status:  7c1ab6cc7066d6b7efecdfd8cfc54482cae65caf Merge pull request #2957 from aprokop/install_trilinos_version

#######################################################
PASSED TESTS
#######################################################
cuda-10.1-Cuda_Pthread-release build_time=758 run_time=145
cuda-10.1-Cuda_Serial-release build_time=820 run_time=154
gcc-4.8.4-OpenMP-release build_time=112 run_time=59
gcc-4.8.4-OpenMP_Serial-release build_time=214 run_time=129
gcc-4.8.4-Pthread-release build_time=100 run_time=54
gcc-4.8.4-Pthread_Serial-release build_time=175 run_time=133
gcc-4.8.4-Serial-release build_time=105 run_time=69
gcc-4.9.3-OpenMP-release build_time=121 run_time=58
gcc-4.9.3-OpenMP_Serial-release build_time=228 run_time=129
gcc-4.9.3-Pthread-release build_time=96 run_time=55
gcc-4.9.3-Pthread_Serial-release build_time=195 run_time=133
gcc-4.9.3-Serial-release build_time=119 run_time=68
gcc-9.2.0-OpenMP-release build_time=186 run_time=61
gcc-9.2.0-OpenMP_Serial-release build_time=294 run_time=124
gcc-9.2.0-Pthread-release build_time=145 run_time=56
gcc-9.2.0-Pthread_Serial-release build_time=254 run_time=113
gcc-9.2.0-Serial-release build_time=158 run_time=59
intel-17.0.1-OpenMP-release build_time=313 run_time=53
intel-17.0.1-OpenMP_Serial-release build_time=533 run_time=117
intel-17.0.1-Pthread-release build_time=226 run_time=50
intel-17.0.1-Pthread_Serial-release build_time=396 run_time=110
intel-17.0.1-Serial-release build_time=240 run_time=58
intel-18.0.5-OpenMP-release build_time=356 run_time=54
intel-18.0.5-OpenMP_Serial-release build_time=653 run_time=117
intel-18.0.5-Pthread-release build_time=245 run_time=49
intel-18.0.5-Pthread_Serial-release build_time=464 run_time=108
intel-18.0.5-Serial-release build_time=251 run_time=55
intel-19.0.5-OpenMP-release build_time=393 run_time=52
intel-19.0.5-OpenMP_Serial-release build_time=699 run_time=112
intel-19.0.5-Pthread-release build_time=451 run_time=47
intel-19.0.5-Pthread_Serial-release build_time=706 run_time=103
intel-19.0.5-Serial-release build_time=455 run_time=55
```

**Comment by kyungjoo-kim** [comment]
I cannot run the full tests (without giving a compiler list). It takes forever. I waited more than 6 hours and it still compiles and tests.

**Comment by ndellingwood** [comment]
@kyungjoo-kim did the issue fixed by your PR require testing configurations skipped by either the spot-check or spot-check-tpls options? We can update the spot-check options if so that way you don't have to run the full checks over each compiler.

**Comment by ndellingwood** [comment]
@kyungjoo-kim your first run looks pretty thorough, I'd just run with the --spot-check-tpls option to make sure changes do not inadvertently have effect when tpls are enabled.

**Comment by kyungjoo-kim** [comment]
Now I have kokkos-dev-2 test output. Is clang 8 with cuda known issue ? I will attach kokkos-dev later. It is on going.
```
/// kokkos-dev-2 without tpls
#######################################################
PASSED TESTS
#######################################################
clang-8.0-Pthread_Serial-release build_time=207 run_time=119
clang-9.0.0-Pthread-release build_time=119 run_time=56
clang-9.0.0-Serial-release build_time=130 run_time=58
cuda-10.1-Cuda_OpenMP-release build_time=924 run_time=154
cuda-9.2-Cuda_Serial-release build_time=927 run_time=178
gcc-4.8.4-OpenMP-release build_time=116 run_time=56
gcc-7.3.0-OpenMP-release build_time=140 run_time=61
gcc-7.3.0-Pthread-release build_time=122 run_time=58
gcc-8.3.0-Serial-release build_time=140 run_time=63
gcc-9.1-OpenMP-release build_time=180 run_time=59
gcc-9.1-Serial-release build_time=161 run_time=63
intel-17.0.1-Serial-release build_time=249 run_time=62
intel-18.0.5-OpenMP-release build_time=372 run_time=54
intel-19.0.5-Pthread-release build_time=493 run_time=52
#######################################################
FAILED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release (build failed)
#######################################################

/// kokkos-dev-2 with tpls
#######################################################
PASSED TESTS
#######################################################
clang-8.0-Pthread_Serial-release build_time=208 run_time=120
clang-9.0.0-Pthread-release build_time=133 run_time=59
clang-9.0.0-Serial-release build_time=124 run_time=62
cuda-10.1-Cuda_OpenMP-release build_time=913 run_time=167
gcc-4.8.4-OpenMP-release build_time=116 run_time=59
gcc-7.3.0-OpenMP-release build_time=143 run_time=61
gcc-7.3.0-Pthread-release build_time=116 run_time=59
gcc-8.3.0-Serial-release build_time=138 run_time=64
gcc-9.1-OpenMP-release build_time=182 run_time=61
gcc-9.1-Serial-release build_time=160 run_time=64
intel-17.0.1-Serial-release build_time=252 run_time=64
intel-18.0.5-OpenMP-release build_time=373 run_time=55
intel-19.0.5-Pthread-release build_time=476 run_time=53
#######################################################
FAILED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release (build failed)
#######################################################
```

**Comment by lucbv** [comment]
@kyungjoo-kim if you see something related to alignment with complex numbers in your clang build then you need to update you kokkos repo, @brian-kelley fixed something there not so long ago.

**Comment by kyungjoo-kim** [comment]
kokkos-dev, kepler architecture.

@lucbv The build error does not relate to the complex alignment. The following output is from tpl spot check. The TRMM code goes into some kokkos implementation. With TPLs, is this normal ? 

with tpls
```
#######################################################
PASSED TESTS
#######################################################
clang-4.0.1-Pthread_Serial-hwloc-release build_time=309 run_time=128
clang-4.0.1-Pthread_Serial-release build_time=309 run_time=128
cuda-9.2-Cuda_OpenMP-release build_time=1136 run_time=287
gcc-5.3.0-OpenMP-hwloc-release build_time=215 run_time=63
gcc-5.3.0-OpenMP-release build_time=215 run_time=63
gcc-7.3.0-Serial-hwloc-release build_time=296 run_time=67
gcc-7.3.0-Serial-release build_time=292 run_time=66
intel-16.0.3-Pthread-hwloc-release build_time=300 run_time=55
intel-16.0.3-Pthread-release build_time=369 run_time=64
intel-16.0.3-Serial-hwloc-release build_time=396 run_time=74
intel-16.0.3-Serial-release build_time=387 run_time=74
intel-17.0.1-OpenMP-hwloc-release build_time=434 run_time=52
intel-17.0.1-OpenMP-release build_time=438 run_time=52
#######################################################
FAILED TESTS
#######################################################
clang-7.0.1-Cuda_OpenMP-hwloc-release (build failed)
#######################################################
```


```
/home/kyukim/Work/lib/kokkoskernels/master/perf_test/blas/blas3/KokkosBlas3_trmm_perf_test.hpp:303:17: error: reference to __host__ function 'trmm<Kokkos::View<double **, Kokkos::LayoutStride, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>, Kokkos::MemoryTraits<0> >, Kokkos::View<double **, Kokkos::LayoutStride, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>, Kokkos::MemoryTraits<0> > >' in __host__ __device__ function
    KokkosBlas::trmm(&trmm_args_.side, &trmm_args_.uplo, &trmm_args_.trans,
                ^
/home/kyukim/Work/lib/kokkoskernels/build/kokkos-dev/test-all/TestAll_2020-06-02_20.56.20/clang/7.0.1/Cuda_OpenMP-hwloc-release/kokkos-install/include/Cuda/Kokkos_Cuda_Parallel.hpp:587:5: note: in instantiation of member function 'parallel_blas_trmm<Kokkos::Cuda>::operator()' requested here
    m_functor(i);
    ^
/home/kyukim/Work/lib/kokkoskernels/build/kokkos-dev/test-all/TestAll_2020-06-02_20.56.20/clang/7.0.1/Cuda_OpenMP-hwloc-release/kokkos-install/include/Cuda/Kokkos_Cuda_Parallel.hpp:609:22: note: in instantiation of function template specialization 'Kokkos::Impl::ParallelFor<parallel_blas_trmm<Kokkos::Cuda>, Kokkos::RangePolicy<Kokkos::Cuda>, Kokkos::Cuda>::exec_range<void>' requested here
      this->template exec_range<WorkTag>(iwork);
                     ^
/home/kyukim/Work/lib/kokkoskernels/build/kokkos-dev/test-all/TestAll_2020-06-02_20.56.20/clang/7.0.1/Cuda_OpenMP-hwloc-release/kokkos-install/include/Cuda/Kokkos_Cuda_KernelLaunch.hpp:124:3: note: in instantiation of member function 'Kokkos::Impl::ParallelFor<parallel_blas_trmm<Kokkos::Cuda>, Kokkos::RangePolicy<Kokkos::Cuda>, Kokkos::Cuda>::operator()' requested here
  driver();
  ^
/home/kyukim/Work/lib/kokkoskernels/build/kokkos-dev/test-all/TestAll_2020-06-02_20.56.20/clang/7.0.1/Cuda_OpenMP-hwloc-release/kokkos-install/include/Cuda/Kokkos_Cuda_KernelLaunch.hpp:448:16: note: in instantiation of function template specialization 'Kokkos::Impl::cuda_parallel_launch_local_memory<Kokkos::Impl::ParallelFor<parallel_blas_trmm<Kokkos::Cuda>, Kokkos::RangePolicy<Kokkos::Cuda>, Kokkos::Cuda> >' requested here
        &attr, cuda_parallel_launch_local_memory<DriverType>));
               ^
/home/kyukim/Work/lib/kokkoskernels/build/kokkos-dev/test-all/TestAll_2020-06-02_20.56.20/clang/7.0.1/Cuda_OpenMP-hwloc-release/kokkos-install/include/Cuda/Kokkos_Cuda_Parallel.hpp:618:43: note: in instantiation of member function 'Kokkos::Impl::CudaParallelLaunch<Kokkos::Impl::ParallelFor<parallel_blas_trmm<Kokkos::Cuda>, Kokkos::RangePolicy<Kokkos::Cuda>, Kokkos::Cuda>, Kokkos::LaunchBounds<0, 0>, Kokkos::Impl::Experimental::CudaLaunchMechanism::LocalMemory>::get_cuda_func_attributes' requested here
                           LaunchBounds>::get_cuda_func_attributes();
                                          ^
/home/kyukim/Work/lib/kokkoskernels/build/kokkos-dev/test-all/TestAll_2020-06-02_20.56.20/clang/7.0.1/Cuda_OpenMP-hwloc-release/kokkos-install/include/Kokkos_Parallel.hpp:182:11: note: in instantiation of member function 'Kokkos::Impl::ParallelFor<parallel_blas_trmm<Kokkos::Cuda>, Kokkos::RangePolicy<Kokkos::Cuda>, Kokkos::Cuda>::execute' requested here
  closure.execute();
          ^
/home/kyukim/Work/lib/kokkoskernels/build/kokkos-dev/test-all/TestAll_2020-06-02_20.56.20/clang/7.0.1/Cuda_OpenMP-hwloc-release/kokkos-install/include/Kokkos_Parallel.hpp:232:13: note: in instantiation of function template specialization 'Kokkos::parallel_for<Kokkos::RangePolicy<Kokkos::Cuda>, parallel_blas_trmm<Kokkos::Cuda> >' requested here
  ::Kokkos::parallel_for(policy, functor, str);
            ^
/home/kyukim/Work/lib/kokkoskernels/master/perf_test/blas/blas3/KokkosBlas3_trmm_perf_test.hpp:319:11: note: in instantiation of function template specialization 'Kokkos::parallel_for<Kokkos::RangePolicy<Kokkos::Cuda>, parallel_blas_trmm<Kokkos::Cuda> >' requested here
  Kokkos::parallel_for("parallelBlasWarmUpLoopTrmm",
          ^
/home/kyukim/Work/lib/kokkoskernels/master/perf_test/blas/blas3/KokkosBlas3_trmm_perf_test.hpp:583:24: note: in instantiation of function template specialization '__do_trmm_parallel_blas<double, Kokkos::View<double ***, Kokkos::LayoutLeft, Kokkos::Cuda>, Kokkos::View<double ***, Kokkos::LayoutLeft, Kokkos::Cuda>, Kokkos::Cuda>' requested here
                       __do_trmm_parallel_blas<default_scalar, view_type_3d,
                       ^
/home/kyukim/Work/lib/kokkoskernels/build/kokkos-dev/test-all/TestAll_2020-06-02_20.56.20/clang/7.0.1/Cuda_OpenMP-hwloc-release/kokkos-install/include/Cuda/Kokkos_Cuda_Parallel.hpp:587:5: note: called by 'exec_range<void>'
    m_functor(i);
    ^
/home/kyukim/Work/lib/kokkoskernels/build/kokkos-dev/test-all/TestAll_2020-06-02_20.56.20/clang/7.0.1/Cuda_OpenMP-hwloc-release/kokkos-install/include/Cuda/Kokkos_Cuda_Parallel.hpp:609:22: note: called by 'operator()'
      this->template exec_range<WorkTag>(iwork);
                     ^
/home/kyukim/Work/lib/kokkoskernels/build/kokkos-dev/test-all/TestAll_2020-06-02_20.56.20/clang/7.0.1/Cuda_OpenMP-hwloc-release/kokkos-install/include/Cuda/Kokkos_Cuda_KernelLaunch.hpp:124:3: note: called by 'cuda_parallel_launch_local_memory<Kokkos::Impl::ParallelFor<parallel_blas_trmm<Kokkos::Cuda>, Kokkos::RangePolicy<Kokkos::Cuda>, Kokkos::Cuda> >'
  driver();
  ^
```

**Comment by kyungjoo-kim** [comment]
kokkos-dev without TPLS. I missed the output summary. 
The failed test is cuda with clang. This is consistent with the previous failure in kokkos-dev-2. The error is calling host function from a device. Other cuda builds are okay. So, this may consider it as an error of warning. Anyone encounter the same error ? 
```
[kyukim @kokkos-dev] results > la failed/
total 16
drwxr-xr-x 2 kyukim users 4096 Jun  3 09:15 .
drwxr-xr-x 4 kyukim users 4096 Jun  3 07:28 ..
-rw-r--r-- 1 kyukim users    6 Jun  3 09:15 clang-7.0.1-Cuda_OpenMP-hwloc-release
-rw-r--r-- 1 kyukim users    6 Jun  3 09:01 clang-7.0.1-Cuda_OpenMP-release
[kyukim @kokkos-dev] results > la passed/
total 60
drwxr-xr-x 2 kyukim users 4096 Jun  3 09:39 .
drwxr-xr-x 4 kyukim users 4096 Jun  3 07:28 ..
-rw-r--r-- 1 kyukim users   28 Jun  3 08:46 clang-4.0.1-Pthread_Serial-hwloc-release
-rw-r--r-- 1 kyukim users   28 Jun  3 08:38 clang-4.0.1-Pthread_Serial-release
-rw-r--r-- 1 kyukim users   29 Jun  3 09:39 cuda-9.2-Cuda_OpenMP-release
-rw-r--r-- 1 kyukim users   27 Jun  3 07:38 gcc-5.3.0-OpenMP-hwloc-release
-rw-r--r-- 1 kyukim users   27 Jun  3 07:33 gcc-5.3.0-OpenMP-release
-rw-r--r-- 1 kyukim users   27 Jun  3 07:47 gcc-7.3.0-Serial-hwloc-release
-rw-r--r-- 1 kyukim users   27 Jun  3 07:42 gcc-7.3.0-Serial-release
-rw-r--r-- 1 kyukim users   27 Jun  3 08:13 intel-16.0.3-Pthread-hwloc-release
-rw-r--r-- 1 kyukim users   27 Jun  3 08:07 intel-16.0.3-Pthread-release
-rw-r--r-- 1 kyukim users   27 Jun  3 08:00 intel-16.0.3-Serial-hwloc-release
-rw-r--r-- 1 kyukim users   27 Jun  3 07:54 intel-16.0.3-Serial-release
-rw-r--r-- 1 kyukim users   27 Jun  3 08:31 intel-17.0.1-OpenMP-hwloc-release
-rw-r--r-- 1 kyukim users   27 Jun  3 08:22 intel-17.0.1-OpenMP-release
```

**Comment by ndellingwood** [comment]
@kyungjoo-kim the trmm errors should be fixed by PR #728 I believe, if you run a `git log` does the SHA d9819c39cbdd163583397ee5a964e65ca5f0acdf show up?

**Comment by ndellingwood** [comment]
@kyungjoo-kim I updated previous reply, I had posted the wrong SHA, sorry for the mistake.

**Comment by kyungjoo-kim** [comment]
Yes. I did not merge develop branch. Now it passes all. I did not run the entire spot-check but ran tests for Cuda_Serial and Cuda_OpenMP for clang 7.

**Comment by ndellingwood** [comment]
> I did not run the entire spot-check but ran tests for Cuda_Serial and Cuda_OpenMP for clang 7.

@kyungjoo-kim that's sufficient, those testing errors were unrelated to your PR, thanks! Merging now.

**Pull request merged**
