### PR TITLE
fix to support View of CrsMatrices

### PR DESCRIPTION
**Pull request by rppawlo**
Required to support a view of crs matrices.

This may require that a corresponding PR in Kokkos be accepted first:

https://github.com/kokkos/kokkos/pull/1587

### CODE REVIEW

**Comment by rppawlo** [comment]
@mhoemmen @srajama1 - Can one of you review this? I don't have permissions to set the reviewer in the ticket.

**Comment by srajama1** [comment]
@rppawlo : Thanks for the fixes. I will wait to see if @mhoemmen has any comments, if not I will merge it.

**Comment by ndellingwood** [comment]
The corresponding Kokkos issue is merged.

**Comment by rppawlo** [comment]
@srajama1 - could you merge this PR?

**Comment by srajama1** [comment]
Done ! Sorry, didn't see the approval email soon enough.

**Comment by rppawlo** [comment]
Thanks @srajama1 !

**Pull request merged**
