### PR TITLE
gemv test: disable M == 0, mode='T' case with TPLs

### PR DESCRIPTION
**Pull request by ndellingwood**
Part of issue #539

### CODE REVIEW

**Comment by ndellingwood** [comment]
Also adding @iyamazaki

**Comment by mhoemmen** [comment]
See [my comment here](https://github.com/kokkos/kokkos-kernels/issues/539#issuecomment-565919015).  This looks like a kokkos-kernels bug that we could easily fix with an `if` test.

**Comment by mhoemmen** [comment]
@ndellingwood and I discussed this on the phone today.  Nathan agrees that it's better to fix the bug first.

**Comment by ndellingwood** [comment]
Closing in favor of #551

**Pull request closed without merging**
