### PR TITLE
Fix Trilinos issue #10612

### PR DESCRIPTION
**Pull request by brian-kelley**
Fix build error in ``ArithTraits<std::complex>::isNan`` and ``isInf``, when building with HIP.

### CODE REVIEW

**Review by e10harvey — APPROVED** [review]

**Comment by brian-kelley** [comment]
@e10harvey Thanks for looking at this. Should I just merge it so the release candidate can retest?

**Comment by ndellingwood** [comment]
@e10harvey no, the Trilinos 3.6.01 PR passed and was merged this morning and the release-candidate-3.6.01 branch is finalized, just waiting on merge and tagging
The changes here will be part of 3.7.00, though it looks like there is a Trilinos hotfix ready trilinos/Trilinos#10651

**Review by ndellingwood — COMMENTED** [review]
@brian-kelley I think for kokkos-kernels develop branch this will require removal of the Experimental namespace, the Kokkos math functions were promoted out of the Experimental namespace for upcoming 3.7.00 release https://github.com/kokkos/kokkos/pull/4791

**Comment by brian-kelley** [comment]
@ndellingwood We don't actually need a corresponding fix in develop because Kokkos core fixed it for us - by moving the functions out of Experimental, ArithTraits is now calling those instead of the problematic ``__device__`` versions in the HIP headers.

**Comment by ndellingwood** [comment]
@brian-kelley I didn't realize the PR was against release-candidate-3.6.01, thanks for the added info about the ArithTraits updates

**Comment by ndellingwood** [comment]
@lucbv would you like to get this fix merged with the release-candidate-3.6.01 (prior to merge to master)? We can leave the patch to Trilinos as the hotfix https://github.com/trilinos/Trilinos/pull/10651 ?

**Pull request merged**
