### PR TITLE
Update changelog for 4.4.00

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
First pass at the changelog for 4.4.00, ready for improved curation and other desired modifcations

**Comment by jgfouca** [comment]
Hey, @ndellingwood . I think I just got the last test failure for https://github.com/kokkos/kokkos-kernels/pull/2281 fixed. Is there any way we can get that PR into the release?

**Comment by ndellingwood** [comment]
@jgfouca possibly, can you test this PR in some Trilinos builds to make sure it won't introduce unexpected issues? I'm assuming this will get exercised through ifpack2 in addition to directly in kokkos-kernels

**Comment by jgfouca** [comment]
I would not expect this to impact Trilinos. This feature is not yet available through ifpack2.

**Comment by ndellingwood** [comment]
@jgfouca it still needs to be tested with Trilinos to make sure nothing unexpected occurs

**Comment by jgfouca** [comment]
@ndellingwood , OK, I did a quick ifpack2 build and test and it seems to work fine.

**Review by lucbv — APPROVED** [review]

**Comment by lucbv** [comment]
Made a small change to the log, I think it looks good.

**Pull request merged**
