### PR TITLE
ci: Disable PR tests which ran on `sogpu01` at Sandia

### PR DESCRIPTION
**Pull request by cwpearson**
This machine has been repurposed.

### CODE REVIEW

**Comment by JBludau** [comment]
why not delete the lines instead of commenting out?

**Review by jgfouca — APPROVED** [review]

**Comment by jgfouca** [comment]
I think commenting out makes sense since we will likely be re-enabling v100 testing on some other machine soon.

**Review by lucbv — CHANGES_REQUESTED** [review]
Actually looking at PR #2441 the Clang CI build seems to still be running correctly. We should keep it if possible.

**Comment by cwpearson** [comment]
It was an oversight that that test continued to work. It was running on sogpu01 and I have disabled it since that machine will be used for something else.

**Comment by lucbv** [comment]
Okay, if you can do a quick rebase for the update to kokkos 4.5.00 as version to test against then I can approve and we can merge this.

**Review by lucbv — APPROVED** [review]

**Pull request merged**
