### PR TITLE
Fix unit test headers installation

### LINKED ISSUE #2332: Unit test headers are installed
Hi,

I noticed that headers from some `unit_test` directories are installed. I suspect it is a mistake ?

The command `grep -R "APPEND KK_INCLUDE_DIRS .*unit_test"` from the top-level directory returns:
```cpp
common/CMakeLists.txt:LIST(APPEND KK_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/common/unit_test)
ode/CMakeLists.txt:LIST(APPEND KK_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/ode/unit_test)
batched/CMakeLists.txt:LIST(APPEND KK_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/batched/dense/unit_test)
batched/CMakeLists.txt:LIST(APPEND KK_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/batched/sparse/unit_test)
```

### PR DESCRIPTION
**Pull request by tpadioleau**
Closes #2332

### CODE REVIEW

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO INSPECTION HAS BEEN PERFORMED ON THIS PULL REQUEST! - This PR must be inspected by setting label 'AT: PRE-TEST INSPECTED'.

**Comment by lucbv** [comment]
@tpadioleau the changes in your PR look reasonable to me, do you want to keep this as draft or shall we convert this to PR?
I am happy to review when you feel it is ready

**Review by lucbv — APPROVED** [review]

**Comment by lucbv** [comment]
I will go ahead and test that locally then review and trigger CI, I should have been more on top of it...

**Review by lucbv — APPROVED** [review]

**Comment by tpadioleau** [comment]
> I will go ahead and test that locally then review and trigger CI, I should have been more on top of it...

No problem!

**Pull request merged**
