### PR TITLE
Add TPL support for CBLAS and LAPACKE

### PR DESCRIPTION
**Pull request by jjwilke**

### CODE REVIEW

**Comment by mhoemmen** [comment]
I've expressed my concerns about this in comments to PR https://github.com/kokkos/kokkos-kernels/pull/552.  Summary: We're adding new TPLs for the sake of three functions that already exist in the BLAS and LAPACK TPLs.  Downstream users will not enable these new TPLs unless they get automatically enabled.

**Comment by jjwilke** [comment]
I'm not able to reproduce this:

On kokkos-dev-2
````
./cm_test_all_sandia --kokkos-path=$HOME/Programs/kokkos/develop --spot-check cuda/10.1 --num=16
````
This builds and passes for me.

**Comment by jjwilke** [comment]
Okay, got it. `spot-check-tpls` not `spot-check`. I'm getting the error in both develop and this PR. The issue is that the CUSPARSE tests use lambdas, but `CUDA_LAMBDA` is not enabled for the TPL spot check.  If I change `cm_test_all_sandia` to enable cuda lamda for the TPL test, everything passes.

I will open a separate PR that fixes this issue (and adds assertions) then come back to this.

**Comment by jjwilke** [comment]
Spot check failures addressed in PR https://github.com/kokkos/kokkos-kernels/pull/640

**Comment by ndellingwood** [comment]
@jjwilke 

> `spot-check-tpls` not `spot-check`

Looked back at my message, sorry I didn't say that.

> I'm getting the error in both develop and this PR. The issue is that the CUSPARSE tests use lambdas

I didn't run into errors in develop when I was running the initial tpl spot-checks before submitting the PR to update the test script, which tests did these occur with? We should probably guard them like in kokkos. 
I like the changes in your PR, thanks!

**Comment by jjwilke** [comment]
The build fails in KokkosSparse_spmv_struct_tuning.cpp. I actually got a Jenkins nightly e-mail with that error: `Build failed in Jenkins: KokkosKernels_KokkosDev2_SPOTCHECK_TPLS #1`

**Comment by ndellingwood** [comment]
> I  actually got a Jenkins nightly e-mail with that error

Got it, hadn't gotten to checking the Jenkins emails yet.

**Comment by ndellingwood** [comment]
@jjwilke PR #641 merged with fix to guard the failing spmv_struct perf test based on whether lambda support is enabled. Rerunning spot-check-tpls on this PR now.

**Comment by ndellingwood** [comment]
tpl spot-check with merge of #641 and all looks good:

```
 nohup ../../scripts/cm_test_all_sandia --spot-check-tpls
...

Running on machine: kokkos-dev-2

Repository Status:  d2cc0b7c91bb1905622bb3835be9fb65fbadb1fa Merge branch 'develop' into pr-554


Going to test compilers:  gcc/7.3.0 gcc/8.3.0 gcc/9.1 intel/18.0.5 clang/8.0 cuda/10.1
Testing compiler gcc/7.3.0
  Starting job gcc-7.3.0-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-7.3.0-OpenMP-release
Testing compiler gcc/8.3.0
  Starting job gcc-7.3.0-Pthread-release
kokkos options: 
kokkos devices: Pthread
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-7.3.0-Pthread-release
Testing compiler gcc/9.1
  Starting job gcc-8.3.0-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-8.3.0-Serial-release
  Starting job gcc-9.1-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-9.1-OpenMP-release
Testing compiler intel/18.0.5
  Starting job gcc-9.1-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-9.1-Serial-release
Testing compiler clang/8.0
  Starting job intel-18.0.5-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED intel-18.0.5-OpenMP-release
  Starting job clang-8.0-Cuda_OpenMP-release
kokkos options: 
kokkos devices: Cuda,OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -Wno-pass-failed 
  PASSED clang-8.0-Cuda_OpenMP-release
Testing compiler cuda/10.1
  Starting job clang-8.0-Pthread_Serial-release
kokkos options: 
kokkos devices: Pthread,Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -Wno-pass-failed 
  PASSED clang-8.0-Pthread_Serial-release
  Starting job cuda-10.1-Cuda_OpenMP-release
kokkos options: 
kokkos devices: Cuda,OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED cuda-10.1-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=120 run_time=154
clang-8.0-Pthread_Serial-release build_time=52 run_time=154
cuda-10.1-Cuda_OpenMP-release build_time=160 run_time=135
gcc-7.3.0-OpenMP-release build_time=46 run_time=1477
gcc-7.3.0-Pthread-release build_time=44 run_time=96
gcc-8.3.0-Serial-release build_time=56 run_time=79
gcc-9.1-OpenMP-release build_time=54 run_time=63
gcc-9.1-Serial-release build_time=46 run_time=75
intel-18.0.5-OpenMP-release build_time=160 run_time=34
```

**Pull request merged**
