### PR TITLE
attempt to fix GCC 5.1 compilation

### PR DESCRIPTION
**Pull request by ibaned**

### CODE REVIEW

**Comment by ndellingwood** [comment]
First test with c++14 standard passed:
```

[ndellin@kokkos-dev-2 TestAllSandia]$ ../../scripts/test_all_sandia gcc/7.2.0 --spot-check --cxxstandard="c++14"
Running on machine: sems
Going to test compilers:  gcc/7.2.0
Testing compiler gcc/7.2.0
  Starting job gcc-7.2.0-Serial-release
  PASSED gcc-7.2.0-Serial-release
#######################################################
PASSED TESTS
#######################################################
gcc-7.2.0-Serial-release build_time=112 run_time=175
#######################################################
FAILED TESTS
#######################################################
```

Will launch a full spot-check (which doesn't enable c++14)

**Comment by ibaned** [comment]
@ndellingwood on second thought, the one app that cared about this has stopped using GCC 5.1, so maybe we don't move forward with this

**Comment by ndellingwood** [comment]
@ibaned it looks like reasonable cleanup assuming it passes spot-checks, but feel free to close if you'd rather we not move forward.

**Comment by ndellingwood** [comment]
White spot-check:
```
/ascldap/users/ndellin/kokkos-kernels/testing/TestAllSandia-White
bash-4.2$ ../../scripts/test_all_sandia --spot-check --arch="Power8,Pascal60"
Running on machine: white
Going to test compilers:  gcc/6.4.0 gcc/7.2.0 ibm/16.1.0 cuda/9.2.88 cuda/10.0.130
Testing compiler gcc/6.4.0
Testing compiler gcc/7.2.0
  Starting job gcc-7.2.0-OpenMP-release
  Starting job gcc-6.4.0-OpenMP_Serial-release
  PASSED gcc-7.2.0-OpenMP-release
  Starting job gcc-7.2.0-Serial-release
  PASSED gcc-6.4.0-OpenMP_Serial-release
Testing compiler ibm/16.1.0
  Starting job gcc-7.2.0-OpenMP_Serial-release
  PASSED gcc-7.2.0-Serial-release
Testing compiler cuda/9.2.88
  Starting job ibm-16.1.0-Serial-release
  PASSED gcc-7.2.0-OpenMP_Serial-release
  PASSED ibm-16.1.0-Serial-release
Testing compiler cuda/10.0.130
  Starting job cuda-9.2.88-Cuda_OpenMP-release
  PASSED cuda-9.2.88-Cuda_OpenMP-release
  Starting job cuda-10.0.130-Cuda_Serial-release
  PASSED cuda-10.0.130-Cuda_Serial-release
#######################################################
PASSED TESTS
#######################################################
cuda-10.0.130-Cuda_Serial-release build_time=914 run_time=349
cuda-9.2.88-Cuda_OpenMP-release build_time=951 run_time=249
gcc-6.4.0-OpenMP_Serial-release build_time=459 run_time=364
gcc-7.2.0-OpenMP-release build_time=295 run_time=130
gcc-7.2.0-OpenMP_Serial-release build_time=504 run_time=394
gcc-7.2.0-Serial-release build_time=200 run_time=206
ibm-16.1.0-Serial-release build_time=1040 run_time=313
#######################################################
FAILED TESTS
#######################################################
```

**Comment by srajama1** [comment]
@ibaned If you don't mind, let us put this fix in. There would be other users who could run into the same issue.

**Comment by srajama1** [comment]
@ibaned : Thank you !

**Comment by srajama1** [comment]
@ndellingwood : Ready to push ?

**Comment by lucbv** [comment]
Kokkos does not support GCC 5.1 anymore, the current min version is 5.3

**Pull request closed without merging**
