### PR TITLE
Release 4.0.0

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Please hold PR until successful pass and merge of https://github.com/trilinos/Trilinos/pull/11600

**Review by lucbv — APPROVED** [review]
Looks good to me, thanks for all the work on the release @ndellingwood

**Comment by ndellingwood** [comment]
Failing build from testing with kokkos master branch (which does not yet contain the merge for the compatible 4.0.0 release for this PR)

**Review by e10harvey — APPROVED** [review]
Thank you, @ndellingwood !

**Comment by e10harvey** [comment]
> Failing build from testing with kokkos master branch (which does not yet contain the merge for the compatible 4.0.0 release for this PR)

To ensure the CI checks pass, first merge the Kokkos core 4.0.0 release into main. Then, under https://github.com/kokkos/kokkos-kernels/actions/runs/4259379854/jobs/7411746207, in the top-right select the drop-down 'Re-run jobs' and 'Re-run all jobs'.

**Comment by ndellingwood** [comment]
https://github.com/trilinos/Trilinos/pull/11600 merged

**Comment by ndellingwood** [comment]
Thanks @lucbv !

**Pull request merged**
