### PR TITLE
Cleaning of eigensolver.

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
This is to provide a host version of eigen solver not to block the application work.

### CODE REVIEW

**Comment by kyungjoo-kim** [comment]
Output from spot check on kokkos-dev

```
[kyukim @kokkos-dev] test-all > ../../../kyukim/scripts/cm_test_all_sandia --spot-check
Running on machine: kokkos-dev
KokkosKernels Repository Status:  cec8d1f96e926833378c6a1c4b25cc06be577b5f Merge remote-tracking branch 'upstream/develop' into qr-develop

Kokkos Repository Status:  c10f94f486aef0a2d6c1d07ac1fecbd8d9995538 Merge pull request #2827 from jjwilke/cleanup-header-source-install

#######################################################
PASSED TESTS
#######################################################
clang-4.0.1-Pthread_Serial-release build_time=315 run_time=126
clang-7.0.1-Cuda_OpenMP-release build_time=1066 run_time=247
cuda-9.2-Cuda_OpenMP-release build_time=1091 run_time=271
gcc-5.3.0-OpenMP-release build_time=227 run_time=63
gcc-7.3.0-Serial-release build_time=195 run_time=66
intel-16.0.3-Pthread-release build_time=294 run_time=66
intel-16.0.3-Serial-release build_time=307 run_time=75
intel-17.0.1-OpenMP-release build_time=421 run_time=54
```

**Comment by kyungjoo-kim** [comment]
The last commit was not tested yet.

**Comment by kyungjoo-kim** [comment]
@ndellingwood I have a few questions regarding to spot-check cuda option inconsistency. In the following test, why do we give no cuda option for clang_cuda_openmp ? Does this really test for cuda ? Without the enable_lambda option (I think that lambda should be turned on), does this really compile all examples and tests ? In the folloing cuda-9.2 openmp test, the option is only uvm. I am wondering if this is right test setting. I got some build failures due to disabled lambda.

```
[kyukim @kokkos-dev] test-all > ../../../kyukim/scripts/cm_test_all_sandia --spot-check
  Starting job clang-7.0.1-Cuda_OpenMP-release
kokkos devices: Cuda,OpenMP
kokkos arch: Kepler35
kokkos options: 
kokkos cuda options: 
  Starting job cuda-9.2-Cuda_OpenMP-release
kokkos devices: Cuda,OpenMP
kokkos arch: Kepler35
kokkos options: 
kokkos cuda options: force_uvm
```

On kokkos-dev-2, the spot check enables lambda and it passes all tests.
```
[kyukim @kokkos-dev-2] test-all > ../../../kyukim/scripts/cm_test_all_sandia --spot-check-tpls
  Starting job cuda-10.1-Cuda_OpenMP-release
kokkos devices: Cuda,OpenMP
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: ,enable_lambda
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  PASSED cuda-10.1-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=649 run_time=161
clang-8.0-Pthread_Serial-release build_time=221 run_time=117
clang-9.0.0-Pthread-release build_time=134 run_time=59
clang-9.0.0-Serial-release build_time=131 run_time=63
cuda-10.1-Cuda_OpenMP-release build_time=868 run_time=163
gcc-4.8.4-OpenMP-release build_time=117 run_time=58
gcc-7.3.0-OpenMP-release build_time=145 run_time=62
gcc-7.3.0-Pthread-release build_time=129 run_time=59
gcc-8.3.0-Serial-release build_time=142 run_time=65
gcc-9.1-OpenMP-release build_time=179 run_time=63
gcc-9.1-Serial-release build_time=163 run_time=64
intel-17.0.1-Serial-release build_time=255 run_time=63
intel-18.0.5-OpenMP-release build_time=385 run_time=54
intel-19.0.5-Pthread-release build_time=455 run_time=53
```

On the other hand, spot check without tpls failed to build my test owing to the disabled lambda.
```
[kyukim @kokkos-dev-2] test-all > ../../../kyukim/scripts/cm_test_all_sandia --spot-check
  Starting job cuda-10.1-Cuda_OpenMP-release
kokkos devices: Cuda,OpenMP
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: 
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft

  FAILED cuda-10.1-Cuda_OpenMP-release
```
In my opinion, we should enable lambdas for all cuda testing. I tested the failed configuration with enabling lambda and it passes the test.

**Comment by ndellingwood** [comment]
@kyungjoo-kim it's possible the script needs a fix for the clang-cuda test you mentioned, I'll take a look. Some Cuda tests enable a different option (e.g. UVM with 9.2 but not 10.1) to give some breadth of option coverage and lambda should be enabled in one of the settings (I forget which), however Kokkos does not enable lambdas with Cuda by default so we should maintain a Cuda build that tests when lambdas are not enabled.

**Comment by kyungjoo-kim** [comment]
Okay. I will enable or disable the tests when the kokkos lambda option is not enabled.

**Comment by kyungjoo-kim** [comment]
This PR is good to be merged. 
```
[kyukim @kokkos-dev-2] test-all > ../../../kyukim/scripts/cm_test_all_sandia --spot-check-tpls
#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=649 run_time=214
clang-8.0-Pthread_Serial-release build_time=210 run_time=121
clang-9.0.0-Pthread-release build_time=129 run_time=59
clang-9.0.0-Serial-release build_time=128 run_time=63
cuda-10.1-Cuda_OpenMP-release build_time=868 run_time=196
gcc-4.8.4-OpenMP-release build_time=120 run_time=61
gcc-7.3.0-OpenMP-release build_time=148 run_time=1746
gcc-7.3.0-Pthread-release build_time=120 run_time=55
gcc-8.3.0-Serial-release build_time=146 run_time=61
gcc-9.1-OpenMP-release build_time=185 run_time=1213
gcc-9.1-Serial-release build_time=166 run_time=61
intel-17.0.1-Serial-release build_time=258 run_time=59
intel-18.0.5-OpenMP-release build_time=366 run_time=54
intel-19.0.5-Pthread-release build_time=462 run_time=53

[kyukim @kokkos-dev-2] test-all > ../../../kyukim/scripts/cm_test_all_sandia --spot-check
#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=651 run_time=212
clang-8.0-Pthread_Serial-release build_time=210 run_time=120
clang-9.0.0-Pthread-release build_time=128 run_time=56
clang-9.0.0-Serial-release build_time=128 run_time=62
cuda-10.1-Cuda_OpenMP-release build_time=850 run_time=189
cuda-9.2-Cuda_Serial-release build_time=782 run_time=182
gcc-4.8.4-OpenMP-release build_time=120 run_time=55
gcc-7.3.0-OpenMP-release build_time=146 run_time=1758
gcc-7.3.0-Pthread-release build_time=122 run_time=53
gcc-8.3.0-Serial-release build_time=145 run_time=59
gcc-9.1-OpenMP-release build_time=183 run_time=1227
gcc-9.1-Serial-release build_time=167 run_time=60
intel-17.0.1-Serial-release build_time=278 run_time=61
intel-18.0.5-OpenMP-release build_time=386 run_time=56
intel-19.0.5-Pthread-release build_time=461 run_time=54
```

**Pull request merged**
