### PR TITLE
Conversion to new ETI requiring minimal C++ code additions

### PR DESCRIPTION
**Pull request by jjwilke**

### CODE REVIEW

**Comment by jjwilke** [comment]
Work in progress. PR open if anyone wants to review the initial implementation and give feedback before renovating the entire repository.

**Comment by jjwilke** [comment]
@mhoemmen I think changing to AnonymousSpace is above my pay grade. My understanding is that `CudaSpace` is "zero-overhead" convertible to `AnonymousSpace`, so this probably makes sense to do? I'm not familiar enough with the code base to know how much algorithm specialization based on the memory space? I know we do specialization based on the execution space. @kyungjoo-kim @srajama1

**Comment by mhoemmen** [comment]
@jjwilke We've talked about this before; I just want people to keep it in mind that kokkos-kernels likely has redundant instantiations that consume build time and space.

**Comment by jjwilke** [comment]
Too many changes including file renames for this PR to remain useful. Canceled in favor of PR #526.  Cherry-picked commits into new PR.

**Pull request closed without merging**
