### PR TITLE
Fix #2344: SVD hanging

### LINKED ISSUE #2344: Hang in KokkosBatched::SerialSVD running in Cuda
This example call to SerialSVD hangs when run on the default execution space for a Cuda build, but runs fine in the default host execution space as well as in CPU builds that I have tried:

```cpp
template <typename ExecSpace>
void call_svd_in_parallel_for()
{
  Kokkos::TeamPolicy<ExecSpace> team_pol(1, Kokkos::AUTO);
  using ScratchMatrix = Kokkos::View<double[3][3], typename ExecSpace::scratch_memory_space>;
  using ScratchVector = Kokkos::View<double[3], typename ExecSpace::scratch_memory_space>;
  team_pol.set_scratch_size(1, Kokkos::PerThread(3*ScratchMatrix::shmem_size() + 3* ScratchVector::shmem_size()));
  Kokkos::parallel_for(team_pol, KOKKOS_LAMBDA(const typename Kokkos::TeamPolicy<ExecSpace>::member_type &team)
  {
    ScratchMatrix A(team.thread_scratch(1));
    ScratchMatrix U(team.thread_scratch(1));
    ScratchMatrix V(team.thread_scratch(1));
    ScratchVector S(team.thread_scratch(1));
    ScratchVector work(team.thread_scratch(1));
    Kokkos::single(Kokkos::PerTeam(team), [&]() {
      A(0, 0) = 0.000000;
      A(1, 0) = 3.58442287931538747e-02;
      A(2, 0) = 0.000000;
      A(0, 1) = 0.000000;
      A(1, 1) = 3.81743062695684907e-02;
      A(2, 1) = 0.000000;
      A(0, 2) = 0.000000;
      A(1, 2) = 0.000000;
      A(2, 2) = -5.55555555555555733e-02;

      KokkosBatched::SerialSVD::invoke(KokkosBatched::SVD_USV_Tag{}, A, U, S, V, work);

      printf("S = {%.16f %.16f %.16f}\n", S(0), S(1), S(2));
      printf("A(0) = {%.16f %.16f %.16f}\n", A(0, 0), A(0, 1), A(0, 2));
      printf("A(1) = {%.16f %.16f %.16f}\n", A(1, 0), A(1, 1), A(1, 2));
      printf("A(2) = {%.16f %.16f %.16f}\n", A(2, 0), A(2, 1), A(2, 2));
      printf("U(0) = {%.16f %.16f %.16f}\n", U(0, 0), U(0, 1), U(0, 2));
      printf("U(1) = {%.16f %.16f %.16f}\n", U(1, 0), U(1, 1), U(1, 2));
      printf("U(2) = {%.16f %.16f %.16f}\n", U(2, 0), U(2, 1), U(2, 2));
      printf("V(0) = {%.16f %.16f %.16f}\n", V(0, 0), V(0, 1), V(0, 2));
      printf("V(1) = {%.16f %.16f %.16f}\n", V(1, 0), V(1, 1), V(1, 2));
      printf("V(2) = {%.16f %.16f %.16f}\n", V(2, 0), V(2, 1), V(2, 2));
    });
  });
}

int main(int argc, char **argv)
{
  Kokkos::initialize(argc, argv);
  
  {
    printf("Running on host\n");
    call_svd_in_parallel_for<Kokkos::DefaultHostExecutionSpace>();
    Kokkos::fence();
    printf("Done\n");

    printf("Running on device\n");
    call_svd_in_parallel_for<Kokkos::DefaultExecutionSpace>();
    Kokkos::fence();
    printf("Done\n");
  }
  
  Kokkos::finalize();
  return 0;
}
```

Cuda testing was on V100 using nvcc-11.2.1 with gcc-8.3.0 host compiler.  @brian-kelley

### PR DESCRIPTION
**Pull request by brian-kelley**
Fix #2344, where SVD would hang due to one of the edge cases not being handled correctly.
Add tests (including the reproducer from the issue) which together exercise the two main edge cases.

Also did some miscellaneous cleanup like replace fabs (C math function) with ``Kokkos::abs``.

### CODE REVIEW

**Review by cwpearson — APPROVED** [review]
No comment on the SVD algorithm fixes, but otherwise LGTM

**Comment by lucbv** [comment]
@brian-kelley, I am looking at it this morning

**Comment by brian-kelley** [comment]
@lucbv You could hold off on reviewing for now - Victor reported that after these changes some other test cases are now hanging, but I don't have those matrices yet. I added some other rank-deficient test cases in my local branch but didn't get any that hang.

**Comment by lucbv** [comment]
Okay just ping me again when you want a look at it : )

**Comment by brian-kelley** [comment]
@lucbv This is ready for review now

**Review by lucbv — COMMENTED** [review]
This looks good overall, adding the new test cases is a good idea. We might want to consolidate some matrix generation features at some point. It seems we often redo these features in tests...

**Review by lucbv — APPROVED** [review]

**Pull request merged**
