### PR TITLE
Merge pull request #1695 from kokkos/update-changelog-to-4.0.0

### PR DESCRIPTION
**Pull request by ndellingwood**
Update changelog to 4.0.0

(cherry picked from commit 3bd6a3de36978f61aad80a25ef67b6d4a7544b91)

### CODE REVIEW

**Review by lucbv — APPROVED** [review]
Looks good to me, thanks @ndellingwood

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job KokkosKernels_PullRequest_CLANG13CUDA10 to start: Total Wait = 3603
- Other jobs have been previously started - We must stop them...
- Terminating Build 367 of Jenkins job KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930 on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build 372 of Jenkins job KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build 14 of Jenkins job KokkosKernels_PullRequest_GCC1020 on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build 285 of Jenkins job KokkosKernels_PullRequest_GCC1020_Light_LayoutRight on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build 248 of Jenkins job KokkosKernels_PullRequest_Tpls_GCC1020 on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build 335 of Jenkins job KokkosKernels_PullRequest_Tpls_INTEL19 on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build 387 of Jenkins job KokkosKernels_PullRequest_CLANG1001 on Jenkins server at https://jenkins-son.sandia.gov

**Comment by lucbv** [comment]
@ndellingwood I don't see a reason to wait for the auto-tester to get this checked before merging so let me know if you want me to merge this?

**Comment by ndellingwood** [comment]
@lucbv agreed, I'm able to merge, thanks!

**Pull request merged**
