### PR TITLE
cuSPARSE 11: fix spgemm and spmv_struct_tunning, see issue #803

### PR DESCRIPTION
**Pull request by lucbv**
Fix for spmv_struct_tunning perf_test that uses cusparse SpMV.
Temporary fix for spGEMM, this will require rewritting the interface for it to work properly but for the moment everything builds correctly.

### CODE REVIEW

**Comment by lucbv** [comment]
@srajama1 @brian-kelley 
These are the current changes for cusparse 11, nothing major, mainly disabling the cusparse backend for SpGEMM if users are building with CUDA 11 while we come up with new interface to fix things more permanently.
I tested the build and tests on Summit, everything was fine, I am now running spot-checks

**Comment by lucbv** [comment]
## kokkos-dev2 spot-check-tpls

#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=663 run_time=99
clang-8.0-Pthread_Serial-release build_time=205 run_time=118
clang-9.0.0-Pthread-release build_time=120 run_time=55
clang-9.0.0-Serial-release build_time=135 run_time=46
cuda-10.1-Cuda_OpenMP-release build_time=896 run_time=100
gcc-7.3.0-OpenMP-release build_time=148 run_time=45
gcc-7.3.0-Pthread-release build_time=122 run_time=56
gcc-8.3.0-Serial-release build_time=144 run_time=48
gcc-9.1-OpenMP-release build_time=179 run_time=45
gcc-9.1-Serial-release build_time=161 run_time=53
intel-18.0.5-OpenMP-release build_time=363 run_time=45
intel-19.0.5-Pthread-release build_time=416 run_time=56
#######################################################
FAILED TESTS
#######################################################
intel-17.0.1-Serial-release (build failed)
#######################################################

The intel-17.0.1 failure is actually due to a build failure in Kokkos, see error below, since everything else is passing I would be inclined to say that my changes are probably fine?
Waiting for regular spot-check to finish.
```
/ascldap/users/lberge/kokkos/core/src/impl/Kokkos_EBO.hpp(128): error: invalid type for defaulted assignment operator
    EBOBaseImpl& operator=(EBOBaseImpl const&) = default;
/ascldap/users/lberge/kokkos/core/src/impl/Kokkos_EBO.hpp(132): error: invalid type for defaulted assignment operator
    EBOBaseImpl& operator=(EBOBaseImpl&&) = default;
/ascldap/users/lberge/kokkos/core/src/impl/Kokkos_EBO.hpp(142): error: cannot overload functions distinguished by return type alone
    constexpr T const& _ebo_data_member() const& {
```

**Comment by lucbv** [comment]
## kokkos-dev2 spot-check

#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=642 run_time=98
clang-8.0-Pthread_Serial-release build_time=203 run_time=115
clang-9.0.0-Pthread-release build_time=125 run_time=54
clang-9.0.0-Serial-release build_time=125 run_time=49
cuda-10.1-Cuda_OpenMP-release build_time=899 run_time=202
cuda-9.2-Cuda_Serial-release build_time=860 run_time=143
gcc-7.3.0-OpenMP-release build_time=144 run_time=44
gcc-7.3.0-Pthread-release build_time=116 run_time=65
gcc-8.3.0-Serial-release build_time=161 run_time=53
gcc-9.1-OpenMP-release build_time=239 run_time=190
gcc-9.1-Serial-release build_time=205 run_time=50
intel-18.0.5-OpenMP-release build_time=382 run_time=889
intel-19.0.5-Pthread-release build_time=407 run_time=56
#######################################################
FAILED TESTS
#######################################################
intel-17.0.1-Serial-release (build failed)
#######################################################

Same as above for intel-17.0.1

**Comment by ndellingwood** [comment]
@lucbv I checked the intel issue with kokkos-dev-2, updates were merged into develop to address the problem with SHA ccef0a1d9d13835c438dadb5cbbf6b45d86006d3 from PR #790. Since the changes in this PR only impact Cuda builds it isn't necessary to retest with intel

**Comment by lucbv** [comment]
@ndellingwood OK I will have to look at how I am generating my spot-check config, I might have copied some file instead of using symbolic links to the source... Thanks for letting me know about this!

@srajama1 @brian-kelley I think this is ready to be merged but it would be good for one of you to give this a quick look first

**Comment by ndellingwood** [comment]
@lucbv I wanted to check if there are any blockers on the PR, or if it is to be superceded by any other changes? I can approve if no other blockers, changes look fine based on what you mentioned this PR intends (changes allow for compilation of kokkos-kernels w/ Cuda/11 and CuSparse enabled, currently throwing runtime error for routines awaiting future updates to support CuSparse/11 API)

**Comment by lucbv** [comment]
In my opinion this is good to go, I am not planning on adding more to the PR as it fixes the issues observed for now while only removing the cusparse 11 SpGEMM capabilities while we work on interfacing the new version. Users can still use Kokkos-kernels for that operation so overall this should not be a blocker for anyone.

**Review by ndellingwood — APPROVED** [review]

**Pull request merged**
