### PR TITLE
Release candidate 3.6.01

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Review by lucbv — APPROVED** [review]
Thanks @ndellingwood

**Review by e10harvey — APPROVED** [review]
Thanks, @ndellingwood !

**Comment by brian-kelley** [comment]
@ndellingwood I see, that's fine. The user that ran into this will have his issue fixed by the Trilinos hotfix.

**Comment by brian-kelley** [comment]
Oops, I meant to close my patch instead of the release!

**Comment by lucbv** [comment]
@ndellingwood we are good merging this right?

**Comment by ndellingwood** [comment]
@lucbv we can merge as-is, or we can first merge #1447 followed by merge of this branch (#1447 was not part of the snapshot to Trilinos, but there is a hotfix patch to Trilinos https://github.com/trilinos/Trilinos/pull/10651)

**Comment by lucbv** [comment]
Let's merge #1447 first then, it will make it cleaner for the tag

**Comment by lucbv** [comment]
Looks good to go, thanks @ndellingwood for adding the last patch : )

**Comment by ndellingwood** [comment]
Thanks @lucbv ! Are you able to also tag the release?

**Comment by lucbv** [comment]
Yeah, I'll tag next

**Pull request merged**
