### PR TITLE
cm_test_all_sandia: add cuda/11 for kokkos-dev-2

### PR DESCRIPTION
**Pull request by ndellingwood**
more kokkos-dev and sems module updates

### CODE REVIEW

**Comment by ndellingwood** [comment]
cuda/11 with c++17 tests running now on kokkos-dev-2, will setup nightly job once this is merged in

**Comment by ndellingwood** [comment]
Oop, looks like tpl check will break until #804 is merged

**Comment by ndellingwood** [comment]
cuda/11 with c++17 (non-tpl) initial check passed

```
Running on machine: kokkos-dev-2
WARNING!! THE FOLLOWING CHANGES ARE UNCOMMITTED!! :
 M scripts/cm_test_all_sandia
?? kk-14.patch

KokkosKernels Repository Status:  d97d9d5ea792b7a5d7d64204b667776a84b8bc2a Merge pull request #821 from ndellingwood/update-testall

Kokkos Repository Status:  a8c1eea2b3509406ca134e0e8c327740ef9326a6 [skipci] test_all_sandia: add cuda/11 for kokkos-dev-2


Going to test compilers:  cuda/11.0
Testing compiler cuda/11.0
Unrecognized compiler cuda/11.0 when looking for Spack variants
Unrecognized compiler cuda/11.0 when looking for Spack variants
Unrecognized compiler cuda/11.0 when looking for Spack variants
  Starting job cuda-11.0-Cuda_OpenMP-release
kokkos devices: Cuda,OpenMP
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: 
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  PASSED cuda-11.0-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
cuda-11.0-Cuda_OpenMP-release build_time=990 run_time=122
```

**Comment by brian-kelley** [comment]
@ndellingwood Does Kokkos automatically turn on C++17 for Cuda 11? Is that supposed to be somewhere in cm_test_all_sandia? If not, LGTM

**Comment by ndellingwood** [comment]
> Does Kokkos automatically turn on C++17 for Cuda 11

@brian-kelley no it defaults to c++14, I did this manually in my runs (`--cxxstandard=17`) but it was unclear in my post above, sorry about that.

**Comment by ndellingwood** [comment]
Updated the results comment to include test commands

**Review by brian-kelley — APPROVED** [review]

**Pull request merged**
