### PR TITLE
Release 4.5.01

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Trilinos snapshot PR: https://github.com/trilinos/Trilinos/pull/13679

**Review by lucbv — APPROVED** [review]

**Comment by ndellingwood** [comment]
Trilinos PR https://github.com/trilinos/Trilinos/pull/13679 with snapshots passed, this is ready for final approvals, merge, tagging

**Review by lucbv — APPROVED** [review]

**Comment by JBludau** [comment]
A user asked if we could eventually include this https://github.com/kokkos/kokkos-kernels/pull/2435.

**Comment by lucbv** [comment]
@JBludau , we have snapshotted release 4.5.01 in Trilinos so this will wait for release 4.6.0.

**Review by lucbv — APPROVED** [review]

**Pull request merged**
