### PR TITLE
Merge pull request #1171 from lucbv/Fix_using_namespace

### PR DESCRIPTION
**Pull request by ndellingwood**
using namespace should be scoped to prevent name clashes, see issue #1170

(cherry picked from commit e9496bbfefad465ea9fba77314759f912898fdea)

### CODE REVIEW

**Comment by ndellingwood** [comment]
I had to resolve conflicts with the cherry-pick, hoping I didn't make a mistake but please review carefully

**Review by lucbv — APPROVED** [review]
@ndellingwood this looks good and as long as you remove the three `using namespace KokkosBatched` we are fine since missing another change will lead to build failure which is easy to detect : )

**Comment by ndellingwood** [comment]
> this looks good and as long as you remove the three `using namespace KokkosBatched`

Yuck, thanks for the catch! I don't understand why that change didn't carry over with the cherry-pick, will need to better understand that

**Comment by ndellingwood** [comment]
Oop, I misinterpreted as a change request my mistake. I looked over the files changed diff and confirm the three culprit using namespace lines have been removed

**Review by e10harvey — APPROVED** [review]
Thank you, @lucbv  and @ndellingwood !

**Comment by ndellingwood** [comment]
@lucbv @e10harvey I force pushed an update to fix an error during testing (some funky duplication during cherry-pick, maybe I made a mistake resolving conflicts). The change resolved the error picked up in a Cuda_Serial build but have a failing `cuda.trsm_complex_double` test. I think I'm going to close this and try again tomorrow

**Pull request closed without merging**
