### PR TITLE
cm_test_all_sandia: remove kokkos-env and related modules

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
kokkos-env and its related modules are being removed from systems, this cleans up the scripts accordingly.

**Comment by lucbv** [comment]
Thanks @ndellingwood for looking into this and cleaning this up diligently.
The update looks good to me!

**Comment by ndellingwood** [comment]
Thanks @lucbv !

I pushed one-line update to skip hwloc testing with kokkos-dev.

A dry-run of the script shows modules are behaving (I confirmed module failure issues without these changes beforehand). This does not compile code (no code changes here), just tests loading modules and the env.

kokkos-dev-2 spot-check
```bash
../../scripts/cm_test_all_sandia --spot-check --dry-run

#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=0 run_time=0
clang-8.0-Pthread_Serial-release build_time=0 run_time=0
clang-9.0.0-Pthread-release build_time=0 run_time=0
clang-9.0.0-Serial-release build_time=0 run_time=0
cuda-10.1-Cuda_OpenMP-release build_time=0 run_time=0
cuda-9.2-Cuda_Serial-release build_time=0 run_time=0
gcc-4.8.4-OpenMP-release build_time=0 run_time=0
gcc-7.3.0-OpenMP-release build_time=0 run_time=0
gcc-7.3.0-Pthread-release build_time=0 run_time=0
gcc-8.3.0-Serial-release build_time=0 run_time=0
gcc-9.1-OpenMP-release build_time=1 run_time=0
gcc-9.1-Serial-release build_time=0 run_time=0
intel-17.0.1-Serial-release build_time=0 run_time=0
intel-18.0.5-OpenMP-release build_time=0 run_time=0
intel-19.0.5-Pthread-release build_time=0 run_time=0
```

kokkos-dev-2 spot-check-tpls
```bash
../../scripts/cm_test_all_sandia --spot-check-tpls --dry-run

#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=0 run_time=0
clang-8.0-Pthread_Serial-release build_time=0 run_time=0
clang-9.0.0-Pthread-release build_time=0 run_time=0
clang-9.0.0-Serial-release build_time=0 run_time=0
cuda-10.1-Cuda_OpenMP-release build_time=0 run_time=0
gcc-4.8.4-OpenMP-release build_time=0 run_time=0
gcc-7.3.0-OpenMP-release build_time=0 run_time=0
gcc-7.3.0-Pthread-release build_time=0 run_time=0
gcc-8.3.0-Serial-release build_time=0 run_time=0
gcc-9.1-OpenMP-release build_time=0 run_time=0
gcc-9.1-Serial-release build_time=0 run_time=0
intel-17.0.1-Serial-release build_time=0 run_time=0
intel-18.0.5-OpenMP-release build_time=0 run_time=0
intel-19.0.5-Pthread-release build_time=0 run_time=0
```

kokkos-dev spot-check
```bash
../../scripts/cm_test_all_sandia --spot-check --dry-run

#######################################################
PASSED TESTS
#######################################################
clang-4.0.1-Pthread_Serial-release build_time=0 run_time=0
clang-7.0.1-Cuda_OpenMP-release build_time=0 run_time=0
cuda-9.2-Cuda_OpenMP-release build_time=0 run_time=0
gcc-5.3.0-OpenMP-release build_time=0 run_time=0
gcc-7.3.0-Serial-release build_time=0 run_time=0
intel-16.0.3-Pthread-release build_time=0 run_time=0
intel-16.0.3-Serial-release build_time=0 run_time=0
intel-17.0.1-OpenMP-release build_time=0 run_time=0
```

**Comment by ndellingwood** [comment]
Did a quick dry-run spot-check confirmation on apollo as well

```bash
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=0 run_time=0
clang-6.0-Cuda_Pthread-release build_time=0 run_time=0
clang-6.0-OpenMP-release build_time=0 run_time=0
cuda-9.1-Cuda_OpenMP-release build_time=0 run_time=0
gcc-4.8.4-OpenMP-release build_time=0 run_time=0
gcc-4.8.4-Pthread-release build_time=0 run_time=0
gcc-5.3.0-Serial-release build_time=0 run_time=0
intel-16.0.1-OpenMP-release build_time=0 run_time=0
```

**Comment by lucbv** [comment]
Thanks again for the changes : )

**Pull request merged**
