### PR TITLE
KokkosSparse Updates

### PR DESCRIPTION
**Pull request by mndevec**
- ETI modifications for Sparse classes for spmv and trsv functions.
- Unit tests for spmv and trsv
- ETI generation scripts for sparse classes that requires ordinal and
  size types.
  scripts/generate_specialization_function_sparse.bash
  scripts/generate_specialization_type_sparse.bash
  The use examples are in
  scripts/generate_specialization2.bash

- Restructure of some folders, and filenames. We will need to change
  some includes in Trilinos from Kokkos_Sparse* to KokkosSparse*
  Moved KokkosBlas files to blas folder.

### CODE REVIEW

**Comment by mhoemmen** [comment]
@mndevec If you want to change header file names, please add backwards compatibility headers with the original names that include the headers with the new names.  Thanks!

**Comment by mndevec** [comment]
Sure Mark, I will add the list of the changed headers, maybe here? 
By the way, #31 talks about the new standard for file names and namespaces. I am following those for now.

**Comment by srajama1** [comment]
Next release is the first major one. IMHO, we can break backwards compatibility in that as long as we change Trilinos packages that include the headers.

**Comment by crtrott** [comment]
I am seconding Siva here. The old naming stuff was just a mess. We need to get this on a clean slate. And we will fix everything inside of Trilinos for the Release, and outside of it we don't have many users, and the ones we have are prepared to adapt.

**Pull request merged**
