### PR TITLE
Add volta70 AT2 checks

### PR DESCRIPTION
**Pull request by e10harvey**

### CODE REVIEW

**Review by lucbv — APPROVED** [review]
This looks reasonable although one thing that would be good is to use the latest release of Kokkos Core, 4.4.00 at this time, as we do with the current auto-tester. I believe changing from `ref: ${{ github.base_ref}` to the 4.4.0 tag might be the way to handle that

**Comment by lucbv** [comment]
Also should we actually run the volta 70 jobs to check that they run and pass before merging?

**Comment by e10harvey** [comment]
> Also should we actually run the volta 70 jobs to check that they run and pass before merging?

Yea, the CLANG13CUDA check does fail a few tests with https://github.com/kokkos/kokkos-kernels/issues/2005.

**Comment by e10harvey** [comment]
@ndellingwood, @lucbv: I'd like to get this PR merged, do you know the ctest regex syntax that's needed to exclude the failing tests? e.g., see https://github.com/kokkos/kokkos-kernels/pull/2325/commits/8d9a0eb73d2f6b4cd2375cab2d6f91c3e8089303

**Comment by lucbv** [comment]
@e10harvey after merging the BDW PR this now needs a rebase, should be easy. Once you have it done I'll have a final look.

**Comment by lucbv** [comment]
PR #2356 now supersedes this

**Pull request closed without merging**
