### PR TITLE
KokkosBatched_Eigendecomposition: Skip MKL code path for intel < 18

### PR DESCRIPTION
**Pull request by ndellingwood**
Address issue #701

### CODE REVIEW

**Comment by ndellingwood** [comment]
@kyungjoo-kim this PR just disables the MKL code path for intel versions older than 18, please close if you'd rather fix this differently.

**Comment by ndellingwood** [comment]
intel/17 TPL spot-check:

```
Running on machine: kokkos-dev-2
WARNING!! THE FOLLOWING CHANGES ARE UNCOMMITTED!! :
 M src/batched/KokkosBatched_Eigendecomposition_Serial_Internal.hpp

KokkosKernels Repository Status:  ef62a71f6b7ae307872caf57a0d5eb9b2b103636 Merge pull request #700 from ndellingwood/update-testall

Kokkos Repository Status:  daf6ac2595549faf04f7fa938db7120c2cb874a4 Merge pull request #2971 from dalg24/rocm-3.3


Going to test compilers:  intel/17.0.1
Testing compiler intel/17.0.1
  Starting job intel-17.0.1-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED intel-17.0.1-Serial-release
#######################################################
PASSED TESTS
#######################################################
intel-17.0.1-Serial-release build_time=107 run_time=23
```

**Comment by srajama1** [comment]
@ndellingwood : Document this somewhere please, seems like something we will forget in few weeks.

**Comment by ndellingwood** [comment]
@srajama1 sure, I'll add documentation to this PR with the change. I realize now my comment above sounds like I disabled MKL for all intel/17 and older usage, which was not the case just for this particular eigen decomposition routine, sorry for the miscommunication.

**Comment by srajama1** [comment]
@ndellingwood Thanks ! I mean in a wiki somewhere, MKL support for this works only with 18. We need to start a page and maintain these caveats somewhere.

**Comment by crtrott** [comment]
uhm 
```
WARNING!! THE FOLLOWING CHANGES ARE UNCOMMITTED!! :
 M src/batched/KokkosBatched_Eigendecomposition_Serial_Internal.hpp
```
I hope you did commit this thing?

**Comment by ndellingwood** [comment]
> I hope you did commit this thing?

Of course, otherwise there would be nothing in this PR ;)

**Comment by ndellingwood** [comment]
@kyungjoo-kim I looked at the mkl headers with the intel/17.0.1 module on kokkos-dev-2, the compiler complained that `LAPACK_ROW_MAJOR` was undefined but it is present in the `mkl_lapacke.h` header. Are you able to look further into this, in which case I'll close this PR? Otherwise I'll run the full spot-check.

**Comment by ndellingwood** [comment]
kokkos-dev-2 spot-check
```bash
nohup ../../scripts/cm_test_all_sandia --spot-check &

Running on machine: kokkos-dev-2
KokkosKernels Repository Status:  39472068c3ca2e984ccbaaae2b8e2262d2b8cfc9 KokkosBatched_Eigendecomposition: Skip MKL code path for intel < 18

Kokkos Repository Status:  daf6ac2595549faf04f7fa938db7120c2cb874a4 Merge pull request #2971 from dalg24/rocm-3.3


Going to test compilers:  gcc/7.3.0 gcc/8.3.0 gcc/9.1 gcc/4.8.4 intel/17.0.1 intel/18.0.5 intel/19.0.5 clang/8.0 clang/9.0.0 cuda/10.1 cuda/9.2
Testing compiler gcc/7.3.0
  Starting job gcc-7.3.0-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-7.3.0-OpenMP-release
Testing compiler gcc/8.3.0
  Starting job gcc-7.3.0-Pthread-release
kokkos options: 
kokkos devices: Pthread
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-7.3.0-Pthread-release
Testing compiler gcc/9.1
  Starting job gcc-8.3.0-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-8.3.0-Serial-release
  Starting job gcc-9.1-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-9.1-OpenMP-release
Testing compiler gcc/4.8.4
  Starting job gcc-9.1-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-9.1-Serial-release
Testing compiler intel/17.0.1
  Starting job gcc-4.8.4-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler intel/18.0.5
  Starting job intel-17.0.1-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED intel-17.0.1-Serial-release
Testing compiler intel/19.0.5
  Starting job intel-18.0.5-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED intel-18.0.5-OpenMP-release
Testing compiler clang/8.0
  Starting job intel-19.0.5-Pthread-release
kokkos options: 
kokkos devices: Pthread
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED intel-19.0.5-Pthread-release
  Starting job clang-8.0-Cuda_OpenMP-release
kokkos options: 
kokkos devices: Cuda,OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -Wno-pass-failed 
  PASSED clang-8.0-Cuda_OpenMP-release
Testing compiler clang/9.0.0
  Starting job clang-8.0-Pthread_Serial-release
kokkos options: 
kokkos devices: Pthread,Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -Wno-pass-failed 
  PASSED clang-8.0-Pthread_Serial-release
  Starting job clang-9.0.0-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED clang-9.0.0-Serial-release
Testing compiler cuda/10.1
  Starting job clang-9.0.0-Pthread-release
kokkos options: 
kokkos devices: Pthread
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED clang-9.0.0-Pthread-release
Testing compiler cuda/9.2
  Starting job cuda-10.1-Cuda_OpenMP-release
kokkos options: 
kokkos devices: Cuda,OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED cuda-10.1-Cuda_OpenMP-release
  Starting job cuda-9.2-Cuda_Serial-release
kokkos options: 
kokkos devices: Cuda,Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED cuda-9.2-Cuda_Serial-release
#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=166 run_time=72
clang-8.0-Pthread_Serial-release build_time=72 run_time=50
clang-9.0.0-Pthread-release build_time=58 run_time=24
clang-9.0.0-Serial-release build_time=55 run_time=24
cuda-10.1-Cuda_OpenMP-release build_time=203 run_time=70
cuda-9.2-Cuda_Serial-release build_time=200 run_time=85
gcc-4.8.4-OpenMP-release build_time=49 run_time=23
gcc-7.3.0-OpenMP-release build_time=58 run_time=22
gcc-7.3.0-Pthread-release build_time=53 run_time=25
gcc-8.3.0-Serial-release build_time=56 run_time=24
gcc-9.1-OpenMP-release build_time=69 run_time=23
gcc-9.1-Serial-release build_time=61 run_time=24
intel-17.0.1-Serial-release build_time=116 run_time=24
intel-18.0.5-OpenMP-release build_time=175 run_time=20
intel-19.0.5-Pthread-release build_time=206 run_time=22
```

kokkos-dev-2 spot-check-tpls
```bash
nohup ../../scripts/cm_test_all_sandia --spot-check-tpls &

Running on machine: kokkos-dev-2
KokkosKernels Repository Status:  39472068c3ca2e984ccbaaae2b8e2262d2b8cfc9 KokkosBatched_Eigendecomposition: Skip MKL code path for intel < 18

Kokkos Repository Status:  daf6ac2595549faf04f7fa938db7120c2cb874a4 Merge pull request #2971 from dalg24/rocm-3.3


Going to test compilers:  gcc/7.3.0 gcc/8.3.0 gcc/9.1 gcc/4.8.4 intel/17.0.1 intel/18.0.5 intel/19.0.5 clang/8.0 clang/9.0.0 cuda/10.1
Testing compiler gcc/7.3.0
  Starting job gcc-7.3.0-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-7.3.0-OpenMP-release
Testing compiler gcc/8.3.0
  Starting job gcc-7.3.0-Pthread-release
kokkos options: 
kokkos devices: Pthread
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-7.3.0-Pthread-release
Testing compiler gcc/9.1
  Starting job gcc-8.3.0-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-8.3.0-Serial-release
  Starting job gcc-9.1-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-9.1-OpenMP-release
Testing compiler gcc/4.8.4
  Starting job gcc-9.1-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-9.1-Serial-release
Testing compiler intel/17.0.1
  Starting job gcc-4.8.4-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler intel/18.0.5
  Starting job intel-17.0.1-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED intel-17.0.1-Serial-release
Testing compiler intel/19.0.5
  Starting job intel-18.0.5-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED intel-18.0.5-OpenMP-release
Testing compiler clang/8.0
  Starting job intel-19.0.5-Pthread-release
kokkos options: 
kokkos devices: Pthread
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED intel-19.0.5-Pthread-release
  Starting job clang-8.0-Cuda_OpenMP-release
kokkos options: 
kokkos devices: Cuda,OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -Wno-pass-failed 
  PASSED clang-8.0-Cuda_OpenMP-release
Testing compiler clang/9.0.0
  Starting job clang-8.0-Pthread_Serial-release
kokkos options: 
kokkos devices: Pthread,Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -Wno-pass-failed 
  PASSED clang-8.0-Pthread_Serial-release
  Starting job clang-9.0.0-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED clang-9.0.0-Serial-release
Testing compiler cuda/10.1
  Starting job clang-9.0.0-Pthread-release
kokkos options: 
kokkos devices: Pthread
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED clang-9.0.0-Pthread-release
  Starting job cuda-10.1-Cuda_OpenMP-release
kokkos options: 
kokkos devices: Cuda,OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED cuda-10.1-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=161 run_time=90
clang-8.0-Pthread_Serial-release build_time=71 run_time=51
clang-9.0.0-Pthread-release build_time=58 run_time=25
clang-9.0.0-Serial-release build_time=53 run_time=24
cuda-10.1-Cuda_OpenMP-release build_time=211 run_time=89
gcc-4.8.4-OpenMP-release build_time=48 run_time=40
gcc-7.3.0-OpenMP-release build_time=57 run_time=38
gcc-7.3.0-Pthread-release build_time=53 run_time=26
gcc-8.3.0-Serial-release build_time=56 run_time=25
gcc-9.1-OpenMP-release build_time=69 run_time=38
gcc-9.1-Serial-release build_time=60 run_time=25
intel-17.0.1-Serial-release build_time=107 run_time=22
intel-18.0.5-OpenMP-release build_time=174 run_time=24
intel-19.0.5-Pthread-release build_time=202 run_time=21
```

**Comment by kyungjoo-kim** [comment]
@ndellingwood No, we do not need to look further. That code I use is for comparison and it is for testing. At that time, we do not test TPLs and now we do. When I overhaul the code, I will remove it or add the interface precisely. At this moment, if spot-check tests do not complain, I think we are fine.

**Comment by srajama1** [comment]
@kyungjoo-kim @ndellingwood The changes are not in test it is src. Can you clarify ?

**Pull request merged**
