### PR TITLE
Fixed clustering, RCM, BFS accessing neighbors >= nv

### PR DESCRIPTION
**Pull request by brian-kelley**
Tpetra graphs contain remote columns (entries) that can't be
used as row indices (so the "local" graph may be symmetric, but
entries >= #numRows must be filtered).

Added this filtering to RCM, BFS and balloon clustering.

Also added a test to Gauss-Seidel for zero-row case, where the input
row map can have length 0 or 1. Ran clean through valgrind in openmp.

Same changes Trilinos #6631, plus the zero-row test.

### CODE REVIEW

**Comment by brian-kelley** [comment]
Spot checks from RIDE (didn't do IBM):
#######################################################
PASSED TESTS
#######################################################
cuda-9.2.88-Cuda_OpenMP-release build_time=585 run_time=420
cuda-9.2.88-Cuda_Serial-release build_time=548 run_time=525
gcc-6.4.0-OpenMP_Serial-release build_time=211 run_time=395
gcc-7.2.0-OpenMP-release build_time=123 run_time=129
gcc-7.2.0-OpenMP_Serial-release build_time=201 run_time=363
gcc-7.2.0-Serial-release build_time=111 run_time=228

Bowman:
#######################################################
PASSED TESTS
#######################################################
intel-16.4.258-Pthread-release build_time=739 run_time=1034
intel-16.4.258-Pthread_Serial-release build_time=1077 run_time=1993
intel-16.4.258-Serial-release build_time=722 run_time=944
intel-17.2.174-OpenMP-release build_time=896 run_time=568
intel-17.2.174-OpenMP_Serial-release build_time=1265 run_time=1492
intel-17.2.174-Pthread-release build_time=816 run_time=901
intel-17.2.174-Pthread_Serial-release build_time=1138 run_time=1795
intel-17.2.174-Serial-release build_time=793 run_time=874

**Comment by ndellingwood** [comment]
@brian-kelley 

Saw this `-Werror` in the Trilinos gcc/7.2.0 build, does it need to be fixed in this PR as well?

```
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_7.2.0/Trilinos/packages/kokkos-kernelssparse/impl/KokkosSparse_cluster_gauss_seidel_impl.hpp:783:14: error: unused variable ‘onCuda’ [-Werror=unused-variable]
         bool onCuda = false;
              ^~~~~~
cc1plus: all warnings being treated as errors
```

**Comment by ndellingwood** [comment]
Cross reference trilinos/Trilinos#6631

**Comment by brian-kelley** [comment]
@ndellingwood No, this PR is OK. I just forgot to remove that variable from the Trilinos one.

**Pull request merged**
