### PR TITLE
Example for block jacobi and eigen solver

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
This provides an example code for block jacobi (small block size about O(10)). As this goes into perf test, it is probably safe to be merged. I tested on blake (intel) and tried to test on white but the test bed is full now. I will update the PR once I can greb a node from white.

### CODE REVIEW

**Comment by kyungjoo-kim** [comment]
@ndellingwood I checked this PR for blake and white but I somehow cannot run the cm_test_all_sandia script. When you have time, would you help me run the script ?

**Comment by ndellingwood** [comment]
Which queue are you using on White? If you're using rhel7G, make sure to change the arch code and bsub to the queue before launching the script. The script options should be the same as with test_all_sandia. I've used the script on white successfully, you may need to specify paths for kokkos and kokkos-kernels, and also make sure you are using kokkos' develop branch.

**Comment by kyungjoo-kim** [comment]
@ndellingwood would you approve this PR and include in the promotion branch ? 

```
[kyukim @kokkos-dev-2] test-all > ../../../kyukim/scripts/cm_test_all_sandia cuda/10.0 cuda/10.1 clang/8.0 gcc/9.1 intel/19.0.5 clang/7.0.1
Running on machine: kokkos-dev-2
Repository Status:  b325e84f3b94470a1e71fdbd38f20eb8f62813ee KokkosBatched - fix a bug on GPUs. checked on white.
...
...
#######################################################
PASSED TESTS
#######################################################
clang-7.0.1-Pthread-release build_time=41 run_time=78
clang-7.0.1-Pthread_Serial-release build_time=57 run_time=146
clang-7.0.1-Serial-release build_time=40 run_time=65
clang-8.0-Cuda_OpenMP-release build_time=125 run_time=158
clang-8.0-Cuda_Serial-release build_time=124 run_time=186
cuda-10.0-Cuda_Pthread-release build_time=157 run_time=168
cuda-10.0-Cuda_Serial-release build_time=162 run_time=179
cuda-10.1-Cuda_Pthread-release build_time=172 run_time=173
cuda-10.1-Cuda_Serial-release build_time=182 run_time=169
gcc-9.1-OpenMP-release build_time=53 run_time=46
gcc-9.1-Serial-release build_time=46 run_time=63
intel-19.0.5-OpenMP-release build_time=133 run_time=43
intel-19.0.5-OpenMP_Serial-release build_time=160 run_time=118
intel-19.0.5-Pthread-release build_time=158 run_time=55
intel-19.0.5-Pthread_Serial-release build_time=184 run_time=136
intel-19.0.5-Serial-release build_time=153 run_time=55
```

**Comment by ndellingwood** [comment]
@kyungjoo-kim can you squash commits to a single commit? That will make this much easier to cherry-pick to the release-candidate-3.0 branch if we get this in with the promotion.

**Comment by kyungjoo-kim** [comment]
@ndellingwood I would like to squash the commits but somehow I can only see noop from git rebase. Would you help me squash the commits when you are available ?

**Comment by ndellingwood** [comment]
@kyungjoo-kim can you rerun spot-checks on this? We can get this merged into develop once passing.

**Comment by kyungjoo-kim** [comment]
I am going to hold this a while.

**Comment by ndellingwood** [comment]
@kyungjoo-kim are you wanting this for 3.1, or is this still WIP?

**Comment by kyungjoo-kim** [comment]
I don' think that this is urgent.

**Comment by srajama1** [comment]
I am surprised we didn't push this. Is this because of squashing. If there is something wrong with the process that makes it harder for simple commits like this, we should fix the process.

**Comment by ndellingwood** [comment]
Squashing commits isn't necessary, I requested before since this was right near the end of integration testing and wanted to be able to back out the changes easily in case issues occurred. If that was a barrier please disregard.

**Pull request closed without merging**
