### PR TITLE
Remove pre-3.0 deprecated code

### PR DESCRIPTION
**Pull request by ndellingwood**
Addresses cleanup for issue #793

### CODE REVIEW

**Review by e10harvey — COMMENTED** [review]
LGTM. Thanks, Nathan! Do the below scripts need to be updated?
```
scripts/trilinos-integration/ATDM_configurations/configure-atdm-cuda-depoff-dbg.sh:  -DKOKKOS_ENABLE_DEPRECATED_CODE=OFF \
scripts/trilinos-integration/ATDM_configurations/configure-atdm-cuda-depoff.sh:  -DKOKKOS_ENABLE_DEPRECATED_CODE=OFF \
scripts/trilinos-integration/ATDM_configurations/configure-atdm-cuda-depon-dbg.sh:  -DKOKKOS_ENABLE_DEPRECATED_CODE=ON \
scripts/trilinos-integration/ATDM_configurations/configure-atdm-cuda-depon.sh:  -DKOKKOS_ENABLE_DEPRECATED_CODE=ON \
scripts/trilinos-integration/ATDM_configurations/configure-atdm-cuda-ride-rdc-depoff.sh:  -DKOKKOS_ENABLE_DEPRECATED_CODE=OFF \
scripts/trilinos-integration/ATDM_configurations/configure-atdm-cuda-ride-rdc-depon.sh:  -DKOKKOS_ENABLE_DEPRECATED_CODE=ON \
scripts/trilinos-integration/ATDM_configurations/configure-atdm-env.sh:  -DKOKKOS_ENABLE_DEPRECATED_CODE=ON \
```

**Review by brian-kelley — APPROVED** [review]
LGTM. I just removed a few more lines for the D2 coloring unit test, since DO_DEPRECATED_TEST is now empty.

**Comment by ndellingwood** [comment]
@e10harvey good catch (only checked source code), updated the scripts and removed the depoff versions

**Review by e10harvey — APPROVED** [review]

**Review by vqd8a — APPROVED** [review]
Thanks, @ndellingwood . It looks good to me.

**Comment by ndellingwood** [comment]
kokkos-dev-2 spot-check passed except intel/17, unrelated to this PR and still some issue with the old gcc that doesn't show up in dry-runs

Not sure why, script didn't print summary at the end when I ran with nohup, will have to figure that out separately.

```
KokkosKernels Repository Status:  3350f004d074d884ea72869012485b1149ca64ad Update integration scripts to remove deprecated code setting

Kokkos Repository Status:  651c021842348e956546fe9b0c5dff80a1678be0 Merge pull request #3402 from jjwilke/hpcbind-issue-3304


Going to test compilers:  gcc/7.3.0 gcc/8.3.0 gcc/9.1 intel/17.0.1 intel/18.0.5 intel/19.0.5 clang/8.0 clang/9.0.0 cuda/10.1 cuda/9.2 cuda/11.0
Testing compiler gcc/7.3.0
  Starting job gcc-7.3.0-OpenMP-release
kokkos devices: OpenMP
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: 
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  PASSED gcc-7.3.0-OpenMP-release
Testing compiler gcc/8.3.0
  Starting job gcc-7.3.0-Pthread-release
kokkos devices: Pthread
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: 
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  PASSED gcc-7.3.0-Pthread-release
Testing compiler gcc/9.1
  Starting job gcc-8.3.0-Serial-release
kokkos devices: Serial
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: 
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  PASSED gcc-8.3.0-Serial-release
  Starting job gcc-9.1-OpenMP-release
kokkos devices: OpenMP
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: 
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  PASSED gcc-9.1-OpenMP-release
Testing compiler intel/17.0.1
  Starting job gcc-9.1-Serial-release
kokkos devices: Serial
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: 
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  PASSED gcc-9.1-Serial-release
Testing compiler intel/18.0.5
  Starting job intel-17.0.1-Serial-release
kokkos devices: Serial
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: 
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  FAILED intel-17.0.1-Serial-release
RUNNING: make -j 12 all
make: *** No rule to make target `all'.  Stop.
Testing compiler intel/19.0.5
  Starting job intel-18.0.5-OpenMP-release
kokkos devices: OpenMP
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: 
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  PASSED intel-18.0.5-OpenMP-release
Testing compiler clang/8.0
  Starting job intel-19.0.5-Pthread-release
kokkos devices: Pthread
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: 
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  PASSED intel-19.0.5-Pthread-release
  Starting job clang-8.0-Cuda_OpenMP-release
kokkos devices: Cuda,OpenMP
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: 
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -Wno-pass-failed 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  PASSED clang-8.0-Cuda_OpenMP-release
Testing compiler clang/9.0.0
  Starting job clang-8.0-Pthread_Serial-release
kokkos devices: Pthread,Serial
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: 
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -Wno-pass-failed 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  PASSED clang-8.0-Pthread_Serial-release
  Starting job clang-9.0.0-Serial-release
kokkos devices: Serial
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: 
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  PASSED clang-9.0.0-Serial-release
Testing compiler cuda/10.1
  Starting job clang-9.0.0-Pthread-release
kokkos devices: Pthread
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: 
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  PASSED clang-9.0.0-Pthread-release
Testing compiler cuda/9.2
  Starting job cuda-10.1-Cuda_OpenMP-release
kokkos devices: Cuda,OpenMP
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: 
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  PASSED cuda-10.1-Cuda_OpenMP-release
Testing compiler cuda/11.0
  Starting job cuda-9.2-Cuda_Serial-release
kokkos devices: Cuda,Serial
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: force_uvm
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  PASSED cuda-9.2-Cuda_Serial-release
/ascldap/users/ndellin/kokkos-kernels/scripts/cm_test_all_sandia: line 1408: syntax error near unexpected token `do'




Finished
Unrecognized compiler cuda/11.0 when looking for Spack variants
Unrecognized compiler cuda/11.0 when looking for Spack variants
Unrecognized compiler cuda/11.0 when looking for Spack variants
  Starting job cuda-11.0-Cuda_OpenMP-release
kokkos devices: Cuda,OpenMP
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: 
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  PASSED cuda-11.0-Cuda_OpenMP-release
```

**Comment by ndellingwood** [comment]
Here's added intel/17 check with a fix to cm_test_all_sandia to properly handle the old gcc module (will issue separate PR). Previous failure of script was due to old gcc not being swapped out; the previous lack of summary was due to me messing with the script while the jobs were running

```bash
Running on machine: kokkos-dev-2
WARNING!! THE FOLLOWING CHANGES ARE UNCOMMITTED!! :
 M scripts/cm_test_all_sandia
 M scripts/update_lib.sh
?? kk-14.patch
?? unit_test/sparse/Test_Sparse_sptrsv.hpp-mod

KokkosKernels Repository Status:  3350f004d074d884ea72869012485b1149ca64ad Update integration scripts to remove deprecated code setting

Kokkos Repository Status:  651c021842348e956546fe9b0c5dff80a1678be0 Merge pull request #3402 from jjwilke/hpcbind-issue-3304


CM_ALL_SCRIPT: /ascldap/users/ndellin/kokkos-kernels/scripts/cm_test_all_sandia
dirname(CM_ALL_SCRIPT): /ascldap/users/ndellin/kokkos-kernels/scripts
CM_ALL_SCRIPT_PATH 1: /ascldap/users/ndellin/kokkos-kernels/testing/PRTest
CM_ALL_SCRIPT_PATH 2: /ascldap/users/ndellin/kokkos-kernels/testing/PRTest//ascldap/users/ndellin/kokkos-kernels/scripts
CM_ALL_SCRIPT_PATH 3: /ascldap/users/ndellin/kokkos-kernels/scripts
Going to test compilers:  intel/17.0.1
Testing compiler intel/17.0.1
  Starting job intel-17.0.1-Serial-release
kokkos devices: Serial
kokkos arch: SNB,Volta70
kokkos options: 
kokkos cuda options: 
kokkos cxxflags: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
extra_args: 
kokkoskernels scalars: 'double,complex_double'
kokkoskernels ordinals: int
kokkoskernels offsets: int,size_t
kokkoskernels layouts: LayoutLeft
  PASSED intel-17.0.1-Serial-release
#######################################################
PASSED TESTS
#######################################################
intel-17.0.1-Serial-release build_time=297 run_time=49
```

**Review by lucbv — APPROVED** [review]
Thanks for cleaning this up

**Review by seheracer — APPROVED** [review]
LGTM. Thanks Nathan!

**Comment by ndellingwood** [comment]
kokkos-dev-2 tpl spot-check passes (I cherry-picked the cm_test_all_sandia commit to fix the intel/17 module issue)

```bash
[ndellin@kokkos-dev-2 PRTest]$ ../../scripts/cm_test_all_sandia --spot-check-tpls
Running on machine: kokkos-dev-2
WARNING!! THE FOLLOWING CHANGES ARE UNCOMMITTED!! :
 M scripts/cm_test_all_sandia

KokkosKernels Repository Status:  ceb12ca6c185f708abc49ddd8fe7ccb7c912a865 cm_test_all_sandia: fix determination of CM_ALL_SCRIPT_PATH var

Kokkos Repository Status:  a47fd425ffa4d566a0e33d897b4e804c554a1b45 [[skipci]] testing script updates


Going to test compilers:  gcc/7.3.0 gcc/8.3.0 gcc/9.1 intel/17.0.1 intel/18.0.5 intel/19.0.5 clang/8.0 clang/9.0.0 cuda/10.1
...

#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=664 run_time=126
clang-8.0-Pthread_Serial-release build_time=212 run_time=118
clang-9.0.0-Pthread-release build_time=129 run_time=56
clang-9.0.0-Serial-release build_time=133 run_time=46
cuda-10.1-Cuda_OpenMP-release build_time=938 run_time=126
gcc-7.3.0-OpenMP-release build_time=151 run_time=45
gcc-7.3.0-Pthread-release build_time=127 run_time=57
gcc-8.3.0-Serial-release build_time=147 run_time=53
gcc-9.1-OpenMP-release build_time=184 run_time=46
gcc-9.1-Serial-release build_time=166 run_time=47
intel-17.0.1-Serial-release build_time=284 run_time=49
intel-18.0.5-OpenMP-release build_time=384 run_time=44
intel-19.0.5-Pthread-release build_time=413 run_time=55
```

**Pull request merged**
