### PR TITLE
Cleanup installation/build of parent project builds

### PR DESCRIPTION
**Pull request by jjwilke**

### CODE REVIEW

**Comment by jjwilke** [comment]
Related to https://github.com/kokkos/kokkos-kernels/issues/621

**Comment by jjwilke** [comment]
This needs to be cleaned up in Kokkos as well.

**Comment by kuberry** [comment]
Looks good. I just built and installed using this and was able to link against the product. I closed PR #621 as a result.

Thanks @jjwilke

**Comment by ndellingwood** [comment]
Due diligence spot-check results:

```
Running on machine: kokkos-dev-2
Repository Status:  d6a225df6fe186dcadfceabf1241bfe254ee7b1c cleanup installation/build of parent project builds


Going to test compilers:  gcc/7.3.0 gcc/8.3.0 gcc/9.1 intel/18.0.5 clang/8.0 cuda/10.1
Testing compiler gcc/7.3.0
  Starting job gcc-7.3.0-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-7.3.0-OpenMP-release
Testing compiler gcc/8.3.0
  Starting job gcc-7.3.0-Pthread-release
kokkos options: 
kokkos devices: Pthread
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-7.3.0-Pthread-release
Testing compiler gcc/9.1
  Starting job gcc-8.3.0-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-8.3.0-Serial-release
  Starting job gcc-9.1-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-9.1-OpenMP-release
Testing compiler intel/18.0.5
  Starting job gcc-9.1-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-9.1-Serial-release
Testing compiler clang/8.0
  Starting job intel-18.0.5-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED intel-18.0.5-OpenMP-release
  Starting job clang-8.0-Cuda_OpenMP-release
kokkos options: 
kokkos devices: Cuda,OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -Wno-pass-failed 
  PASSED clang-8.0-Cuda_OpenMP-release
Testing compiler cuda/10.1
  Starting job clang-8.0-Pthread_Serial-release
kokkos options: 
kokkos devices: Pthread,Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -Wno-pass-failed 
  PASSED clang-8.0-Pthread_Serial-release
  Starting job cuda-10.1-Cuda_OpenMP-release
kokkos options: 
kokkos devices: Cuda,OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED cuda-10.1-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=119 run_time=152
clang-8.0-Pthread_Serial-release build_time=50 run_time=150
cuda-10.1-Cuda_OpenMP-release build_time=156 run_time=141
gcc-7.3.0-OpenMP-release build_time=44 run_time=46
gcc-7.3.0-Pthread-release build_time=42 run_time=75
gcc-8.3.0-Serial-release build_time=41 run_time=70
gcc-9.1-OpenMP-release build_time=53 run_time=45
gcc-9.1-Serial-release build_time=46 run_time=72
intel-18.0.5-OpenMP-release build_time=150 run_time=45
```

**Comment by ndellingwood** [comment]
@jjwilke looks like a merge conflict due to my merge of PR #627 that added a missing alias, I'm assuming this PR is preferred?

**Comment by jjwilke** [comment]
Oops. I opened this on a kokkos-kernels branch instead of my fork. I promise to never do that again.

**Comment by jjwilke** [comment]
@ndellingwood I rebased and removed the conflict. This should be good.

**Pull request merged**
