### PR TITLE
Issue 188

### PR DESCRIPTION
**Pull request by mndevec**
This should fix the Graph coloring and spgemm hangs on VOLTA GPUs #188 .

### CODE REVIEW

**Comment by srajama1** [comment]
@ndellingwood I don't think these changes will affect anything on Volta, do you think so ?

**Comment by mndevec** [comment]
@ndellingwood 
The added code is protected with FLAGs related to volta GPUs. 
Still, I run the performance test here(https://github.com/kokkos/kokkos-kernels/wiki/p100_configure) before pushing. I get the same timings. 

For Volta, I did not have any reference. The test that runs 0.82 seconds on P100 runs in 0.50 on Apollo's Volta.

**Comment by ndellingwood** [comment]
Running spot-check on the PR now

**Comment by ndellingwood** [comment]
Rerunning the spot-check, ran into an error due to comparison of signed and unsigned:

```
/home/ndellin/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp:630:18: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
         else if (++new_hash == vector_size){
```

I changed the `else if` as below to fix the error
`         else if (++new_hash == decltype(new_hash)(vector_size)){`

Will post results once it finishes.

**Comment by mndevec** [comment]
Thanks @ndellingwood can you make a PR to my branch?

**Comment by ndellingwood** [comment]
I had to fix a typo in test_all_sandia as well (will put in 1-line PR), spot-check on kokkos-dev passes:
```

#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-hwloc-release build_time=778 run_time=1176
clang-3.9.0-Pthread_Serial-release build_time=779 run_time=2514
cuda-8.0.44-Cuda_OpenMP-release build_time=1049 run_time=1065
gcc-5.3.0-Serial-hwloc-release build_time=598 run_time=996
gcc-5.3.0-Serial-release build_time=590 run_time=989
intel-16.0.1-OpenMP-hwloc-release build_time=398 run_time=371
intel-16.0.1-OpenMP-release build_time=730 run_time=351
#######################################################
```

**Comment by ndellingwood** [comment]
@mndevec I just pushed the change to your branch issue-188 replacing line 630 of `kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp` with `else if (++new_hash == decltype(new_hash)(vector_size)){`

**Comment by mndevec** [comment]
@ndellingwood , @crtrott , @srajama1 
I don't have merge access, can you merge this branch?

**Pull request merged**
