### PR TITLE
Test_Sparse_spmv: resolve -Werror due to unused variable

### PR DESCRIPTION
**Pull request by ndellingwood**
This addresses a -Werror occurring with clang builds

### CODE REVIEW

**Comment by ndellingwood** [comment]
This cleans up another unused variable -Werror issue with clang, part of #1178 

Note the clang builds will not complete -Werror free until #1172 is resolved

**Comment by lucbv** [comment]
@ndellingwood I opened a similar pull request just now.
I actually modified the loops to use static allocation instead of the dynamic one done here and I also fixed another issue in the nightly tests related to comparison of integer of different types, see PR #1185

**Comment by ndellingwood** [comment]
@lucbv I'll close this PR then, thanks!

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job KokkosKernels_PullRequest_GCC720 to start: Total Wait = 3603
- Other jobs have been previously started - We must stop them...
- Terminating Build #203 of Jenkins job KokkosKernels_PullRequest_GCC720_Light on Jenkins server at https://jenkins-son.sandia.gov

**Pull request closed without merging**
