### PR TITLE
spadd bugfix, cleanup for performance

### PR DESCRIPTION
**Pull request by brian-kelley**
-Making sure last entry of rowcount view is correct, if Crowmap on input
  wasn't initialized (a bug affecting Tpetra!)
-Remove unnecessary view initializations (was taking up to 50% of the
  spadd time!)
-Remove unnecessary fences
  -Still have fences at the end of user-facing functions,
    so that timers on host accurately reflect kernel times
-Use idiomatic deep_copy to scalar for accessing views, rather than
  making a host mirror of a single-element subview
-Negligible impact, but avoid View reference count increments (pass-by-ref to functor ctor)

### CODE REVIEW

**Comment by brian-kelley** [comment]
@ndellingwood I went through carefully with vimdiff and made sure the Trilinos PR and this are identical, apart from the fact that the new batched add feature isn't in Trilinos yet. I'm running spot checks now, and won't merge the Trilinos one until this one is done.

**Comment by brian-kelley** [comment]
Ride spot check is done:
#######################################################
PASSED TESTS
#######################################################
cuda-9.2.88-Cuda_OpenMP-release build_time=545 run_time=414
cuda-9.2.88-Cuda_Serial-release build_time=561 run_time=523
gcc-6.4.0-OpenMP_Serial-release build_time=209 run_time=395
gcc-7.2.0-OpenMP-release build_time=121 run_time=128
gcc-7.2.0-OpenMP_Serial-release build_time=206 run_time=357
gcc-7.2.0-Serial-release build_time=119 run_time=227
ibm-16.1.0-Serial-release build_time=503 run_time=394
#######################################################
FAILED TESTS
#######################################################
ibm-16.1.0-OpenMP-release (test failed)
ibm-16.1.0-OpenMP_Serial-release (test failed)

Bowman is running but so far intel-16.4.258-Pthread-release and intel-16.4.258-Serial-release have passed. Will post when that's done.

**Comment by brian-kelley** [comment]
Bowman:
#######################################################
PASSED TESTS
#######################################################
intel-16.4.258-Pthread-release build_time=719 run_time=1031
intel-16.4.258-Pthread_Serial-release build_time=1052 run_time=1981
intel-16.4.258-Serial-release build_time=704 run_time=1004
intel-17.2.174-OpenMP-release build_time=885 run_time=580
intel-17.2.174-OpenMP_Serial-release build_time=1211 run_time=1492
intel-17.2.174-Pthread-release build_time=813 run_time=898
intel-17.2.174-Pthread_Serial-release build_time=1132 run_time=1791
intel-17.2.174-Serial-release build_time=782 run_time=884

**Comment by ndellingwood** [comment]
Cross-reference trilinos/Trilinos#6615

**Pull request merged**
