### PR TITLE
Added option to output colors to file

### PR DESCRIPTION
**Pull request by rohit-mp**
Hi @william76 @srajama1, this is with reference to issue #444 I just raised.

I've followed a code structure similar to ```print_1Dview``` and updated only distance 1 graph coloring. Is this fine or would you like me to change anything? If fine, I can add the same to distance 2 graph coloring as well.

A side-effect would be that the output file gets overwritten unless ```repeat``` is set to 1. Do we let the overwriting happen or force ```repeat``` to 1?

### CODE REVIEW

**Comment by william76** [comment]
@rohit-mp 
I had a quick look and it generally looks fine to me... here are my thoughts:
  
1. You're trying to merge into the `master` branch... we don't allow merges directly into that branch.  Can you switch this PR to merge into the `develop` branch instead?
2. This is a preference of mine, but in the `kk_print_to_file` you're limiting it to purely printing to files.  I prefer making an interface like the one used in `dump_graphviz`:
    https://github.com/kokkos/kokkos-kernels/blob/f934ce71bbd15e32e12dba628f21a78f4f3367c4/src/graph/KokkosGraph_Distance2ColorHandle.hpp#L389-L395
    where I pass in an `ostream` object instead of a filename... this lets you pass in `std::cout` or `std::cerr` if you want to write to stdout or stderr on the console or you can change it to a file stream as well if you want to write to a file... For example, in `perf_test/graph/KokkosGraph_color_d2.cpp` I pass in a `std::ofstream` object so I can write to a file:
    https://github.com/kokkos/kokkos-kernels/blob/f934ce71bbd15e32e12dba628f21a78f4f3367c4/perf_test/graph/KokkosGraph_color_d2.cpp#L385-L387

So (1) is pretty critical, it must definitely be addressed (2) is mostly a preference of mine, but I like the flexibility to be able to easily switch from writing a file to printing to stderr/stdout easily... @ndellingwood , @srajama -- do you guys have any opinions on using streams rather than a filename?

**Comment by mhoemmen** [comment]
I fixed Part 1 (changing the base branch to develop).

**Comment by rohit-mp** [comment]
> I fixed Part 1 (changing the base branch to develop).
Thanks @mhoemmen !

**Comment by rohit-mp** [comment]
(2) can be done as well but do you plan on giving the output flexibility while running the program instead of having to modify the source code? If yes, would we have to fix/dedicate some filename to cout and cerr? If no, I could make the changes to pass an ostream and push another commit.

**Comment by william76** [comment]
@ndellingwood 
Spot check results for this PR:

RHEL7
------
```
--------------------------------------------------------------------------------
-
-           K O K K O S   K E R N E L S   S P O T   C H E C K
-
--------------------------------------------------------------------------------

Kokkos
- URL...: git@github.com:william76/kokkos.git
- Branch: develop
- SHA1..: 54ef2182c1ca18ff41e63ac2c62413a0be66aad0

KokkosKernels
- URL...: git@github.com:william76/kokkos-kernels.git
- Branch: outputfile
- SHA1..: 37782f4b084b7e4b62ad26d81da308bb69878cd3

Spot Check Command
/home/wcmclen/dev/kk-dev/source/KokkosKernels/scripts/test_all_sandia \
    --spot-check \
    --kokkoskernels-path=/home/wcmclen/dev/kk-dev/source/KokkosKernels \
    --kokkos-path=/home/wcmclen/dev/kk-dev/source/Kokkos \
    --arch="" \
    --skip-hwloc \
    gcc  \
    --num=2

ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'sems-git'
Running on machine: sems
Going to test compilers:  gcc/5.3.0 gcc/7.2.0
Testing compiler gcc/5.3.0
Testing compiler gcc/7.2.0
  Starting job gcc-5.3.0-OpenMP-release
  Starting job gcc-7.2.0-Serial-release
  PASSED gcc-5.3.0-OpenMP-release
  PASSED gcc-7.2.0-Serial-release
#######################################################
PASSED TESTS
#######################################################
gcc-5.3.0-OpenMP-release build_time=171 run_time=147
gcc-7.2.0-Serial-release build_time=146 run_time=191
#######################################################
FAILED TESTS
#######################################################

--------------------------------------------------------------------------------
- Elapsed time: 340 seconds.
0m0.008s 0m0.011s
116m24.093s 6m24.545s
--------------------------------------------------------------------------------
```

White
------
```
--------------------------------------------------------------------------------
-
-           K O K K O S   K E R N E L S   S P O T   C H E C K
-
--------------------------------------------------------------------------------

Kokkos
- URL...: git@github.com:william76/kokkos.git
- Branch: develop
- SHA1..: 54ef2182c1ca18ff41e63ac2c62413a0be66aad0

KokkosKernels
- URL...: git@github.com:william76/kokkos-kernels.git
- Branch: outputfile
- SHA1..: 37782f4b084b7e4b62ad26d81da308bb69878cd3

Spot Check Command
bsub -J wcmclen-KK-Test \
    -W 6:00 \
    -Is \
    -q rhel7F \
    /home/wcmclen/dev/kk-dev/source/KokkosKernels/scripts/test_all_sandia \
        --spot-check \
        --kokkoskernels-path=/home/wcmclen/dev/kk-dev/source/KokkosKernels \
        --kokkos-path=/home/wcmclen/dev/kk-dev/source/Kokkos \
        --arch="Power8,Kepler37" \
        --skip-hwloc \
        cuda \
        gcc \
        --num=2

***Forced exclusive execution
Job <45427> is submitted to queue <rhel7F>.
<<Waiting for dispatch ...>>
<<Starting on white26>>
Running on machine: white
Going to test compilers:  gcc/6.4.0 gcc/7.2.0 cuda/9.2.88 cuda/10.0.130
Testing compiler gcc/6.4.0
Testing compiler gcc/7.2.0
  Starting job gcc-7.2.0-OpenMP-release
  Starting job gcc-6.4.0-OpenMP_Serial-release
  PASSED gcc-7.2.0-OpenMP-release
  Starting job gcc-7.2.0-Serial-release
  PASSED gcc-6.4.0-OpenMP_Serial-release
Testing compiler cuda/9.2.88
  Starting job gcc-7.2.0-OpenMP_Serial-release
  PASSED gcc-7.2.0-Serial-release
  PASSED gcc-7.2.0-OpenMP_Serial-release
Testing compiler cuda/10.0.130
  Starting job cuda-9.2.88-Cuda_OpenMP-release
  PASSED cuda-9.2.88-Cuda_OpenMP-release
  Starting job cuda-10.0.130-Cuda_Serial-release
  PASSED cuda-10.0.130-Cuda_Serial-release
#######################################################
PASSED TESTS
#######################################################
cuda-10.0.130-Cuda_Serial-release build_time=933 run_time=483
cuda-9.2.88-Cuda_OpenMP-release build_time=963 run_time=388
gcc-6.4.0-OpenMP_Serial-release build_time=465 run_time=399
gcc-7.2.0-OpenMP-release build_time=319 run_time=143
gcc-7.2.0-OpenMP_Serial-release build_time=399 run_time=331
gcc-7.2.0-Serial-release build_time=238 run_time=220
#######################################################
FAILED TESTS
#######################################################

--------------------------------------------------------------------------------
- Elapsed time: 4373 seconds.
--------------------------------------------------------------------------------
```

**Comment by srajama1** [comment]
@rohit-mp : Thanks again for contributing to Kokkos Kernels.

**Comment by rohit-mp** [comment]
Thanks!

**Pull request merged**
