### PR TITLE
Remove include for nonexistent directory

### PR DESCRIPTION
**Pull request by sethrj**
When building a Fortran code that links against Kokkos as part of the same TriBITS project, the compiler complains because the Kokkos logic references a nonexistent directory. This PR simply removes the offending include command.

```
f951: Warning: Nonexistent include directory ‘/home/s3j/.local/src/scale/Trilinos/packages/kokkos-kernels/src/batched/impl’ [-Wmissing-include-dirs]
```

See https://github.com/trilinos/Trilinos/pull/6669

### CODE REVIEW

**Comment by srajama1** [comment]
@sethrj Are you a Sandian ? Then you can follow the spot-check process, if not one of us will have to do the spot check ?

**Comment by sethrj** [comment]
@srajama1 I interned at SNL 15 years ago 😆 but no, I'm at ORNL. Could one of you please take care of it?

**Comment by srajama1** [comment]
@sethrj Thanks ! We will run the spot-check.

**Comment by ndellingwood** [comment]
These changes were made against kokkos-kernels master branch, but it in develop with the updated CMake it looks like there is still a line like this:
`LIST(APPEND KK_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/batched/impl)`

@sethrj would you like to update your PR (and commit into develop) or would you like us to issue a new PR?

**Comment by sethrj** [comment]
@ndellingwood I'll update the PR, I clearly didn't follow the rabbit hole deep enough (we use a mirror of trilinos, which uses a snapshot of kokkos master, which ....)

**Comment by sethrj** [comment]
@ndellingwood OK should be good to go now.

**Comment by ndellingwood** [comment]
Thanks @sethrj , running spot-check tests now. Since you're building through Trilinos we'll patch this into Trilinos as well.

**Comment by ndellingwood** [comment]
Spot-check passes on kokkos-dev-2 (no surprise), thanks for the contribution @sethrj !

```
Repository Status:  8d8005c9df50f39268780e921604742370b45fe1 Remove include for nonexistent directory


Going to test compilers:  gcc/7.3.0 gcc/8.3.0 gcc/9.1 intel/18.0.5 clang/8.0 cuda/10.1
Testing compiler gcc/7.3.0
  Starting job gcc-7.3.0-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-7.3.0-OpenMP-release
Testing compiler gcc/8.3.0
  Starting job gcc-7.3.0-Pthread-release
kokkos options: 
kokkos devices: Pthread
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-7.3.0-Pthread-release
Testing compiler gcc/9.1
  Starting job gcc-8.3.0-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-8.3.0-Serial-release
  Starting job gcc-9.1-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-9.1-OpenMP-release
Testing compiler intel/18.0.5
  Starting job gcc-9.1-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-9.1-Serial-release
Testing compiler clang/8.0
  Starting job intel-18.0.5-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED intel-18.0.5-OpenMP-release
  Starting job clang-8.0-Cuda_OpenMP-release
kokkos options: 
kokkos devices: Cuda,OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -Wno-pass-failed 
  PASSED clang-8.0-Cuda_OpenMP-release
Testing compiler cuda/10.1
  Starting job clang-8.0-Pthread_Serial-release
kokkos options: 
kokkos devices: Pthread,Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -Wno-pass-failed 
  PASSED clang-8.0-Pthread_Serial-release
  Starting job cuda-10.1-Cuda_OpenMP-release
kokkos options: 
kokkos devices: Cuda,OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED cuda-10.1-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=116 run_time=151
clang-8.0-Pthread_Serial-release build_time=48 run_time=154
cuda-10.1-Cuda_OpenMP-release build_time=152 run_time=142
gcc-7.3.0-OpenMP-release build_time=42 run_time=47
gcc-7.3.0-Pthread-release build_time=39 run_time=77
gcc-8.3.0-Serial-release build_time=40 run_time=71
gcc-9.1-OpenMP-release build_time=51 run_time=46
gcc-9.1-Serial-release build_time=45 run_time=72
intel-18.0.5-OpenMP-release build_time=122 run_time=45
```

**Comment by ndellingwood** [comment]
@sethrj I put in the matching patch to trilinos in PR trilinos/Trilinos#6757

**Pull request merged**
