### PR TITLE
Moving includes inside ifdefs

### PR DESCRIPTION
**Pull request by mndevec**
Related to #199.
Compilation on white with single lno, size_type and scalar_type and two execution spaces.
--previously took 5m 18s
--after changes suggested by @ibaned: reduced to 4m 21 s.

### CODE REVIEW

**Comment by ndellingwood** [comment]
Spot-check passes:

```
[ndellin@kokkos-dev TestAllSandia-spot]$ ../../scripts/test_all_sandia --spot-check --skip-hwloc
Going to test compilers:  gcc/5.3.0 intel/16.0.1 clang/3.9.0 cuda/8.0.44
Testing compiler gcc/5.3.0
Testing compiler intel/16.0.1
Testing compiler clang/3.9.0
Testing compiler cuda/8.0.44
  Starting job gcc-5.3.0-Serial-release
  Starting job clang-3.9.0-Pthread_Serial-release
  Starting job intel-16.0.1-OpenMP-release
  PASSED intel-16.0.1-OpenMP-release
  PASSED gcc-5.3.0-Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  PASSED cuda-8.0.44-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=841 run_time=2526
cuda-8.0.44-Cuda_OpenMP-release build_time=1288 run_time=1097
gcc-5.3.0-Serial-release build_time=689 run_time=1160
intel-16.0.1-OpenMP-release build_time=912 run_time=435
#######################################################
```

**Comment by mndevec** [comment]
Nathan, did you time the compilation?

**Comment by ndellingwood** [comment]
@mndevec I'm rerunning with the commit prior to your commit, SHA 70032bcaad7d114f111fc2ca655681bf21b3a178
The output from test_all_sandia includes build times, so I will sum those up and compare the two results.

**Comment by ndellingwood** [comment]
@mndevec I reran the spot-check with this PR and with the prior commit when the machine wasn't busy to get better comparison for times, nice improvements :)

Spot-check results with this PR:
```
[ndellin@kokkos-dev TestAllSandia-spot]$ ../../scripts/test_all_sandia --spot-check --skip-hwloc
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=696 run_time=2003
cuda-8.0.44-Cuda_OpenMP-release build_time=796 run_time=1123
gcc-5.3.0-Serial-release build_time=564 run_time=1125
intel-16.0.1-OpenMP-release build_time=771 run_time=370
#######################################################
```

Spot check results with commit prior to this PR including build times

```
[ndellin@kokkos-dev TestAllSandia-spot]$ ../../scripts/test_all_sandia --spot-check --skip-hwloc
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=852 run_time=2062
cuda-8.0.44-Cuda_OpenMP-release build_time=1130 run_time=1144
gcc-5.3.0-Serial-release build_time=645 run_time=948
intel-16.0.1-OpenMP-release build_time=869 run_time=367
#######################################################
```

**Comment by mndevec** [comment]
Thanks @ndellingwood and @ibaned !

**Comment by mndevec** [comment]
@ndellingwood , @crtrott , @srajama1 
I don't have merge access, can you merge this branch?

**Pull request merged**
