### PR TITLE
Master release 4.4.01

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Trilinos snapshot PR: https://github.com/trilinos/Trilinos/pull/13446
Please do not merge until confirmation that PR has passed testing and is approved

**Review by lucbv — APPROVED** [review]

**Comment by ndellingwood** [comment]
Trilinos PR https://github.com/trilinos/Trilinos/pull/13446 has passed

**Comment by ndellingwood** [comment]
@lucbv ready for merge, the GA workflow should handle the tagging

**Comment by lucbv** [comment]
Yes, I will go ahead with the merge and do the final steps for tagging and checking the generated artifacts

**Pull request merged**
