### PR TITLE
KokkosKernels_ExecSpaceUtils: kk_is_a64fx_mem_space add brace

### PR DESCRIPTION
**Pull request by ndellingwood**
Fix compilation issues on ARM architectures
Cleanup indentation

### CODE REVIEW

**Comment by ndellingwood** [comment]
This PR addresses nightly build errors on mayer ARM testbed following PR #1054, e.g.:

```
23:40:47 /home/jenkins/mayer/jenkins-new/workspace/KokkosKernels_Mayer_gnu7/kokkos-kernels/src/common/KokkosKernels_ExecSpaceUtils.hpp: In function ‘constexpr bool KokkosKernels::Impl::kk_is_a64fx_mem_space() [with ExecutionSpace = Kokkos::HostSpace]’:
23:40:47 /home/jenkins/mayer/jenkins-new/workspace/KokkosKernels_Mayer_gnu7/kokkos-kernels/src/common/KokkosKernels_ExecSpaceUtils.hpp:179:3: error: a template declaration cannot appear at block scope
23:40:47    template <typename MemorySpace>
23:40:47    ^~~~~~~~
23:40:47 /home/jenkins/mayer/jenkins-new/workspace/KokkosKernels_Mayer_gnu7/kokkos-kernels/src/common/KokkosKernels_ExecSpaceUtils.hpp:258:93: error: a function-definition is not allowed here before ‘{’ token
23:40:47  inline int kk_get_suggested_team_size(const int vector_size, const ExecSpaceType exec_space){
23:40:47  
```


Sample Reproducer (gcc/7):
```
module load cmake/3.17.1 gnu7/7.2.0

$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=OpenMP --arch=ARMV8_THUNDERX2 --compiler=g++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="14"   --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-options=disable_deprecated_code --no-examples
```

**Review by lucbv — APPROVED** [review]
It's always tricky to make sure we hit all code path correctly with all the pre-processor guards! Thanks for the fix @ndellingwood

**Comment by ndellingwood** [comment]
Just to verify, this passed a sample build+test on Mayer with gnu/7 and OpenMP backend:

```
bash-4.2$ ctest
Test project /ascldap/users/ndellin/kokkos/testing/Mayer-gnu
      Start  1: blas_openmp
 1/15 Test  #1: blas_openmp ......................   Passed    7.05 sec
      Start  2: batched_dla_openmp
 2/15 Test  #2: batched_dla_openmp ...............   Passed  111.16 sec
      Start  3: sparse_openmp
 3/15 Test  #3: sparse_openmp ....................   Passed  374.49 sec
      Start  4: graph_openmp
 4/15 Test  #4: graph_openmp .....................   Passed    9.32 sec
      Start  5: common_openmp
 5/15 Test  #5: common_openmp ....................   Passed    2.83 sec
      Start  6: wiki_crsmatrix
 6/15 Test  #6: wiki_crsmatrix ...................   Passed    0.03 sec
      Start  7: wiki_spmv
 7/15 Test  #7: wiki_spmv ........................   Passed    0.05 sec
      Start  8: wiki_spadd
 8/15 Test  #8: wiki_spadd .......................   Passed    0.09 sec
      Start  9: wiki_spgemm
 9/15 Test  #9: wiki_spgemm ......................   Passed    0.17 sec
      Start 10: wiki_gauss_seidel
10/15 Test #10: wiki_gauss_seidel ................   Passed    0.15 sec
      Start 11: wiki_coloring
11/15 Test #11: wiki_coloring ....................   Passed    0.03 sec
      Start 12: wiki_mis2
12/15 Test #12: wiki_mis2 ........................   Passed    0.33 sec
      Start 13: wiki_coarsening
13/15 Test #13: wiki_coarsening ..................   Passed    0.08 sec
      Start 14: wiki_rcm
14/15 Test #14: wiki_rcm .........................   Passed    0.04 sec
      Start 15: gmres_test_real_A
15/15 Test #15: gmres_test_real_A ................   Passed    0.31 sec

100% tests passed, 0 tests failed out of 15

Total Test time (real) = 506.20 sec
```

**Review by e10harvey — COMMENTED** [review]
Thanks, @ndellingwood !

**Pull request merged**
