### PR TITLE
Drop "fenl" example

### PR DESCRIPTION
**Pull request by dalg24**
Commented out  since https://github.com/kokkos/kokkos-kernels/pull/737 that is 2y 1/2 ago but presumably does not compile for much longer than that.

https://github.com/kokkos/kokkos-kernels/blob/ddf1b3df43fed1674e166516e4f7169ccce3d224/example/fenl/VectorImport.hpp#L114-L117
is what caught my eye.  `Kokkos::Impl::StaticAssert` was removed almost 4y ago (see kokkos/kokkos#2130)

Just being pragmatic.  Fix or remove.  I suggest remove.

### CODE REVIEW

**Comment by lucbv** [comment]
@srajama1 do you know who is using/needing this? I have also wanted to remove this for a while now...

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO INSPECTION HAS BEEN PERFORMED ON THIS PULL REQUEST! - This PR must be inspected by setting label 'AT: PRE-TEST INSPECTED'.

**Comment by lucbv** [comment]
Superseded by PR #1657

**Comment by lucbv** [comment]
See above comment

**Pull request closed without merging**
