### PR TITLE
Some compilers throw shadow warnings in static functions

### PR DESCRIPTION
**Pull request by jgfouca**
Do a minor rename to make them happy.

### CODE REVIEW

**Review by lucbv — APPROVED** [review]

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection is Not Necessary for this Pull Request.

**Review by ndellingwood — APPROVED** [review]

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job KokkosKernels_PullRequest_VEGA90A_Tpls_ROCM561 to start: Total Wait = 3603
- Other jobs have been previously started - We must stop them...
- Terminating Build #1459 of Jenkins job KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build #1047 of Jenkins job KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930_Tpls_CLANG13CUDA10 on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build #701 of Jenkins job KokkosKernels_PullRequest_GNU1021 on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build #688 of Jenkins job KokkosKernels_PullRequest_GNU1021_Light_LayoutRight on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build #689 of Jenkins job KokkosKernels_PullRequest_Tpls_GNU1021 on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build #693 of Jenkins job KokkosKernels_PullRequest_Tpls_INTEL19_solo on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build #665 of Jenkins job KokkosKernels_PullRequest_CLANG1001_solo on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build #1143 of Jenkins job KokkosKernels_PullRequest_VEGA90A_ROCM561 on Jenkins server at https://jenkins-son.sandia.gov

**Comment by ndellingwood** [comment]
Cross-reference as follow-on to #2281

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job KokkosKernels_PullRequest_VEGA90A_Tpls_ROCM561 to start: Total Wait = 3603
- Other jobs have been previously started - We must stop them...
- Terminating Build #1462 of Jenkins job KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build #1050 of Jenkins job KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930_Tpls_CLANG13CUDA10 on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build #704 of Jenkins job KokkosKernels_PullRequest_GNU1021 on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build #691 of Jenkins job KokkosKernels_PullRequest_GNU1021_Light_LayoutRight on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build #692 of Jenkins job KokkosKernels_PullRequest_Tpls_GNU1021 on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build #696 of Jenkins job KokkosKernels_PullRequest_Tpls_INTEL19_solo on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build #668 of Jenkins job KokkosKernels_PullRequest_CLANG1001_solo on Jenkins server at https://jenkins-son.sandia.gov
- Terminating Build #1146 of Jenkins job KokkosKernels_PullRequest_VEGA90A_ROCM561 on Jenkins server at https://jenkins-son.sandia.gov

**Pull request merged**
