### PR TITLE
KokkoBatched - add radial complex version is needed in ifpack2

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
@ndellingwood this PR is needed to use complex in Ifpack2 tests.

### CODE REVIEW

**Comment by crtrott** [comment]
Did you test this in any way within Trilinos i.e. that it fixes the bug Nathan found??

**Comment by ndellingwood** [comment]
@kyungjoo-kim There were some new errors in the integration tests last night that this PR did not catch (Serial, OpenMP, Cuda, did not retest Pthreads), for example:
```

ascldap/users/ndellin/IntegrationTests/serial-update/trilinos-update/packages/kokkos-kernels/src/batched/KokkosBatched_AddRadial_Internal.hpp(31): error: no operator "*" matches these operands
            operand types are: KokkosBatched::Experimental::Vector<KokkosBatched::Experimental::SIMD<double>, 8> * const KokkosBatched::Experimental::Vector<KokkosBatched::Experimental::SIMD<bool>, 8>
            A[i*as] +=  ValueType(minus_abs_tiny)*(a_real <  0);
```

See issue [kokkos/kokkos#1413](https://github.com/kokkos/kokkos/issues/1413)

**Comment by ndellingwood** [comment]
@kyungjoo-kim A Jenkins build also failed last night Shepard gcc/4.9.3 OpenMPSerial due to `-Werror`

```
<https://jenkins-son.sandia.gov/job/KokkosKernels_Shepard_GCC493_OpenMPSerial/ws/kokkos-kernels/unit_test/batched/Test_Batched_VectorRelation.hpp>:24:36: error: typedef 'mag_type' locally defined but not used [-Werror=unused-local-typedefs]
     typedef typename ats::mag_type mag_type;

/home/jenkins/shepard/workspace/KokkosKernels_Shepard_GCC493_OpenMPSerial/kokkos-kernels/unit_test/batched/Test_Batched_VectorView.hpp:116:46: error: typedef 'value_type' locally defined but not used [-Werror=unused-local-typedefs]

```

I can put a quick PR in for these `-Werror` issues.

**Comment by ndellingwood** [comment]
Put in PR #165 for the `-Werror` issues.

**Pull request merged**
