### PR TITLE
Release candidate 3.2.1

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Cross-referencing:

kokkos/kokkos#3618 (Kokkos 3.2.1 release)
trilinos/Trilinos#8359 (Trilinos with 3.2.1 snapshots)

**Review by brian-kelley — APPROVED** [review]

**Review by e10harvey — APPROVED** [review]

**Review by srajama1 — APPROVED** [review]
Thanks @ndellingwood !

**Comment by srajama1** [comment]
Can I merge this to master ?

**Comment by ndellingwood** [comment]
@srajama1 yes, this should be good to go into master, thanks!

**Comment by srajama1** [comment]
Thanks @ndellingwood  ! Done.

**Pull request merged**
