### PR TITLE
Rc 3.6.0 changelog

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by lucbv** [comment]
Thanks @ndellingwood I will give this a look!

**Review by kliegeois — APPROVED** [review]
Looks good to me for the batched sparse linear algebra, thanks!

**Review by vqd8a — APPROVED** [review]
LGTM. Thanks, @ndellingwood

**Review by e10harvey — APPROVED** [review]
Thank you, @ndellingwood . If @srajama1 would like it added:
- Unit test Batched GEMM and demostrate GMRES example convergence with bhalf_t.

**Comment by ndellingwood** [comment]
@e10harvey I'll add that to the Batched Sparse Linear algebra section of the features, thanks for the feedback

**Pull request merged**
