### PR TITLE
Feature/perf testing perfsuite

### PR DESCRIPTION
**Pull request by ajpowelsnl**
Code changes proposed here encapsulate integration of rajaperfsuite (RPS) as a kokkos-kernels (KK) third party library (TPL).  In this scenario, RPS is used **only** as performance testing infrastructure to run RPS implementations of KK performance tests, towards the goal of having nightly performance builds, testing and reporting.  Here, the RPS infrastructure will **only** be built and run with KK performance tests, and **not** the RPS built-in kernels.   RPS infrastructure (as a KK TPL) will output 5 data files:  RAJAPerf-checksum.txt , RAJAPerf-fom.csv , RAJAPerf-speedup.csv, and RAJAPerf-timing.csv.  The "RAJAPerf-timing.csv" files will be accumulated to generate line graphs showing performance over time in watchr (Jenkins visualization plugin).  We have implemented one KK performance test, sparse_spmv (with more soon to come).  This example is detailed below.

To exercise this code, please do the following:

1) Build and install Kokkos:

cd kokkos
git pull
mkdir build
cd build
cmake -DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_CUDA_LAMBDA=ON -DKokkos_ARCH_VOLTA70=ON -DCMAKE_INSTALL_PREFIX=$HOME/installs ..
make -j12
make install

2) Clone the performance test input data repo, decompress the data.zip file, and set the path to this input data:

git clone git@github.com:DavidPoliakoff/data-for-kernels.git
cd data-for-kernels/
unzip data.zip
export KOKKOS_KERNELS_INPUT_DATA=/$HOME/data-for-kernels/data

3) Pull in our fork of KK (ajpowelsnl/kokkos-kernels)

git clone git@github.com:ajpowelsnl/kokkos-kernels.git

4) cd to kokkos-kernels

5) Set $KOKKOS_INSTALL_DIR

(e.g., export KOKKOS_INSTALL_DIR=$HOME/installs)

6) create build directory

(e.g., mkdir build)

7) change to build directory

(e.g., cd build)

8) Configure:

cmake \

-DKokkos_ROOT=$KOKKOS_INSTALL_DIR \

-DKokkosKernels_ENABLE_TESTS=ON \

-DKokkosKernels_ENABLE_TESTS_AND_PERFSUITE=ON \

-DCMAKE_BUILD_TYPE=Release \

-DCMAKE_CXX_STANDARD=14 .. \

9) Build:

(e.g., make -j16;make)

10) Change directory to the built executables, and run RPS-implemented sparse_spmv KK performance test:

(e.g., $KOKKOS_KERNELS_ROOT/$BUILD_DIRECTORY/ tpls/rajaperfsuite/bin)

./tracked_testing --input-data $ KOKKOS_KERNELS_INPUT_DATA

OUTPUT:

[ajpowel@kokkos-dev-2 bin]$ ls -l1 RAJAPerf-*

-rw-r----- 1 ajpowel ajpowel 1597 Jun  8 16:10 RAJAPerf-checksum.txt
-rw-r----- 1 ajpowel ajpowel  855 Jun  8 16:10 RAJAPerf-fom.csv
-rw-r----- 1 ajpowel ajpowel  350 Jun  8 16:10 RAJAPerf-speedup.csv
-rw-r----- 1 ajpowel ajpowel  328 Jun  8 16:10 RAJAPerf-timing.csv

**_CAVEATS:_**

- CMake changes represent an intermediate state, not a final, polished design;

- The executable name and location (in $KOKKOS_KERNELS_ROOT/$BUILD_DIRECTORY/ tpls/rajaperfsuite/bin) represent a prototype, and will change, once we have input from the team.

- The outpufile names (i.e., RAJAPerf-*.csv) will be Kokkos-i-fied to something on the order of "KokkosKernelsPerf-*.csv," once we have team input.

- If the team accepts this design (with suggested modifications, of course), this approach will be ported to Kokkos Core. 

- If

### CODE REVIEW

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           WARNING: NO REVIEWERS HAVE BEEN REQUESTED FOR THIS PULL REQUEST!

**Comment by lucbv** [comment]
@ajpowelsnl why are there so many files added in this PR?
It would be nice if we can avoid adding thousands more files to the repo...

**Comment by srajama1** [comment]
the tpl directory should not be committed into our repo. It should be configured during compile time like other tpls.

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           WARNING: NO REVIEWERS HAVE BEEN REQUESTED FOR THIS PULL REQUEST!

**Comment by srajama1** [comment]
@ajpowelsnl It is ok for this to be the first cut, but we do not want to push 4K files into the repo. Even if you remove it later, git will maintain it in the background which will be part of every clone. Two options (i) We could leave it here as a PR until the second step is complete (ii) find an intermediate quick and dirty way as a temporary fix and do (i) as next step.

**Comment by ajpowelsnl** [comment]
@lucbv @srajama1 @DavidPoliakoff Adding a config file to RAJAPerf Suite repo to enable watchr-based reporting of Kokkos Kernels performance tests for our nightly Jenkins job weaver ( https://jenkins-son.sandia.gov/view/KokkosKernels/job/KokkosKernels_develop_weaver_cuda_rps_perf_testing/ )

**Comment by ajpowelsnl** [comment]
> @ajpowelsnl It is ok for this to be the first cut, but we do not want to push 4K files into the repo. Even if you remove it later, git will maintain it in the background which will be part of every clone. Two options (i) We could leave it here as a PR until the second step is complete (ii) find an intermediate quick and dirty way as a temporary fix and do (i) as next step.

@srajama1 that makes sense.  @nellingwood suggested that it might be possible to use git submodules; this approach possibly avoids what you and Luc were mentioning (i.e., committing thousands of files to KK).  I'll keep you posted, and many thanks for the design feedback.

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           WARNING: NO REVIEWERS HAVE BEEN REQUESTED FOR THIS PULL REQUEST!

**Comment by brian-kelley** [comment]
@ajpowelsnl If this PR is superseded by #1037, do you want to just close this one?

**Comment by ajpowelsnl** [comment]
> @ajpowelsnl If this PR is superseded by #1037, do you want to just close this one?

@brian-kelley - yes, that sounds good.  I'll close #1015

**Comment by ajpowelsnl** [comment]
This PR is superseded by #1037

**Pull request closed without merging**
