### PR TITLE
Convert Lambdas to Functors in unit test

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
@crtrott @srajama1 I tested with cuda8 + gcc 5.4 on White with Cuda_OpenMP enabled, builds and tests pass. Should I run test_all_sandia also?

**Comment by ndellingwood** [comment]
@crtrott @srajama1 I'm not able to request reviewers, add labels etc - should I be able to or is this managed by some of the core developers?

**Comment by srajama1** [comment]
I am not sure about the labels. I thought there is one team for kokkos and kokkoskernels, let me check. I can review.

**Comment by ndellingwood** [comment]
Some OpenMP tests failed, just a sec...

**Comment by srajama1** [comment]
Can you create a github issue, so we know what is this for ?

**Comment by srajama1** [comment]
Changes look good to me. Let me know if tests pass, I will click the button

**Comment by ndellingwood** [comment]
Will do. Have same OpenMP tests failing on this branch on develop, I probably missed something when generating the makefile or something. Once I sort this out then I'll get test_all_sandia running

**Comment by ndellingwood** [comment]
Here's the issue I'm having with testing for this PR with a generated makefile:

OpenMP with gcc5.4: builds and tests pass.
Cuda 8 + gcc5.4 with OpenMP: All unit tests build, however 137/204 tests fail for OpenMP. All Cuda tests pass. This occurs on develop branch and this PR.

I used the compileKokkosKernels.sh script (with minor changes for paths etc) to create the makefile. 

Allocated a node

Tested with make test -j

Any suggestions?

**Comment by mndevec** [comment]
Are you testing on white?

**Comment by ndellingwood** [comment]
@mndevec yes

**Comment by ndellingwood** [comment]
For the develop branch I added this when generating the makefile to avoid compiler issues with lambda support:

```
KOKKOS_CUDA_OPTIONS=enable_lambda
--with-cuda-options=${KOKKOS_CUDA_OPTIONS}  
```

**Comment by mndevec** [comment]
The errors I get are CudaDeviceSync errors for OpenMP tests. 
I suspect something weird is happening with Kokkos::fence(). Let me change the Kokkos::fences to execspace::fence and try again.


 @crtrott

**Comment by ndellingwood** [comment]
Did some testing with @mndevec, here's a summary:

Building alone with Cuda or OpenMP results in all tests building, all tests passing.

Building with Cuda and OpenMP results in all tests building, but many OpenMP tests failing with this type of error message:
```
unknown file: Failure
C++ exception with description "cudaDeviceSynchronize() error( cudaErrorAssert): device-side assert triggered /ascldap/users/ndellin/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:119
Traceback functionality not available
" thrown in the test body.
```

We tried replacing occurrences of `Kokkos::fence()` with `DeviceType::execution_space::fence()` which fixed the failing tests for that file (tested with `unit_test/batched/Test_Batched_SerialGemm.hpp`)

@crtrott

**Comment by ndellingwood** [comment]
This PR should be safe for merge as the error above existed prior and is not affected by these changes.

**Pull request merged**
