### PR TITLE
Master release 4.4.00

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Trilinos snapshot PR: https://github.com/trilinos/Trilinos/pull/13334
Do not merge until confirmation that PR has passed testing and is approved

**Comment by ndellingwood** [comment]
applied clang-format in [f7df9ff](https://github.com/kokkos/kokkos-kernels/pull/2303/commits/f7df9fffab8dd762d6ec7aaf78c5a1ee6bdfde29) , made a mistake during the revert of #2185

snapshot to Trilinos updated as well

**Comment by ndellingwood** [comment]
updated the other yaml workflow files to use kokkos@4.3.01

**Comment by ndellingwood** [comment]
Some of the AT2 jobs fail with:
```
 A job started hook has been configured by the self-hosted runner administrator
Run '/home/runner/snl_verify.sh'
[2024-08-08T01:26:43Z INFO  github_api_requester] Success Status for user ndellingwood: 200 OK
[2024-08-08T01:26:45Z INFO  github_api_requester] Success Status for user lucbv: 200 OK
[2024-08-08T01:26:45Z INFO  github_api_requester] Success Status for user jgfouca: 200 OK
[2024-08-08T01:26:46Z ERROR github_api_requester] Failure Status for user rbberger: 404 Not Found
[2024-08-08T01:26:46Z INFO  verification::job_approver] found unapproved commit from committer: "rbberger"
[2024-08-08T01:26:46Z INFO  verification::job_approver] last unapproved commit made on: "2024-08-01 21:13:19"
[2024-08-08T01:26:56Z INFO  verification::job_approver] .github directory was modified, requiring special approval...
[2024-08-08T01:26:59Z ERROR verification::job_approver] AT2: latest special approval: No special approval found
[2024-08-08T01:26:59Z INFO  verification] Job is not approved
Error: Process completed with exit code 1.
```

**Comment by ndellingwood** [comment]
Just noting AT2 jobs will not run due to `ERROR github_api_requester] Failure Status for user rbberger: 404 Not Found` issues with external contributions
```
[2024-08-08T21:41:59Z ERROR github_api_requester] Failure Status for user rbberger: 404 Not Found
[2024-08-08T21:41:59Z INFO  verification::job_approver] found unapproved commit from committer: "rbberger"
[2024-08-08T21:41:59Z INFO  verification::job_approver] last unapproved commit made on: "2024-08-01 21:13:19"
```

This case is not covered by the `AT2-SPECIAL-APPROVAL` label

**Comment by ndellingwood** [comment]
Trilinos PR passed https://github.com/trilinos/Trilinos/pull/13334 , this is should be ready for final review

**Comment by ndellingwood** [comment]
@lucbv this is ready to merge and tag

**Review by lucbv — APPROVED** [review]

**Comment by lucbv** [comment]
Okay, approved and merged, will tag now

**Pull request merged**
