### PR TITLE
Fix an error in Krylov Handle documentation

### PR DESCRIPTION
**Pull request by kliegeois**
Fix a documentation error.
I put the WIT label not to use CI tests.

### CODE REVIEW

**Review by lucbv — APPROVED** [review]
Looks good, thanks

**Comment by kliegeois** [comment]
@ndellingwood 
Can we add this to 4.0?
This should not have any conflict.
Thanks!

**Comment by ndellingwood** [comment]
@kliegeois I'll add this to the release-candidate and update here with the sha, thanks!

**Comment by ndellingwood** [comment]
Cherry-picked to release-candidate-4.0.0 SHA 9f37dac2544be1bc9ac9c1ad771623d4828668e2

**Comment by kliegeois** [comment]
Thanks @ndellingwood  !

**Pull request merged**
