### PR TITLE
D2GC: Fix headers for Distance-1 use cases

### PR DESCRIPTION
**Pull request by william76**
Replaced a couple of places where we should be using `KokkosGraph_Distance1ColorHandle.hpp` instead of the older headers.  I probably should have done this in #375 but I just missed them.

Running spot-check now, I'll update results in comments.

FYI @ndellingwood

### CODE REVIEW

**Comment by william76** [comment]
# RHEL7 COE

```
--------------------------------------------------------------------------------
-
-           K O K K O S   K E R N E L S   S P O T   C H E C K
-
--------------------------------------------------------------------------------

Kokkos
- URL...: git@github.com:william76/kokkos.git
- Branch: develop
- SHA1..: 2a32d301cb07846f30722fa8de09f80c1ad272d7

KokkosKernels
- URL...: git@github.com:william76/kokkos-kernels.git
- Branch: D2GC-Cleanup
- SHA1..: 863be2b6f910209c89c412a07bcb3ac108bec10c

Spot Check Command
/home/wcmclen/dev/kk-dev/source/KokkosKernels/scripts/test_all_sandia \
    --spot-check \
    --kokkoskernels-path=/home/wcmclen/dev/kk-dev/source/KokkosKernels \
    --kokkos-path=/home/wcmclen/dev/kk-dev/source/Kokkos \
    --arch="" \
    --skip-hwloc \
    gcc  \
    --num=2

ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'sems-git'
Running on machine: sems
Going to test compilers:  gcc/5.3.0 gcc/7.2.0
Testing compiler gcc/5.3.0
Testing compiler gcc/7.2.0
  Starting job gcc-5.3.0-OpenMP-release
  Starting job gcc-7.2.0-Serial-release
  PASSED gcc-5.3.0-OpenMP-release
  PASSED gcc-7.2.0-Serial-release
#######################################################
PASSED TESTS
#######################################################
gcc-5.3.0-OpenMP-release build_time=164 run_time=129
gcc-7.2.0-Serial-release build_time=141 run_time=192
#######################################################
FAILED TESTS
#######################################################

--------------------------------------------------------------------------------
- Elapsed time: 334 seconds.
0m0.006s 0m0.011s
111m43.709s 5m52.367s
--------------------------------------------------------------------------------

wcmclen@sisu:~/dev/kk-dev/kk-test/rhel7-coe-Serial-OpenMP (git master)  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  [02:29 PM]
0 $ --------------------------------------------------------------------------------
OpenMP-release
  Starting job gcc-7.2.0-Serial-release
  PASSED gcc-5.3.0-OpenMP-release
  PASSED gcc-7.2.0-Serial-release
#######################################################
PASSED TESTS
#######################################################
gcc-5.3.0-OpenMP-release build_time=164 run_time=129
gcc-7.2.0-Serial-release build_time=141 run_time=192
#######################################################
FAILED TESTS
#######################################################

--------------------------------------------------------------------------------
- Elapsed time: 334 seconds.
0m0.006s 0m0.011s
111m43.709s 5m52.367s
--------------------------------------------------------------------------------
```

**Comment by ndellingwood** [comment]
@william76 actually we need this PR to go to Trilinos to patch it with these changes, can you resubmit there?

**Comment by ndellingwood** [comment]
@william76 oh oops, misinterpreted this PR, sorry! Reviewing now.

**Comment by william76** [comment]
@ndellingwood yeah, I saw these when I was doing the patching in Trilinos so this PR is just applying the two changes back into Kokkos-Kernels.  No point having Kokkos-Kernels loading the deprecated versions of the headers internally, I just missed these two in #375 I think.

**Comment by william76** [comment]
# Spot Check for KNL
```
--------------------------------------------------------------------------------
-
-           K O K K O S   K E R N E L S   S P O T   C H E C K
-
--------------------------------------------------------------------------------

Kokkos
- URL...: git@github.com:william76/kokkos.git
- Branch: develop
- SHA1..: 2a32d301cb07846f30722fa8de09f80c1ad272d7

KokkosKernels
- URL...: git@github.com:william76/kokkos-kernels.git
- Branch: D2GC-Cleanup
- SHA1..: 863be2b6f910209c89c412a07bcb3ac108bec10c

Spot Check Command
bsub -J wcmclen-KK-CUDA_OMP_Pascal \
    -W 6:00 \
    -Is \
    -q  \
    /home/wcmclen/dev/kk-dev/source/KokkosKernels/scripts/test_all_sandia \
        --spot-check \
        --kokkoskernels-path=/home/wcmclen/dev/kk-dev/source/KokkosKernels \
        --kokkos-path=/home/wcmclen/dev/kk-dev/source/Kokkos \
        --arch="KNL" \
        --skip-hwloc \
        intel \
        --num=2

Running on machine: bowman
Going to test compilers:  intel/17.2.174
Testing compiler intel/17.2.174
  Starting job intel-17.2.174-OpenMP-release
  PASSED intel-17.2.174-OpenMP-release
#######################################################
PASSED TESTS
#######################################################
intel-17.2.174-OpenMP-release build_time=1418 run_time=737
#######################################################
FAILED TESTS
#######################################################

--------------------------------------------------------------------------------
- Elapsed time: 2159 seconds.
0m0.020s 0m0.036s
431m35.674s 33m6.990s
--------------------------------------------------------------------------------
```

**Comment by william76** [comment]
# Spot Check for Cuda (white)

@ndellingwood I had that initial error on White that I emailed you about.  Per your advice I updated the latest kokkos-kernels version of develop in that had Kyungjoo's fixes in it and the spot check passed.

```
--------------------------------------------------------------------------------
-
-           K O K K O S   K E R N E L S   S P O T   C H E C K
-
--------------------------------------------------------------------------------

Kokkos
- URL...: git@github.com:william76/kokkos.git
- Branch: develop
- SHA1..: 2a32d301cb07846f30722fa8de09f80c1ad272d7

KokkosKernels
- URL...: git@github.com:william76/kokkos-kernels.git
- Branch: D2GC-Cleanup
- SHA1..: 8813f607fea2dc3986e58c2333102d6c7747222c

Spot Check Command
/home/wcmclen/dev/kk-dev/source/KokkosKernels/scripts/test_all_sandia \
    --spot-check \
    --kokkoskernels-path=/home/wcmclen/dev/kk-dev/source/KokkosKernels \
    --kokkos-path=/home/wcmclen/dev/kk-dev/source/Kokkos \
    --arch="Power8,Pascal60" \
    --skip-hwloc \
    cuda \
    --num=1

Running on machine: white
Going to test compilers:  cuda/9.2.88 cuda/10.0.130
Testing compiler cuda/9.2.88
Testing compiler cuda/10.0.130
  Starting job cuda-9.2.88-Cuda_OpenMP-release
  PASSED cuda-9.2.88-Cuda_OpenMP-release
  Starting job cuda-10.0.130-Cuda_Serial-release
  PASSED cuda-10.0.130-Cuda_Serial-release
#######################################################
PASSED TESTS
#######################################################
cuda-10.0.130-Cuda_Serial-release build_time=1105 run_time=340
cuda-9.2.88-Cuda_OpenMP-release build_time=1142 run_time=240
#######################################################
FAILED TESTS
#######################################################

--------------------------------------------------------------------------------
- Elapsed time: 2838 seconds.
0m0.016s 0m0.000s
853m14.423s 19m8.624s
--------------------------------------------------------------------------------
```

**Comment by william76** [comment]
@ndellingwood let me know if you want me to run any more spot checks or if this looks good to you =)

**Comment by ndellingwood** [comment]
@william76 looks good, thanks! Merging.

**Pull request merged**
