### PR TITLE
Fix install issues and add install testing

### PR DESCRIPTION
**Pull request by jjwilke**
Add installation testing that builds all of Kokkos Kernels tests against an installed library.
Installation tests can be configured as:

````
cmake ${SRC} \
 -DKokkosKernels_INSTALL_TESTING \
 -DKokkosKernels_ROOT=${INSTALL_PREFIX}
````
Here `INSTALL_PREFIX` is the location of an installed Kokkos-Kernels.

### CODE REVIEW

**Comment by jjwilke** [comment]
Also adds bug fixes to the current installation.

**Comment by ndellingwood** [comment]
@jjwilke Very nice! Can you run spot-checks on kokkos-dev-2 and kokkos-dev (just the cuda build) and post results?

**Comment by jjwilke** [comment]
````
#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=117 run_time=152
clang-8.0-Pthread_Serial-release build_time=47 run_time=140
cuda-10.1-Cuda_OpenMP-release build_time=144 run_time=140
cuda-9.2-Cuda_Serial-release build_time=139 run_time=191
gcc-7.3.0-OpenMP-release build_time=45 run_time=45
gcc-7.3.0-Pthread-release build_time=41 run_time=77
gcc-8.3.0-Serial-release build_time=40 run_time=70
gcc-9.1-OpenMP-release build_time=52 run_time=46
gcc-9.1-Serial-release build_time=46 run_time=70
intel-18.0.5-OpenMP-release build_time=148 run_time=45
````

**Comment by jjwilke** [comment]
and kokkos-dev
````
  PASSED cuda-9.2-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
cuda-9.2-Cuda_OpenMP-release build_time=1252 run_time=361
````

**Comment by jjwilke** [comment]
@e10harvey So there was no bug report, actually, otherwise I usually do include an issue number in both the branch name and commit message. I only found the bug after adding the new feature. Would you like me to open an issue as well? I can also change the commit message.

**Comment by e10harvey** [comment]
> So there was no bug report, actually, otherwise I usually do include an issue number in both the branch name and commit message. I only found the bug after adding the new feature. Would you like me to open an issue as well? I can also change the commit message.

@jjwilke, Thank you for clarifying. I don't think an issue should be created if the bug was in the feature that this PR introduces. Going forward, it would be best to open an issue for bugs that already exist in the develop branch.

**Pull request merged**
