### PR TITLE
Release 3.7.01

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Please hold PR until successful pass and merge of https://github.com/trilinos/Trilinos/pull/11347

**Review by brian-kelley — APPROVED** [review]

**Review by e10harvey — APPROVED** [review]

**Comment by e10harvey** [comment]
> Please hold PR until successful pass and merge of [trilinos/Trilinos#11347](https://github.com/trilinos/Trilinos/pull/11347)

@ndellingwood: We may want to include https://github.com/kokkos/kokkos-kernels/pull/1608. See https://github.com/trilinos/Trilinos/pull/11330#issuecomment-1339831196.

**Comment by ndellingwood** [comment]
@e10harvey trying to cherry-pick #1608 is messy various conflicts, for the rdc test referenced can the batched tests be marked with the RUN_SERIAL option to avoid the timeout, or does enabling rdc increase the test time (in which case #1608 is necessary and can't be worked around)?

**Comment by ndellingwood** [comment]
> I think it can wait till 4.0. It is marked as RUN_SERIAL -- perhaps the system load was higher than usual.

Thanks for the update @e10harvey ! If timeout continues to be a problem with the rdc build I'll volunteer to make changes similar to #1608 in Trilinos prior to 4.0 (I think they'll need to be made manually, the repo reorg and other changes made since then make it hard to use git tricks to cleanly pull in the update)

**Comment by ndellingwood** [comment]
https://github.com/trilinos/Trilinos/pull/11347 passed testing, ready for merge

**Pull request merged**
