### PR TITLE
lapack magma tpl fixes

### PR DESCRIPTION
**Pull request by ndellingwood**
Fixes for 4.2.00, apply to patch release 4.2.01
See issue #2042

### CODE REVIEW

**Comment by ndellingwood** [comment]
Trilinos patch https://github.com/trilinos/Trilinos/pull/12555

**Comment by ndellingwood** [comment]
Fails look like they're due to searching for release-candidate-4.2.01 branch of Kokkos (not created yet)

**Comment by ndellingwood** [comment]
These are the test results from Weaver (cuda/11.2, magma-2.7.2):
```
bash-4.4$ ./lapack/unit_test/KokkosKernels_lapack_cuda 
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from Cuda
[ RUN      ] Cuda.gesv_double
[       OK ] Cuda.gesv_double (7740 ms)
[ RUN      ] Cuda.gesv_mrhs_double
[       OK ] Cuda.gesv_mrhs_double (350 ms)
[ RUN      ] Cuda.trtri_double
[       OK ] Cuda.trtri_double (462 ms)
[----------] 3 tests from Cuda (8552 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (8552 ms total)
[  PASSED  ] 3 tests.
```

**Review by lucbv — APPROVED** [review]

**Comment by ndellingwood** [comment]
None of these changes will be hit by CI. Local testing confirms fix for magma (posted above). Going ahead with merge to release-candidate-4.2.01

**Comment by vqd8a** [comment]
@ndellingwood Thanks for doing this.

**Pull request merged**
