### PR TITLE
Backport cusparse tpl spmv changes from Trilinos

### PR DESCRIPTION
**Pull request by brian-kelley**
Includes changes from Trilinos PRs: https://github.com/trilinos/Trilinos/pull/7677 and https://github.com/trilinos/Trilinos/pull/7694

### CODE REVIEW

**Comment by brian-kelley** [comment]
Tested locally with cuda,openmp,serial and --with-tpls=cusparse, but autotester should kick in after review (?)

**Comment by ndellingwood** [comment]
@brian-kelley the autotester isn't enabled yet, I think it is still waiting for a final round of approvals

**Comment by brian-kelley** [comment]
@ndellingwood Got it. Here's kokkos-dev2 with --spot-check-tpls.

BTW, is the spot check supposed to be building and running the examples?
If not, we could probably disable that to shave a few minutes off the testing time.
Although, it did just make me fix a warning in my GS example, so maybe it is useful...

#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=631 run_time=164
clang-8.0-Pthread_Serial-release build_time=209 run_time=111
clang-9.0.0-Pthread-release build_time=125 run_time=52
clang-9.0.0-Serial-release build_time=137 run_time=57
cuda-10.1-Cuda_OpenMP-release build_time=869 run_time=165
gcc-4.8.4-OpenMP-release build_time=116 run_time=59
gcc-7.3.0-OpenMP-release build_time=151 run_time=58
gcc-7.3.0-Pthread-release build_time=118 run_time=53
gcc-8.3.0-Serial-release build_time=141 run_time=59
gcc-9.1-OpenMP-release build_time=182 run_time=59
gcc-9.1-Serial-release build_time=168 run_time=59
intel-17.0.1-Serial-release build_time=256 run_time=56
intel-18.0.5-OpenMP-release build_time=357 run_time=52
intel-19.0.5-Pthread-release build_time=405 run_time=49

**Comment by brian-kelley** [comment]
Added fix for https://github.com/trilinos/Trilinos/issues/7723 , and re running tests.

**Comment by brian-kelley** [comment]
It certainly is questionable to change the numbering scheme between patch versions. Oh well, it should be consistent from now on (we can always use ``CUSPARSE_VERSION`` to detect newer features).

**Pull request merged**
