### PR TITLE
Fixes in KokkosSparse trsv and spiluk for integrating spiluk to ifpack2

### PR DESCRIPTION
**Pull request by vqd8a**
This PR contains fixes in KokkosSparse ```trsv``` and ```spiluk``` to make KokkosSparse ```spiluk``` work in Ifpack2.
The fixes include:
- modifying ```lowerTriSolveCsc```, ```lowerTriSolveCscConj```, ```upperTriSolveCsc```, ```upperTriSolveCscConj``` to make them work with non-unit diagonal matrices 
- adding more test cases for sparse ```trsv```
- increasing the allocated size for ```level_ptr``` in the ```spiluk``` handle to cover the worst case.
- throwing exceptions when L and U were not allocated enough memory during the symbolic phase
- throwing exceptions if the symbolic phase has not been complete before the numeric phase.

### CODE REVIEW

**Comment by vqd8a** [comment]
@ndellingwood Could you please help me run spotchecks? Thanks.

**Comment by ndellingwood** [comment]
Hi @vqd8a, the PR failed testing with cuda/9.2 and uvm enabled in the spot-check (complex_double case), here are some details:

**Failing tests**
```bash
3: [  FAILED  ] 2 tests, listed below:
3: [  FAILED  ] cuda.sparse_trsv_mv_kokkos_complex_double_int_int_LayoutLeft_TestExecSpace
3: [  FAILED  ] cuda.sparse_trsv_mv_kokkos_complex_double_int_size_t_LayoutLeft_TestExecSpace
3: 
3:  2 FAILED TESTS
 3/16 Test  #3: sparse_cuda ......................***Failed   66.90 sec


# Some failure output
[ RUN      ] cuda.sparse_trsv_mv_kokkos_complex_double_int_int_LayoutLeft_TestExecSpace
/ascldap/users/ndellin/kokkos-kernels/unit_test/../test_common/KokkosKernels_TestUtils.hpp:88: Failure
The difference between double(AT1::abs(val1)) and double(AT2::abs(val2)) is 9.0628160233930615, which exceeds double(AT3::abs(tol)), where
double(AT1::abs(val1)) evaluates to 2.1039716219353801,
double(AT2::abs(val2)) evaluates to 11.166787645328441, and
double(AT3::abs(tol)) evaluates to 9.9999999999999995e-08.
/ascldap/users/ndellin/kokkos-kernels/unit_test/../test_common/KokkosKernels_TestUtils.hpp:88: Failure
The difference between double(AT1::abs(val1)) and double(AT2::abs(val2)) is 6.8319424419108978, which exceeds double(AT3::abs(tol)), where
double(AT1::abs(val1)) evaluates to 1.1154367907389393,
double(AT2::abs(val2)) evaluates to 7.9473792326498369, and
double(AT3::abs(tol)) evaluates to 9.9999999999999995e-08.
...
```

**Reproducer instructions**
```bash
module load sems-env sems-cmake/3.12.2 sems-cuda/9.2 sems-gcc/7.3.0

$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Cuda,Serial --arch=SNB,Volta70 --compiler=${KOKKOS_PATH}/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="11" --ldflags="" --with-cuda --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=    --with-options= --with-cuda-options=force_uvm --no-examples
```

The failure occurred testing on kokkos-dev-2 but should be reproducible on a system with similar compilers available (e.g. white or weaver)

**Comment by ndellingwood** [comment]
@vqd8a all other builds and tests passed, including cuda/10.1 without UVM enabled

**Comment by vqd8a** [comment]
@ndellingwood I ran spot-checks again on kokkos-dev-2. They all passed (with and without UVM enabled). Perhaps, like you said, running multiple spot-checks at the same time caused the test failures before.

- without UVM enabled
```../kokkos-kernels/scripts/cm_test_all_sandia --kokkos-path=/ascldap/users/vqdang/Kokkos/kokkos --spot-check```
```
Running on machine: kokkos-dev-2

KokkosKernels Repository Status:  35c48d15824b08350507801d104ed0e1bee195db Fixes in sparse trsv and spiluk for integrating spiluk to ifpack2

Kokkos Repository Status:  117c1b5cf7c46bdf57fd47139e5b08f70e73dccf Merge pull request #3216 from Rombur/clean_team

Going to test compilers:  gcc/7.3.0 gcc/8.3.0 gcc/9.1 gcc/4.8.4 intel/17.0.1 intel/18.0.5 intel/19.0.5 clang/8.0 clang/9.0.0 cuda/10.1 cuda/9.2
...

#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=629 run_time=171
clang-8.0-Pthread_Serial-release build_time=204 run_time=141
clang-9.0.0-Pthread-release build_time=126 run_time=66
clang-9.0.0-Serial-release build_time=129 run_time=57
cuda-10.1-Cuda_OpenMP-release build_time=810 run_time=168
cuda-9.2-Cuda_Serial-release build_time=789 run_time=211
gcc-4.8.4-OpenMP-release build_time=117 run_time=66
gcc-7.3.0-OpenMP-release build_time=144 run_time=64
gcc-7.3.0-Pthread-release build_time=119 run_time=67
gcc-8.3.0-Serial-release build_time=145 run_time=59
gcc-9.1-OpenMP-release build_time=179 run_time=65
gcc-9.1-Serial-release build_time=161 run_time=59
intel-17.0.1-Serial-release build_time=255 run_time=58
intel-18.0.5-OpenMP-release build_time=352 run_time=60
intel-19.0.5-Pthread-release build_time=427 run_time=64
```

- with UVM enabled
```../kokkos-kernels/scripts/cm_test_all_sandia --kokkos-path=/ascldap/users/vqdang/Kokkos/kokkos --spot-check --with-cuda-options=force_uvm```
```
Running on machine: kokkos-dev-2

KokkosKernels Repository Status:  35c48d15824b08350507801d104ed0e1bee195db Fixes in sparse trsv and spiluk for integrating spiluk to ifpack2

Kokkos Repository Status:  117c1b5cf7c46bdf57fd47139e5b08f70e73dccf Merge pull request #3216 from Rombur/clean_team


Going to test compilers:  gcc/7.3.0 gcc/8.3.0 gcc/9.1 gcc/4.8.4 intel/17.0.1 intel/18.0.5 intel/19.0.5 clang/8.0 clang/9.0.0 cuda/10.1 cuda/9.2
...
#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=699 run_time=242
clang-8.0-Pthread_Serial-release build_time=208 run_time=143
clang-9.0.0-Pthread-release build_time=126 run_time=70
clang-9.0.0-Serial-release build_time=171 run_time=60
cuda-10.1-Cuda_OpenMP-release build_time=867 run_time=197
cuda-9.2-Cuda_Serial-release build_time=792 run_time=211
gcc-4.8.4-OpenMP-release build_time=123 run_time=67
gcc-7.3.0-OpenMP-release build_time=167 run_time=66
gcc-7.3.0-Pthread-release build_time=130 run_time=76
gcc-8.3.0-Serial-release build_time=167 run_time=68
gcc-9.1-OpenMP-release build_time=196 run_time=199
gcc-9.1-Serial-release build_time=195 run_time=72
intel-17.0.1-Serial-release build_time=330 run_time=67
intel-18.0.5-OpenMP-release build_time=456 run_time=116
intel-19.0.5-Pthread-release build_time=516 run_time=76
```

**Comment by ndellingwood** [comment]
Thanks @vqd8a, not sure why I saw the failure but thanks for rerunning the testing. Merging.

**Comment by vqd8a** [comment]
@ndellingwood Thank you for reviewing and merging.

**Pull request merged**
