### PR TITLE
Adding Changelog for Release 4.2.0

### PR DESCRIPTION
**Pull request by ndellingwood**
Part of Kokkos C++ Performance Portability Programming EcoSystem 4.2

### CODE REVIEW

**Comment by ndellingwood** [comment]
Added WIP to skip CI

**Review by lucbv — APPROVED** [review]
I made some changes and think it looks good, thanks @ndellingwood

**Review by brian-kelley — APPROVED** [review]

**Comment by ndellingwood** [comment]
Thanks for the updates @lucbv @cwpearson @brian-kelley ! If no further updates are needed, I'll rebase down to a single commit then merge into the release candidate.

**Review by lucbv — APPROVED** [review]
I'm not sure why it looks like the changelog for 4.1.00 is new but besides that I'm good with this PR

**Comment by ndellingwood** [comment]
> I'm not sure why it looks like the changelog for 4.1.00 is new but besides that I'm good with this PR

@lucbv because the release candidate was branched off the develop branch and I forgot to put in a PR to update develop with the 4.1 changelog :( When I merge this to master for the PR to master that should not be present

**Pull request merged**
