### PR TITLE
Fix missing assert with complex<float>

### PR DESCRIPTION
**Pull request by kyungjoo-kim**

### CODE REVIEW

**Comment by kyungjoo-kim** [comment]
#316

**Comment by ndellingwood** [comment]
Compiles now, check with the following generated makefile settings:

```
KOKKOS_PATH=${HOME}/kokkos #path to kokkos source
KOKKOSKERNELS_SCALARS='double,"complex<double>",float,"complex<float>"'.
KOKKOSKERNELS_ORDINALS=int #ordinal types to instantiate
KOKKOSKERNELS_OFFSETS=int #offset types to instantiate
KOKKOSKERNELS_PATH=../.. #path to kokkos-kernels top directory.
CXX=${KOKKOS_PATH}/bin/nvcc_wrapper #icpc #
KOKKOSKERNELS_OPTIONS=eti-only #options for kokkoskernels  
KOKKOS_DEVICES="Cuda,OpenMP,Serial"
KOKKOS_ARCHS="Power8,Kepler37"
CXXFLAGS="-Wall -pedantic -O3 -g -Wshadow -Wsign-compare -Wtype-limits -Wuninitialized"
#CXXFLAGS="-Wall -pedantic -Werror -O3 -g -Wshadow -Wsign-compare -Wtype-limits -Wuninitialized"

../../scripts/generate_makefile.bash --kokkoskernels-path=${KOKKOSKERNELS_PATH} --with-scalars=${KOKKOSKERNELS_SCALARS} --with-ordinals=${KOKKOSKERNELS_ORDINALS} --with-offsets=${KOKKOSKERNELS_OFFSETS} --kokkos-path=${KOKKOS_PATH} --with-devices=${KOKKOS_DEVICES} --arch=${KOKKOS_ARCHS} --compiler=${CXX} --with-options=${KOKKOSKERNELS_OPTIONS}  --cxxflags="${CXXFLAGS}"
```

**Comment by kyungjoo-kim** [comment]
Is this checking this PR? or kokkoskernels in general ?

**Comment by ndellingwood** [comment]
Unit tests are failing, but this is good step forward. Those will be addressed in followup PR.

**Comment by ndellingwood** [comment]
@kyungjoo-kim kokkoskernels in general, I copy/pasted your changes into the repo I was building.

**Pull request merged**
