### PR TITLE
Changelog 3.7.00

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
First pass at the changelog, please push any desired updates to curate

**Review by e10harvey — APPROVED** [review]
Thank you, Nathan!

**Comment by lucbv** [comment]
@ndellingwood I made a bunch of changes to re-organize things a bit, let me know if that looks fine with you.
I am happy with the changelog

**Review by lucbv — APPROVED** [review]
lgtm

**Pull request merged**
