### PR TITLE
exposing more functionalities (e.g., to Ifpack2) from two-stage GS

### PR DESCRIPTION
**Pull request by iyamazaki**
This PR exposes additional functionalities (e.g., use inverse_diagonal provided by Ifpack2) from the two-stage GS.

### CODE REVIEW

**Comment by brian-kelley** [comment]
@iyamazaki I'm running spot checks for this on kokkos-dev2, should take < 2 hours (white and RIDE are still down, it seems). I looked over the changes and don't expect issues, though.

**Comment by brian-kelley** [comment]
Actually, white is up so I'll run it there too

**Comment by iyamazaki** [comment]
Spot-check on White:

#######################################################
PASSED TESTS
#######################################################
cuda-10.1.105-Cuda_OpenMP-release build_time=376 run_time=105
cuda-10.1.105-Cuda_Serial-release build_time=381 run_time=146
cuda-9.2.88-Cuda_OpenMP-release build_time=340 run_time=118
cuda-9.2.88-Cuda_Serial-release build_time=364 run_time=159
gcc-6.4.0-OpenMP_Serial-release build_time=136 run_time=128
gcc-7.2.0-OpenMP-release build_time=103 run_time=44
gcc-7.2.0-OpenMP_Serial-release build_time=139 run_time=127
gcc-7.2.0-Serial-release build_time=89 run_time=80
ibm-16.1.0-Serial-release build_time=611 run_time=88

**Comment by srajama1** [comment]
Are there other spot checks running ? Can I merge ?

**Comment by iyamazaki** [comment]
No.. I am not running any other spot-check. I think it should be good to merge..

**Comment by srajama1** [comment]
Thanks, @iyamazaki !

**Pull request merged**
