### PR TITLE
Replace vendored gtest 1.7 with external 1.15.2

### PR DESCRIPTION
**Pull request by cwpearson**
Replace the vendored gtest 1.7 with external gtest 1.15.2. Either a previously-installed gtest can be used, or it can automatically be retrieved from github.

Specify an existing Gtest with `-DGTest_ROOT=path/to/installed/googletest`

- @lucbv @ndellingwood Trilinos integration concerns?
- [x] Test that using external GTest works
- [x] perf tests need gtest too? (fixed in https://github.com/kokkos/kokkos-kernels/pull/2385)

### CODE REVIEW

**Comment by cwpearson** [comment]
Revisit this after a rebase on https://github.com/kokkos/kokkos-kernels/pull/2385

**Comment by cwpearson** [comment]
I believe testing is blocked by https://github.com/kokkos/kokkos-kernels/pull/2387

**Comment by lucbv** [comment]
We should actually fix the workflow files to make them build against the latest release not develop. I'll go have a look and you can rebase afterward?

**Comment by ndellingwood** [comment]
@cwpearson I tested this with Trilinos (Serial build, sems-gcc/11.4.0) and encountered some issues during configuration:

```
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) (Required is at least version "1.15.2")
-- GTest compatible with 1.15.2 not found. Retrieving from github...
CMake Error at Build/SemsGcc1140OpenMPI416/_deps/googletest-src/googletest/cmake/internal_utils.cmake:165 (add_library):
  add_library cannot create target "gtest" because another target with the
  same name already exists.  The existing target is a shared library created
  in source directory "/ascldap/users/ndellin/Trilinos/commonTools/gtest".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  Build/SemsGcc1140OpenMPI416/_deps/googletest-src/googletest/cmake/internal_utils.cmake:210 (cxx_library_with_type)
  Build/SemsGcc1140OpenMPI416/_deps/googletest-src/googletest/CMakeLists.txt:123 (cxx_library)


CMake Error at cmake/tribits/core/package_arch/TribitsAddExecutable.cmake:560 (message):
  ERROR: 'GTest::Main' in TESTONLYLIBS not a TESTONLY lib! If this a regular
  library in this package or in an dependent upstream package then TriBITS
  will link automatically to it.  If you remove this and it does not link,
  then you need to add a new package dependency to this package's
  dependencies file
  /ascldap/users/ndellin/Trilinos/kokkos-kernels/cmake/Dependencies.cmake
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsAddExecutable.cmake:327 (tribits_add_executable_assert_testonlylibs)
  cmake/tribits/core/package_arch/TribitsAddExecutableAndTest.cmake:40 (tribits_add_executable)
  cmake/tribits/core/package_arch/TribitsAddExecutableAndTest.cmake:202 (tribits_add_executable_wrapper)
  kokkos-kernels/cmake/kokkoskernels_tribits.cmake:233 (TRIBITS_ADD_EXECUTABLE_AND_TEST)
  kokkos-kernels/cmake/kokkoskernels_tribits.cmake:183 (KOKKOSKERNELS_ADD_EXECUTABLE_AND_TEST)
  kokkos-kernels/common/unit_test/CMakeLists.txt:69 (KOKKOSKERNELS_ADD_UNIT_TEST)

```

**Comment by cwpearson** [comment]
@ndellingwood can you give me a bit more about how to reproduce this?

**Comment by ndellingwood** [comment]
@cwpearson reproducer scripts and info sent

**Comment by cwpearson** [comment]
I can't really figure this out. Even if I build this thing entirely internally to Kokkos Kernels, my understanding is that TriBITS feels entitled to dig around in our directories and find literally every target we define and try to export it `tribits_get_all_build_targets_including_in_subdirs`. With this PR, we pull in an external GTest so of course a few GTest-related targets that we're not intending to export get defined.

I think the TESTONLY libs facility is the way around this, but I believe you can't use that with a purely imported target without attaching any of our own sources to it.

**Comment by cwpearson** [comment]
Closed in favor of #2416

**Pull request closed without merging**
