### PR TITLE
Small clean-up in spgemm and sptrsv for clang 7 cuda build with tpls

### PR DESCRIPTION
**Pull request by lucbv**
This allows us to update the `cm_sandia_test_all` script to test tpls on kokkos-dev with the cuda-clang build.

### CODE REVIEW

**Comment by lucbv** [comment]
@ndellingwood I did a build and ran `ctest -V -R` on kokkos-dev using the build described in issue #630, everything builds and runs fine.
Do you want me to run the spot_check on this branch?

**Comment by ndellingwood** [comment]
> Do you want me to run the spot_check on this branch?

@lucbv if you don't mind that would be great, the changes shouldn't hurt anything but probably better to follow process consistently.

**Comment by ndellingwood** [comment]
@lucbv does this also need to get patched into Trilinos? I saw an issue about a clang/7.0.1 PR build being set up.

**Comment by lucbv** [comment]
@ndellingwood as discussed, the Trilinos PR tester using clang 7.0.1 is not performing a cuda build so no worries on that front.
I just did a spot-check on kokkos-dev, here are the results:

#######################################################
PASSED TESTS
#######################################################
clang-4.0.1-Pthread_Serial-hwloc-release build_time=129 run_time=162
clang-4.0.1-Pthread_Serial-release build_time=128 run_time=195
clang-7.0.1-Cuda_OpenMP-hwloc-release build_time=350 run_time=285
clang-7.0.1-Cuda_OpenMP-release build_time=345 run_time=283
cuda-9.2-Cuda_OpenMP-release build_time=395 run_time=251
gcc-5.3.0-OpenMP-hwloc-release build_time=95 run_time=56
gcc-5.3.0-OpenMP-release build_time=95 run_time=55
gcc-7.3.0-Serial-hwloc-release build_time=81 run_time=116
gcc-7.3.0-Serial-release build_time=78 run_time=91
intel-17.0.1-OpenMP-hwloc-release build_time=159 run_time=54
intel-17.0.1-OpenMP-release build_time=151 run_time=54

**Comment by ndellingwood** [comment]
@lucbv merged! I'll add this configuration to the cm_test_all_sandia script and put ina PR shortly.

**Comment by ndellingwood** [comment]
Cross-reference #629

**Pull request merged**
