### PR TITLE
GEMM unit test: Modify way random values set based on execution space

### PR DESCRIPTION
**Pull request by ndellingwood**
Addressed issue #528

### CODE REVIEW

**Comment by ndellingwood** [comment]
Here's initial results testing this on host, I'll post full results when complete

```
[ndellin@kokkos-dev-2 TestAllSandia]$ ../../scripts/test_all_sandia --spot-check gcc/7.3 --skip-hwloc
Running on machine: kokkos-dev-2
Going to test compilers:  gcc/7.3.0
Testing compiler gcc/7.3.0
  Starting job gcc-7.3.0-Pthread-release
  Starting job gcc-7.3.0-OpenMP-release
  PASSED gcc-7.3.0-OpenMP-release
  PASSED gcc-7.3.0-Pthread-release
#######################################################
PASSED TESTS
#######################################################
gcc-7.3.0-OpenMP-release build_time=218 run_time=272
gcc-7.3.0-Pthread-release build_time=204 run_time=455
#######################################################
```

**Comment by seheracer** [comment]
@ndellingwood Thanks for fixing this!

**Comment by ndellingwood** [comment]
> @ndellingwood Thanks for fixing this!

No problem, it was my fault it slipped through by requesting to skip the extra testing for a quick merge

**Comment by ndellingwood** [comment]
Changes addressed in Trilinos as part of PR trilinos/Trilinos#6451

**Comment by ndellingwood** [comment]
Failing in cuda builds now, will update the PR soon...

**Comment by ndellingwood** [comment]
Cuda tests with complex types have large diffs in results, e.g.

```
Result: 6.153095e+02 3.572919e-10
/ascldap/users/ndellin/kokkos-kernels-cmake/unit_test/blas/Test_Blas3_gemm.hpp:165: Failure
Value of: (diff_C_average < 1.05*diff_C_expected )
  Actual: false
Expected: true
```

The Trilinos PR testing does not enable complex types so this was not exposed then.

I think the best thing to do for now is back out the changes to the unit test and revisit more carefully in a future PR. I've updated the PR accordingly.

**Pull request merged**
