### PR TITLE
using namespace should be scoped to prevent name clashes

### PR DESCRIPTION
**Pull request by ndellingwood**
matching changes to PR #1171
see issue #1170

### CODE REVIEW

**Comment by ndellingwood** [comment]
Replaces PR #1173 with changes made manually. Initial round of Cuda_Serial testing passes

**Review by lucbv — APPROVED** [review]
Sorry you had to replicate this by hand...

**Comment by ndellingwood** [comment]
Testing looks good, going ahead with merge and will put in matching PR to Trilinos

**Comment by ndellingwood** [comment]
Matching Trilinos PR trilinos/Trilinos#9910

**Pull request merged**
