### PR TITLE
Update Copyright to Kokkos v. 3.0

### PR DESCRIPTION
**Pull request by crtrott**

### CODE REVIEW

**Comment by crtrott** [comment]
Wait this is wrong ...

**Comment by crtrott** [comment]
ok fixed.

**Comment by srajama1** [comment]
@ndellingwood @jjwilke Can we update the documentation from internal to external ?

**Comment by ndellingwood** [comment]
> @ndellingwood @jjwilke Can we update the documentation from internal to external ?

Done

**Comment by srajama1** [comment]
Thanks @ndellingwood  !

**Comment by ndellingwood** [comment]
@crtrott can you post command-line incantation, similar to how you did here:
Command-line incantations used are documented here: https://github.com/kokkos/kokkos/pull/2737#issuecomment-583788544

This will require a matching commit to develop.

**Comment by ndellingwood** [comment]
Matching PR #616 to develop just issued.
@crtrott do we also need to update the tag in the CHANGELOG?

**Comment by vqd8a** [comment]
NTESS in here?
https://github.com/kokkos/kokkos-kernels/blob/c91f0da6d2b12334872a1bc3c2d9ed710556aa2a/Copyright.txt#L26
https://github.com/kokkos/kokkos-kernels/blob/c91f0da6d2b12334872a1bc3c2d9ed710556aa2a/Copyright.txt#L29

**Comment by ndellingwood** [comment]
@crtrott I just put in a PR to your fork with updates SANDIA -> NTESS

**Comment by ndellingwood** [comment]
@crtrott https://github.com/crtrott/kokkos-kernels/pull/1

**Comment by ndellingwood** [comment]
@crtrott ping for merge of my PR to yours

**Comment by ndellingwood** [comment]
@crtrott added new PR crtrott/kokkos-kernels#2 to your PR that updates the Kokkos v. 2.0 instances, please merge.

**Pull request merged**
