### PR TITLE
Update kk_get_free_total_memory for SYCL

### PR DESCRIPTION
**Pull request by masterleinad**
https://github.com/intel/llvm/pull/6604 at least allows for querying free memory but that isn't available in most releases. This pull request updates the current implementation to allow multiple memory modules. The update closely follows the public implementation https://github.com/intel/llvm/blob/9811ef24694f8dee5c1c8b7dd43047a63f655277/sycl/plugins/level_zero/pi_level_zero.cpp#L3147-L3167.

### CODE REVIEW

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO INSPECTION HAS BEEN PERFORMED ON THIS PULL REQUEST! - This PR must be inspected by setting label 'AT: PRE-TEST INSPECTED'.

**Comment by masterleinad** [comment]
@lucbv ping

**Comment by masterleinad** [comment]
@lucbv ping

**Review by lucbv — APPROVED** [review]
Thanks for updating to the latest and greatest Intel runtime

**Comment by jczhang07** [comment]
@lucbv To test on Sunspot with KK/develop, we need this PR.  If not other issues, could you merge this PR? Thanks.

**Pull request merged**
