### PR TITLE
cast Kokkos::Impl::integral_constant to int

### PR DESCRIPTION
**Pull request by cwpearson**
The bounds on this loop is a `Kokkos::Impl::integral_constant`, which is not appropriate for the iteration variable. So cast it to `int`.

### CODE REVIEW

**Comment by cwpearson** [comment]
Fix for https://github.com/kokkos/kokkos-kernels/issues/1696

**Review by brian-kelley — APPROVED** [review]

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930 to start: Total Wait = 3603
- Other jobs have been previously started - We must stop them...

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930 to start: Total Wait = 3603
- Other jobs have been previously started - We must stop them...

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930 to start: Total Wait = 3603
- Other jobs have been previously started - We must stop them...

**Comment by ndellingwood** [comment]
@e10harvey it seems the `KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930` job is failing to make it to the Weaver rhel8 queue after a couple RETESTS, maybe this just bad luck with too much contention for builds on rhel8?
I looks like `KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930` ran on a couple other PRs, maybe the timeout for the job should be increased so it can wait in the queue a bit longer?

@lucbv @e10harvey based on the changes in the PR (applying a cast) I'd like to merge this PR without another retest, this will resolve multiple nightly build failures (with -Werror) and avoid occupying testing resources for other PRs, does this sound acceptable?

**Review by lucbv — APPROVED** [review]
Good to go

**Pull request merged**
