### PR TITLE
Rename reserved identifiers

### PR DESCRIPTION
**Pull request by cwpearson**
-- edit to describe what this PR does --

This PR does a search-replace style change of include guards that start with `__`, which is a reserved pattern in C++

-- end edit --

This is the easy stuff, not quite everything.

With the added `.clang-tidy` file:

```bash
cmake -S . -B $KERNELS_BUILD \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DCMAKE_CXX_STANDARD=17 \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DKokkos_ROOT=$KOKKOS_INSTALL \
  -DKokkosKernels_ENABLE_TESTS=ON \
  -DKokkosKernels_ENABLE_BENCHMARK=ON \
  -DKokkosKernels_ENABLE_PERFTESTS=ON \
  -DKokkosKernels_ENABLE_EXAMPLES=ON \
  -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wpedantic -Werror -Wimplicit-fallthrough -Wno-unused-result" \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DCMAKE_CXX_CLANG_TIDY="clang-tidy"
fi
```

### CODE REVIEW

**Comment by dalg24** [comment]
So this PR is handling the double underscore right?

**Comment by cwpearson** [comment]
The bugprone-reserved-identifiers check seems to catch reserved patterns reliably (this is my first time using clang-tidy). It may make sense to add it as an automatic check.

**Comment by cwpearson** [comment]
It does catch them, this PR just does one kind of change at a time 😄

**Comment by cwpearson** [comment]
We're not actually running clang-tidy in CI yet, let me get it to pass cleanly when run manually and then I can make a PR to add a CI check.

**Review by lucbv — APPROVED** [review]

**Pull request merged**
