### PR TITLE
Structured spmv

### PR DESCRIPTION
**Pull request by lucbv**
This is an implementation of the algorithm outlined in issue #364. It performs well for all covered stencils for matrices larger than 25k rows.

A unit test and a performance test are added to assess correctness and performance, results have been obtained on white.

### CODE REVIEW

**Comment by mhoemmen** [comment]
It would be nicer to remove the unused or superfluous explicit instantiations, like CudaSpace and CudaUMVSpace, or HostSpace and HBWSpace.

**Comment by lucbv** [comment]
@mhoemmen I do not disagree with this idea but I think we should open a specific issue regarding automatic ETI in Kokkos-Kernels and decide what needs to stay and what can be removed. At the moment all I do is run a specific script that generates automatically all the ETI files for me...

**Comment by srajama1** [comment]
@lucbv Are you done with the changes you wanted to make ? I am checking if it is ok for me to review.

**Comment by crtrott** [comment]
btw. Nathan asked that we stop merging unless its super critical. Because he is close to getting done with the promotion.

**Comment by srajama1** [comment]
Alright, I won't merge.

**Comment by lucbv** [comment]
I'm closing this as this branch is now stale and I have refreshed this work in PR #446

**Pull request closed without merging**
