### PR TITLE
ROCmCC compiler error with Kokkos_ArithTraits.hpp: wrong-side rule

### PR DESCRIPTION
**Pull request by lukebroskop**
Working with Trilinos (using the HIP backend) I ran into a wrong-side rule violation error:

```
/home/users/lroskop/Trilinos/packages/kokkos-kernels/src/Kokkos_ArithTraits.hpp:1112:12: error: no matching function for call to 'isnan'
    return isnan (real (x)) || isnan (imag (x));
...
...
...                                               \
      ^
/opt/rocm-5.0.0/llvm/lib/clang/14.0.0/include/__clang_hip_cmath.h:97:31: note: candidate function not viable: call to __device__ function from __host__ function
__DEVICE__ __CONSTEXPR__ bool isnan(float __x) { return ::__isnanf(__x); }
                              ^
/opt/rocm-5.0.0/llvm/lib/clang/14.0.0/include/__clang_hip_cmath.h:98:31: note: candidate function not viable: call to __device__ function from __host__ function
__DEVICE__ __CONSTEXPR__ bool isnan(double __x) { return ::__isnan(__x); }
```

From: https://github.com/kokkos/kokkos/blob/2834f94af9b01debf67c1aaa3f0eb0c903d72c8d/core/src/Kokkos_Macros.hpp#L493
```
#if defined(__CUDACC__) && defined(__CUDA_ARCH__) && defined(KOKKOS_ENABLE_CUDA)
#define KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_CUDA
#elif defined(__SYCL_DEVICE_ONLY__) && defined(KOKKOS_ENABLE_SYCL)
#define KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_SYCL
#elif defined(__HIPCC__) && defined(__HIP_DEVICE_COMPILE__) && \
    defined(KOKKOS_ENABLE_HIP)
#define KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_HIP_GPU
#else
#define KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_HOST
#endif
```

Neither `KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_HIP_GPU` nor `KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_HOST` are defined. It could be I'm doing something incorrectly, still I would think setting `__HIPCC__`, `__HIP_DEVICE_COMPILE__`, and `KOKKOS_ENABLE_HIP` would result in setting `KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_HIP_GPU` and still lead to the wrong-side rule violation.
There are a few ways around this. But since the `__HIP_DEVICE_COMPILE__` macro is used in other places in `src/Kokkos_ArithTraits.hpp`, maybe just use that?

If I am doing something wrong, please advise how I can fix my compiler error.
Thanks!

### CODE REVIEW

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO INSPECTION HAS BEEN PERFORMED ON THIS PULL REQUEST! - This PR must be inspected by setting label 'AT: PRE-TEST INSPECTED'.

**Comment by lucbv** [comment]
@lukebroskop does this problem also exist in the develop branch of Kokkos Kernels?
Having a reproducer using a Kokkos Core and Kokkos Kernels build would be much simpler than using Trilinos and it is also more useful as Kokkos Kernels is snapshotted in Trilinos and hence can lag quite a bit.

**Comment by lucbv** [comment]
@lukebroskop 
I think this should be resolved now that the ArithTraits have been re-implemented using the Kokkos Math Functions and Numeric Traits. If that's not the case please let us know.

**Comment by lukebroskop** [comment]
Thanks for the update @lucbv. However, I'm still seeing the issue. Here's a diff of what I changed to force things to go through:
```
diff --git a/packages/kokkos-kernels/src/Kokkos_ArithTraits.hpp b/packages/kokkos-kernels/src/Kokkos_ArithTraits.hpp
index bf7235e507b..83228a4416a 100644
--- a/packages/kokkos-kernels/src/Kokkos_ArithTraits.hpp
+++ b/packages/kokkos-kernels/src/Kokkos_ArithTraits.hpp
@@ -1098,6 +1098,8 @@ class ArithTraits<float> {
     using std::isinf;
 #elif defined(KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_SYCL)
     using sycl::isinf;
+#elif defined(__HIP_DEVICE_COMPILE__)
+    using std::isinf;
 #endif
     return isinf(x);
   }
@@ -1106,6 +1108,8 @@ class ArithTraits<float> {
     using std::isnan;
 #elif defined(KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_SYCL)
     using sycl::isnan;
+#elif defined(__HIP_DEVICE_COMPILE__)
+    using std::isnan;
 #endif
     return isnan(x);
   }
@@ -1286,6 +1290,8 @@ class ArithTraits<std::complex<RealFloatType> > {
   static bool isInf(const std::complex<RealFloatType>& x) {
 #ifdef KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_HOST
     using std::isinf;
+#elif defined(__HIP_DEVICE_COMPILE__)
+    using std::isinf;
 #endif
     return isinf(real(x)) || isinf(imag(x));
   }
@@ -1309,6 +1315,8 @@ class ArithTraits<std::complex<RealFloatType> > {
   static bool isNan(const std::complex<RealFloatType>& x) {
 #ifdef KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_HOST
     using std::isnan;
+#elif defined(__HIP_DEVICE_COMPILE__)
+    using std::isnan;
 #endif
     return isnan(real(x)) || isnan(imag(x));
   }
```

**Comment by lucbv** [comment]
@lukebroskop 
If you try the develop version of Kokkos and Kokkos Kernels, the code has changed and I believe should work.
The new version will be part of the 3.7.0 release which will arrive later this summer.
If the new version do not work that would be interesting to know!

**Comment by lukebroskop** [comment]
Thanks for the pointer @lucbv, I'll take a look. Thanks!

**Comment by lucbv** [comment]
@lukebroskop assuming the work I mentioned above fixed you issue I will close this PR.
Thanks for raising this problem and for proposing a fix!

**Pull request closed without merging**
