### PR TITLE
Release 4.3.01

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Hold until confirmation of passing status of Trilinos snapshot PR https://github.com/trilinos/Trilinos/pull/12995

**Comment by ndellingwood** [comment]
Needed a fix for the version check and changelog fix [ca09900](https://github.com/kokkos/kokkos-kernels/pull/2197/commits/ca09900d98508ddb7e775e0447feafd23a9f9751) (thanks @brian-kelley !); rebased and cleaned up the the branch, along with updated snapshot to Trilinos

**Comment by ndellingwood** [comment]
PR https://github.com/trilinos/Trilinos/pull/12995 passed AT checks

**Review by lucbv — APPROVED** [review]
Okay, looks fine to me

**Pull request merged**
