### PR TITLE
Fixed divide-by-zero with compression flops

### PR DESCRIPTION
**Pull request by brian-kelley**
Mirror of https://github.com/trilinos/Trilinos/pull/6780

Bowman
#######################################################
PASSED TESTS
#######################################################
intel-16.4.258-Pthread-release build_time=738 run_time=1060
intel-16.4.258-Pthread_Serial-release build_time=1065 run_time=1982
intel-16.4.258-Serial-release build_time=716 run_time=937
intel-17.2.174-OpenMP-release build_time=889 run_time=563
intel-17.2.174-OpenMP_Serial-release build_time=1236 run_time=1468
intel-17.2.174-Pthread-release build_time=820 run_time=885
intel-17.2.174-Pthread_Serial-release build_time=1126 run_time=1810
intel-17.2.174-Serial-release build_time=783 run_time=895

RIDE
#######################################################
PASSED TESTS
#######################################################
cuda-10.1.105-Cuda_OpenMP-release build_time=286 run_time=193
cuda-10.1.105-Cuda_Serial-release build_time=305 run_time=243
cuda-9.2.88-Cuda_OpenMP-release build_time=319 run_time=197
cuda-9.2.88-Cuda_Serial-release build_time=295 run_time=248
gcc-6.4.0-OpenMP_Serial-release build_time=112 run_time=164
gcc-7.2.0-OpenMP-release build_time=84 run_time=56
gcc-7.2.0-OpenMP_Serial-release build_time=123 run_time=162
gcc-7.2.0-Serial-release build_time=78 run_time=103
ibm-16.1.0-Serial-release build_time=372 run_time=115

### CODE REVIEW

**Comment by srajama1** [comment]
Thanks, @brian-kelley !

**Comment by srajama1** [comment]
This is the second such commit, right ? Is the first one with the test in develop ?

**Comment by brian-kelley** [comment]
@srajama1 Yes it is. This one fixes what just showed up as silent undefined behavior (0/0) but which was killing EMPIRE on debug builds.

**Comment by srajama1** [comment]
Thanks, @brian-kelley ! I am not able to keep track of all PRs I am approving.

**Pull request merged**
