### PR TITLE
SpTrsv: Integrate Kokkos-kernels interface for TRMM & TRTRI

### PR DESCRIPTION
**Pull request by iyamazaki**
This PR
- integrates TRMM & TRTRI interfaces created by the PR #622 
- should also fix the issue #633 with camke build with UVM
- includes supernode-based SpTrsv in the unit-test (but protected with KOKKOSKERNELS_ENABLE_SUPERNODAL_SPTRSV, and TPL BLAS)
- adds an option to perform supernode-based SpTrsv without inverse

### CODE REVIEW

**Comment by iyamazaki** [comment]
Spot-check on White:

#######################################################
PASSED TESTS
#######################################################
cuda-10.1.105-Cuda_OpenMP-release build_time=373 run_time=106
cuda-10.1.105-Cuda_Serial-release build_time=337 run_time=146
cuda-9.2.88-Cuda_OpenMP-release build_time=369 run_time=119
cuda-9.2.88-Cuda_Serial-release build_time=302 run_time=160
gcc-6.4.0-OpenMP_Serial-release build_time=136 run_time=129
gcc-7.2.0-OpenMP-release build_time=101 run_time=43
gcc-7.2.0-OpenMP_Serial-release build_time=126 run_time=127
gcc-7.2.0-Serial-release build_time=91 run_time=79
ibm-16.1.0-Serial-release build_time=597 run_time=89

**Comment by iyamazaki** [comment]
Right now, we only have perf-test, and no unit-test (I was not sure how to provide the supernode/block info to the unit-test). I could probably add an option to the current sptrsv unit test (e.g., with block size of one).

**Comment by e10harvey** [comment]
> Right now, we only have perf-test, and no unit-test (I was not sure how to provide the supernode/block info to the unit-test). I could probably add an option to the current sptrsv unit test (e.g., with block size of one).



> Right now, we only have perf-test, and no unit-test (I was not sure how to provide the supernode/block info to the unit-test). I could probably add an option to the current sptrsv unit test (e.g., with block size of one).

@iyamazaki Does the perf-test produce the expected results with the changes in cd5c6fa?

**Comment by iyamazaki** [comment]
Yes. I have a small script to run perf-test with different parameters and a couple of matrices. Maybe, we can ask @nellingwood if we should create an issue to add this option to the sptrsv unit-test.

**Comment by iyamazaki** [comment]
Results of ../scripts/cm_test_all_sandia --spot-check --arch=Power8,Pascal60 on White:

#######################################################
PASSED TESTS
#######################################################
cuda-10.1.105-Cuda_OpenMP-release build_time=362 run_time=114
cuda-10.1.105-Cuda_Serial-release build_time=401 run_time=155
cuda-9.2.88-Cuda_OpenMP-release build_time=366 run_time=127
cuda-9.2.88-Cuda_Serial-release build_time=354 run_time=169
gcc-6.4.0-OpenMP_Serial-release build_time=150 run_time=132
gcc-7.2.0-OpenMP-release build_time=105 run_time=45
gcc-7.2.0-OpenMP_Serial-release build_time=143 run_time=131
gcc-7.2.0-Serial-release build_time=98 run_time=81
ibm-16.1.0-Serial-release build_time=635 run_time=91

**Comment by iyamazaki** [comment]
Results of ../scripts/cm_test_all_sandia --spot-check-tpls --arch=Power8,Pascal60 --cxxflags-extra='-DKOKKOSKERNELS_ENABLE_SUPERNODAL_SPTRSV=ON' on White:

#######################################################
PASSED TESTS
#######################################################
cuda-10.1.105-Cuda_Serial-release build_time=1503 run_time=531
cuda-9.2.88-Cuda_OpenMP-release build_time=1436 run_time=549
gcc-7.2.0-OpenMP-release build_time=574 run_time=376
gcc-7.2.0-Serial-release build_time=507 run_time=496
gcc-7.4.0-OpenMP-release build_time=574 run_time=207

**Comment by ndellingwood** [comment]
@iyamazaki looks like a merge conflict in `perf_test/sparse/KokkosSparse_sptrsv_superlu.cpp` needs to be resolved, should be able to do this directly through github's web editor

**Comment by ndellingwood** [comment]
```bash
[ndellin@kokkos-dev-2 PRTest]$ nohup ../../scripts/cm_test_all_sandia --spot-check --skip-hwloc &

Running on machine: kokkos-dev-2
WARNING!! THE FOLLOWING CHANGES ARE UNCOMMITTED!! :
 M scripts/cm_test_all_sandia

KokkosKernels Repository Status:  3caa4149a924c2ac51769654f05223435077b825 Merge branch 'develop' into sptrsv-supernode

Kokkos Repository Status:  daf6ac2595549faf04f7fa938db7120c2cb874a4 Merge pull request #2971 from dalg24/rocm-3.3


Going to test compilers:  gcc/7.3.0 gcc/8.3.0 gcc/9.1 intel/17.0.1 intel/18.0.5 intel/19.0.5 clang/8.0 cuda/10.1 cuda/9.2
Testing compiler gcc/7.3.0
  Starting job gcc-7.3.0-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-7.3.0-OpenMP-release
Testing compiler gcc/8.3.0
  Starting job gcc-7.3.0-Pthread-release
kokkos options: 
kokkos devices: Pthread
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-7.3.0-Pthread-release
Testing compiler gcc/9.1
  Starting job gcc-8.3.0-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-8.3.0-Serial-release
  Starting job gcc-9.1-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-9.1-OpenMP-release
Testing compiler intel/17.0.1
  Starting job gcc-9.1-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized 
  PASSED gcc-9.1-Serial-release
Testing compiler intel/18.0.5
  Starting job intel-17.0.1-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED intel-17.0.1-Serial-release
Testing compiler intel/19.0.5
  Starting job intel-18.0.5-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED intel-18.0.5-OpenMP-release
Testing compiler clang/8.0
  Starting job intel-19.0.5-Pthread-release
kokkos options: 
kokkos devices: Pthread
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED intel-19.0.5-Pthread-release
  Starting job clang-8.0-Cuda_OpenMP-release
kokkos options: 
kokkos devices: Cuda,OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -Wno-pass-failed 
  PASSED clang-8.0-Cuda_OpenMP-release
Testing compiler cuda/10.1
  Starting job clang-8.0-Pthread_Serial-release
kokkos options: 
kokkos devices: Pthread,Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -Wno-pass-failed 
  PASSED clang-8.0-Pthread_Serial-release
Testing compiler cuda/9.2
  Starting job cuda-10.1-Cuda_OpenMP-release
kokkos options: 
kokkos devices: Cuda,OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED cuda-10.1-Cuda_OpenMP-release
  Starting job cuda-9.2-Cuda_Serial-release
kokkos options: 
kokkos devices: Cuda,Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED cuda-9.2-Cuda_Serial-release
#######################################################
PASSED TESTS
#######################################################
clang-8.0-Cuda_OpenMP-release build_time=164 run_time=72
clang-8.0-Pthread_Serial-release build_time=70 run_time=49
cuda-10.1-Cuda_OpenMP-release build_time=208 run_time=70
cuda-9.2-Cuda_Serial-release build_time=198 run_time=85
gcc-7.3.0-OpenMP-release build_time=60 run_time=22
gcc-7.3.0-Pthread-release build_time=52 run_time=24
gcc-8.3.0-Serial-release build_time=55 run_time=24
gcc-9.1-OpenMP-release build_time=68 run_time=22
gcc-9.1-Serial-release build_time=59 run_time=24
intel-17.0.1-Serial-release build_time=106 run_time=23
intel-18.0.5-OpenMP-release build_time=177 run_time=21
intel-19.0.5-Pthread-release build_time=201 run_time=22
```

**Comment by ndellingwood** [comment]
Extra test with complex_double enabled in Cuda builds:

```bash
[ndellin@kokkos-dev-2 PRTest]$ nohup ../../scripts/cm_test_all_sandia --spot-check cuda --with-scalars=complex_double &
Running on machine: kokkos-dev-2
WARNING!! THE FOLLOWING CHANGES ARE UNCOMMITTED!! :
 M scripts/cm_test_all_sandia

KokkosKernels Repository Status:  3caa4149a924c2ac51769654f05223435077b825 Merge branch 'develop' into sptrsv-supernode

Kokkos Repository Status:  daf6ac2595549faf04f7fa938db7120c2cb874a4 Merge pull request #2971 from dalg24/rocm-3.3


Going to test compilers:  cuda/10.1 cuda/9.2
Testing compiler cuda/10.1
Testing compiler cuda/9.2
  Starting job cuda-10.1-Cuda_OpenMP-release
kokkos options: 
kokkos devices: Cuda,OpenMP
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED cuda-10.1-Cuda_OpenMP-release
  Starting job cuda-9.2-Cuda_Serial-release
kokkos options: 
kokkos devices: Cuda,Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED cuda-9.2-Cuda_Serial-release
#######################################################
PASSED TESTS
#######################################################
cuda-10.1-Cuda_OpenMP-release build_time=353 run_time=128
cuda-9.2-Cuda_Serial-release build_time=344 run_time=161
```

**Comment by ndellingwood** [comment]
Merging, thanks @iyamazaki !

**Pull request merged**
