### PR TITLE
[4.4.01] Patches to 4.4.01

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Summary of changes from the changelog:

### Build System:
- Restore size_t as default offset, in Tribits builds [\#2313](https://github.com/kokkos/kokkos-kernels/pull/2313)

### Enhancements:
- Improve crs/bsr sorting performance [\#2293](https://github.com/kokkos/kokkos-kernels/pull/2293)

### Bug Fixes:
- SpAdd handle: delete sort_option getter/setter [\#2296](https://github.com/kokkos/kokkos-kernels/pull/2296)
- Improve GH action to produce release artifacts [\#2312](https://github.com/kokkos/kokkos-kernels/pull/2312)
- coo2csr: add parens to function calls [\#2318](https://github.com/kokkos/kokkos-kernels/pull/2318)

**Comment by ndellingwood** [comment]
Noting that AT2 jobs will not run due to block on external user contributions, this does not indicate test failure
```
 [2024-09-04T22:58:07Z ERROR github_api_requester] Failure Status for user dalg24: 404 Not Found
```
@lucbv was this changed in any of the recent AT2 updates, and if so should I pull those in with this PR?

**Comment by lucbv** [comment]
Yes, this was changed in PR #2320 and we can pull it in since it only affects github actions so it is transparent to users : )

**Comment by ndellingwood** [comment]
@lucbv cherry-picked over with SHA a360d0034e1cbd8a804351fd1b3eeec23acb9d16 , but the AT2 jobs still failed with the same issue. Is there a specific label to use?

**Review by lucbv — APPROVED** [review]

**Comment by lucbv** [comment]
Supposedly having me approve and re-run the jobs should have allowed the tests to run @e10harvey do you know why it would fail to run in this case?

**Comment by ndellingwood** [comment]
@lucbv setting the nightly Trilinos integration builds to test with this PR ran fine, including Hip, Cuda, Sycl (Tpetra tests only), OpenMP backends. Should be safe for merge

**Pull request merged**
