### PR TITLE
KokkosKernels: Fix install( ... DESTINATION ... ) dir (#10810)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
Matching PR for #1496 that brings this fix into the branch `release-candidate-3.7.00`.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@lucbv, what does that mean when you assign a PR to a GitHub user who is not a member of the GitHub project?

**Comment by lucbv** [comment]
@bartlettroscoe since you wrote this PR I assume you are willing to do modifications to it if something fail in the auto-tester?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe since you wrote this PR I assume you are willing to do modifications to it if something fail in the auto-tester?

Sure.  Just wanted to know what that meant.

**Review by ndellingwood — APPROVED** [review]
Thanks @bartlettroscoe !

**Pull request merged**
