### PR TITLE
Update testing and KOKKOS_IMPL_BATCHED_GEMM_GCC_CXX14_WORKAROUND

### PR DESCRIPTION
**Pull request by ndellingwood**
Resurfaced issue #349, update to macro for CXX14 workaround issues.
Added gcc/7.4 to testing on white testbed.
Added support for kokkos-dev-2 system for testing.
Extra fixes caught while spot-check testing on kokkos-dev-2
* Shadow warning of type in KokkosSparse_spmv_struct_impl.hpp
* Missing test for Threads backend in KokkosGraph_color_d2.cpp

### CODE REVIEW

**Comment by ndellingwood** [comment]
@srajama1 Spot-check passed with c++14 support on the gcc's 7.2, 7.3, 7.4, and spot-check on kokkos-dev-2. Due to issues that popped up that I fixed along the way I don't have a clean screen output of passing tests to post.

**Comment by ndellingwood** [comment]
Follow-up items:
1. Re-enable `-Werror` for the clang builds on kokkos-dev-2 when we resume testing off of Kokkos' develop branch
2. Add nightly testing on kokkos-dev-2 when PR is merged

**Comment by ndellingwood** [comment]
@aprokop thanks for reporting, I'm assuming this PR is not as important to you as a fix in Trilinos so I'll put a patch in for the `KOKKOS_IMPL_BATCHED_GEMM_GCC_CXX14_WORKAROUND` update you required.

**Comment by srajama1** [comment]
Can we file an issue for this, so we don't forget.

> Follow-up items:
> 
>     1. Re-enable `-Werror` for the clang builds on kokkos-dev-2 when we resume testing off of Kokkos' develop branch
> 
>     2. Add nightly testing on kokkos-dev-2 when PR is merged

**Comment by ndellingwood** [comment]
@srajama1 will do! I'll merge this in, can you approve the trilinos/Trilinos#6164 patch as well? I have that set to auto-merge, it is only the 1-line change Andrey requested, the other cleanup stuff in this PR can come in during the next promotion when we clobber Trilinos' kokkos-kernels.

**Comment by ndellingwood** [comment]
@srajama1 issue created with follow-up items, trial run of first automated build on kokkos-dev-2 successful :)

**Pull request merged**
