### PR TITLE
Avoid enum without fixed underlying type to fix SYCL

### PR DESCRIPTION
**Pull request by masterleinad**
Compiling the tests for the  SYCL backend currently fails with
```
clang++: warning: CUDA version is newer than the latest supported version 11.5 [-Wunknown-cuda-version]
clang++: warning: CUDA version is newer than the latest supported version 11.5 [-Wunknown-cuda-version]
In file included from /app/kokkos-kernels/ode/unit_test/backends/Test_SYCL_ODE.cpp:19:
In file included from /app/kokkos-kernels/test_common/Test_SYCL.hpp:17:
In file included from /app/kokkos-install/include/Kokkos_Core.hpp:43:
In file included from /app/kokkos-install/include/Kokkos_Core_fwd.hpp:28:
In file included from /app/kokkos-install/include/Kokkos_Macros.hpp:96:
In file included from /app/kokkos-install/include/KokkosCore_Config_SetupBackend.hpp:22:
In file included from /app/kokkos-install/include/setup/Kokkos_Setup_SYCL.hpp:36:
In file included from /opt/intel/oneapi/compiler/2023.0.0/linux/bin-llvm/../include/sycl/sycl.hpp:16:
In file included from /opt/intel/oneapi/compiler/2023.0.0/linux/bin-llvm/../include/sycl/backend.hpp:18:
In file included from /opt/intel/oneapi/compiler/2023.0.0/linux/bin-llvm/../include/sycl/detail/backend_traits_opencl.hpp:26:
In file included from /opt/intel/oneapi/compiler/2023.0.0/linux/bin-llvm/../include/sycl/queue.hpp:21:
/opt/intel/oneapi/compiler/2023.0.0/linux/bin-llvm/../include/sycl/handler.hpp:1253:50: error: unscoped enum 'newton_solver_status' requires fixed underlying type
    kernel_parallel_for<KernelName, ElementType>(KernelFunc);
                                                 ^
/opt/intel/oneapi/compiler/2023.0.0/linux/bin-llvm/../include/sycl/handler.hpp:1042:7: note: in instantiation of function template specialization 'sycl::handler::kernel_parallel_for_wrapper<sycl::detail::RoundedRangeKernel<sycl::item<1, true>, 1, Kokkos::Impl::FunctorWrapperRangePolicyParallelFor<Kokkos::Experimental::Impl::SYCLFunctionWrapper<Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Experimental::SYCL, Kokkos::Experimental::SYCLDeviceUSMSpace>, KokkosODE::Experimental::newton_solver_status, true>, Kokkos::Experimental::Impl::SYCLInternal::USMObjectMem<sycl::usm::alloc::host>, true>, Kokkos::RangePolicy<Kokkos::Experimental::SYCL, Kokkos::IndexType<long>>>>, sycl::item<1, true>, sycl::detail::RoundedRangeKernel<sycl::item<1, true>, 1, Kokkos::Impl::FunctorWrapperRangePolicyParallelFor<Kokkos::Experimental::Impl::SYCLFunctionWrapper<Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Experimental::SYCL, Kokkos::Experimental::SYCLDeviceUSMSpace>, KokkosODE::Experimental::newton_solver_status, true>, Kokkos::Experimental::Impl::SYCLInternal::USMObjectMem<sycl::usm::alloc::host>, true>, Kokkos::RangePolicy<Kokkos::Experimental::SYCL, Kokkos::IndexType<long>>>>>' requested here
      kernel_parallel_for_wrapper<KName, TransformedArgType>(Wrapper);
      ^
/opt/intel/oneapi/compiler/2023.0.0/linux/bin-llvm/../include/sycl/handler.hpp:1471:5: note: in instantiation of function template specialization 'sycl::handler::parallel_for_lambda_impl<Kokkos::Impl::FunctorWrapperRangePolicyParallelFor<Kokkos::Experimental::Impl::SYCLFunctionWrapper<Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Experimental::SYCL, Kokkos::Experimental::SYCLDeviceUSMSpace>, KokkosODE::Experimental::newton_solver_status, true>, Kokkos::Experimental::Impl::SYCLInternal::USMObjectMem<sycl::usm::alloc::host>, true>, Kokkos::RangePolicy<Kokkos::Experimental::SYCL, Kokkos::IndexType<long>>>, Kokkos::Impl::FunctorWrapperRangePolicyParallelFor<Kokkos::Experimental::Impl::SYCLFunctionWrapper<Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Experimental::SYCL, Kokkos::Experimental::SYCLDeviceUSMSpace>, KokkosODE::Experimental::newton_solver_status, true>, Kokkos::Experimental::Impl::SYCLInternal::USMObjectMem<sycl::usm::alloc::host>, true>, Kokkos::RangePolicy<Kokkos::Experimental::SYCL, Kokkos::IndexType<long>>>, 1>' requested here
    parallel_for_lambda_impl<KernelName>(NumWorkItems, std::move(KernelFunc));
    ^
/app/kokkos-install/include/SYCL/Kokkos_SYCL_Parallel_Range.hpp:94:13: note: in instantiation of function template specialization 'sycl::handler::parallel_for<Kokkos::Impl::FunctorWrapperRangePolicyParallelFor<Kokkos::Experimental::Impl::SYCLFunctionWrapper<Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Experimental::SYCL, Kokkos::Experimental::SYCLDeviceUSMSpace>, KokkosODE::Experimental::newton_solver_status, true>, Kokkos::Experimental::Impl::SYCLInternal::USMObjectMem<sycl::usm::alloc::host>, true>, Kokkos::RangePolicy<Kokkos::Experimental::SYCL, Kokkos::IndexType<long>>>, Kokkos::Impl::FunctorWrapperRangePolicyParallelFor<Kokkos::Experimental::Impl::SYCLFunctionWrapper<Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Experimental::SYCL, Kokkos::Experimental::SYCLDeviceUSMSpace>, KokkosODE::Experimental::newton_solver_status, true>, Kokkos::Experimental::Impl::SYCLInternal::USMObjectMem<sycl::usm::alloc::host>, true>, Kokkos::RangePolicy<Kokkos::Experimental::SYCL, Kokkos::IndexType<long>>>>' requested here
        cgh.parallel_for<FunctorWrapperRangePolicyParallelFor<Functor, Policy>>(
            ^
/app/kokkos-install/include/SYCL/Kokkos_SYCL_Parallel_Range.hpp:133:25: note: in instantiation of function template specialization 'Kokkos::Impl::ParallelFor<Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Experimental::SYCL, Kokkos::Experimental::SYCLDeviceUSMSpace>, KokkosODE::Experimental::newton_solver_status, true>, Kokkos::RangePolicy<Kokkos::Experimental::SYCL, Kokkos::IndexType<long>>, Kokkos::Experimental::SYCL>::sycl_direct_launch<Kokkos::Experimental::Impl::SYCLFunctionWrapper<Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Experimental::SYCL, Kokkos::Experimental::SYCLDeviceUSMSpace>, KokkosODE::Experimental::newton_solver_status, true>, Kokkos::Experimental::Impl::SYCLInternal::USMObjectMem<sycl::usm::alloc::host>, true>>' requested here
    sycl::event event = sycl_direct_launch(m_policy, functor_wrapper,
                        ^
/app/kokkos-install/include/impl/Kokkos_ViewMapping.hpp:3105:15: note: in instantiation of member function 'Kokkos::Impl::ParallelFor<Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Experimental::SYCL, Kokkos::Experimental::SYCLDeviceUSMSpace>, KokkosODE::Experimental::newton_solver_status, true>, Kokkos::RangePolicy<Kokkos::Experimental::SYCL, Kokkos::IndexType<long>>, Kokkos::Experimental::SYCL>::execute' requested here
      closure.execute();
              ^
/app/kokkos-install/include/impl/Kokkos_ViewMapping.hpp:3075:7: note: (skipping 1 context in backtrace; use -ftemplate-backtrace-limit=0 to see all)
      parallel_for_implementation();
      ^
/app/kokkos-install/include/impl/Kokkos_ViewMapping.hpp:3456:27: note: in instantiation of function template specialization 'Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Experimental::SYCL, Kokkos::Experimental::SYCLDeviceUSMSpace>, KokkosODE::Experimental::newton_solver_status, true>::construct_shared_allocation<KokkosODE::Experimental::newton_solver_status>' requested here
        record->m_destroy.construct_shared_allocation();
                          ^
/app/kokkos-install/include/Kokkos_View.hpp:1421:60: note: in instantiation of function template specialization 'Kokkos::Impl::ViewMapping<Kokkos::ViewTraits<KokkosODE::Experimental::newton_solver_status *, Kokkos::Experimental::SYCL>, void>::allocate_shared<std::basic_string<char>, Kokkos::Experimental::SYCLDeviceUSMSpace, Kokkos::Experimental::SYCL>' requested here
    Kokkos::Impl::SharedAllocationRecord<>* record = m_map.allocate_shared(
                                                           ^
/app/kokkos-install/include/Kokkos_View.hpp:1512:9: note: in instantiation of function template specialization 'Kokkos::View<KokkosODE::Experimental::newton_solver_status *, Kokkos::Experimental::SYCL>::View<std::basic_string<char>>' requested here
      : View(Impl::ViewCtorProp<std::string>(arg_label),
        ^
/app/kokkos-kernels/ode/unit_test/Test_ODE_Newton.hpp:218:56: note: in instantiation of function template specialization 'Kokkos::View<KokkosODE::Experimental::newton_solver_status *, Kokkos::Experimental::SYCL>::View<char[21]>' requested here
  Kokkos::View<newton_solver_status*, execution_space> status(
                                                       ^
/app/kokkos-kernels/ode/unit_test/Test_ODE_Newton.hpp:525:11: note: in instantiation of function template specialization 'Test::test_newton_status<Kokkos::Experimental::SYCL, float>' requested here
  ::Test::test_newton_status<TestExecSpace, float>();
          ^
[...]
```
Just providing an underlying type for `enum` in question fixes the issue.

### CODE REVIEW

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO INSPECTION HAS BEEN PERFORMED ON THIS PULL REQUEST! - This PR must be inspected by setting label 'AT: PRE-TEST INSPECTED'.

**Comment by lucbv** [comment]
Ah good to know, that one was my mistake, I did not test the time integration solvers with SYCL... will be more careful before merging #1930 which introduces more enums...

**Review by lucbv — APPROVED** [review]

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight</h3>
<ul>
  <li>Build Num: 816</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/masterleinad/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>30a2e3f92dd6e98954c1275ca498aaefc7b00d5a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>a0684e1e5ada8e0114b9bdf21a54605b7ee8a40b</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Cleanup</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1940</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930_Tpls_CLANG13CUDA10</h3>
<ul>
  <li>Build Num: 407</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/masterleinad/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>30a2e3f92dd6e98954c1275ca498aaefc7b00d5a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>a0684e1e5ada8e0114b9bdf21a54605b7ee8a40b</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Cleanup</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1940</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_GNU1021</h3>
<ul>
  <li>Build Num: 80</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/masterleinad/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>30a2e3f92dd6e98954c1275ca498aaefc7b00d5a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>a0684e1e5ada8e0114b9bdf21a54605b7ee8a40b</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Cleanup</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1940</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_GNU1021_Light_LayoutRight</h3>
<ul>
  <li>Build Num: 79</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/masterleinad/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>30a2e3f92dd6e98954c1275ca498aaefc7b00d5a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>a0684e1e5ada8e0114b9bdf21a54605b7ee8a40b</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Cleanup</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1940</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_GNU1021</h3>
<ul>
  <li>Build Num: 79</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/masterleinad/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>30a2e3f92dd6e98954c1275ca498aaefc7b00d5a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>a0684e1e5ada8e0114b9bdf21a54605b7ee8a40b</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Cleanup</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1940</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_INTEL19_solo</h3>
<ul>
  <li>Build Num: 85</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/masterleinad/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>30a2e3f92dd6e98954c1275ca498aaefc7b00d5a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>a0684e1e5ada8e0114b9bdf21a54605b7ee8a40b</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Cleanup</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1940</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_CLANG1001_solo</h3>
<ul>
  <li>Build Num: 69</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/masterleinad/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>30a2e3f92dd6e98954c1275ca498aaefc7b00d5a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>a0684e1e5ada8e0114b9bdf21a54605b7ee8a40b</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Cleanup</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1940</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_A64FX_Tpls_ARMPL2110</h3>
<ul>
  <li>Build Num: 580</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/masterleinad/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>30a2e3f92dd6e98954c1275ca498aaefc7b00d5a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>a0684e1e5ada8e0114b9bdf21a54605b7ee8a40b</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Cleanup</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1940</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_A64FX_GCC1020</h3>
<ul>
  <li>Build Num: 575</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/masterleinad/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>30a2e3f92dd6e98954c1275ca498aaefc7b00d5a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>a0684e1e5ada8e0114b9bdf21a54605b7ee8a40b</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Cleanup</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1940</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_VEGA908_ROCM520</h3>
<ul>
  <li>Build Num: 574</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/masterleinad/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>30a2e3f92dd6e98954c1275ca498aaefc7b00d5a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>a0684e1e5ada8e0114b9bdf21a54605b7ee8a40b</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Cleanup</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1940</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_VEGA908_Tpls_ROCM520</h3>
<ul>
  <li>Build Num: 96</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/masterleinad/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>30a2e3f92dd6e98954c1275ca498aaefc7b00d5a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>a0684e1e5ada8e0114b9bdf21a54605b7ee8a40b</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Cleanup</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1940</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>
</details>

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ lucbv ]!

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - Pull Request MUST BE MERGED MANUALLY BY Project Team - This Repo does not support Automerge

**Pull request merged**
