### PR TITLE
Fixup 3.7.01

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Review by brian-kelley — APPROVED** [review]

**Review by vqd8a — APPROVED** [review]

**Comment by ndellingwood** [comment]
Corresponding Trilinos changes submitted with PR https://github.com/trilinos/Trilinos/pull/11434

**Comment by ndellingwood** [comment]
PR updated to include cherry-picks of #1528 and #1530

**Comment by ndellingwood** [comment]
@lucbv when you get a moment to take a look, I'd like to get your blessing before merge (this is a fixup to master with Trilinos patches I missed in 3.7.01)

**Review by lucbv — APPROVED** [review]
Thanks @ndellingwood this looks fine with me

**Pull request merged**
